UPDATE pages SET meta_data = json_set(json_set(meta_data, '$.relatedJobs', json('[{"slug":"제과사-및-제빵사","name":"제과사 및 제빵사"},{"slug":"바리스타","name":"바리스타"},{"slug":"한식조리사","name":"한식조리사"}]')), '$.relatedMajors', json('[{"slug":"식품영양학과","name":"식품영양학과"},{"slug":"식품조리학과","name":"식품조리학과"},{"slug":"식품공학과","name":"식품공학과"}]')) WHERE id = 6749;
UPDATE pages SET meta_data = json_set(json_set(meta_data, '$.relatedJobs', json('[{"slug":"데이터분석가일반","name":"데이터분석가(일반)"},{"slug":"데이터분석가빅데이터분석가","name":"데이터분석가(빅데이터분석가)"},{"slug":"빅데이터전문가","name":"빅데이터전문가"},{"slug":"인공지능엔지니어","name":"인공지능엔지니어"}]')), '$.relatedMajors', json('[{"slug":"통계학과","name":"통계학과"},{"slug":"컴퓨터공학과","name":"컴퓨터공학과"},{"slug":"산업공학과","name":"산업공학과"}]')) WHERE id = 6747;
UPDATE pages SET meta_data = json_set(meta_data, '$.relatedJobs', json('[{"slug":"경비원","name":"경비원"},{"slug":"경호원","name":"경호원"},{"slug":"정보보안전문가","name":"정보보안전문가"},{"slug":"청원경찰","name":"청원경찰"}]')) WHERE id = 6746;
UPDATE pages SET meta_data = json_set(meta_data, '$.relatedJobs', json('[{"slug":"소방관","name":"소방관"},{"slug":"소방시설설계기술자","name":"소방시설설계기술자"},{"slug":"건축시공기술자","name":"건축시공기술자"},{"slug":"전기기술자","name":"전기기술자"}]')) WHERE id = 6707;
UPDATE pages SET meta_data = json_set(json_set(meta_data, '$.relatedJobs', json('[{"slug":"손해사정사","name":"손해사정사"},{"slug":"보험계리사","name":"보험계리사"},{"slug":"보험설계사","name":"보험설계사"},{"slug":"변호사","name":"변호사"}]')), '$.relatedMajors', json('[{"slug":"법학과","name":"법학과"},{"slug":"경영학과","name":"경영학과"},{"slug":"금융보험학과","name":"금융·보험학과"},{"slug":"간호학과","name":"간호학과"}]')) WHERE id = 6706;
UPDATE pages SET meta_data = json_set(meta_data, '$.relatedJobs', json('[{"slug":"데이터분석가일반","name":"데이터분석가(일반)"},{"slug":"데이터엔지니어","name":"데이터엔지니어"},{"slug":"데이터분석가빅데이터분석가","name":"데이터분석가(빅데이터분석가)"},{"slug":"빅데이터전문가","name":"빅데이터전문가"}]')) WHERE id = 6705;
UPDATE pages SET meta_data = json_set(meta_data, '$.relatedJobs', json('[{"slug":"위생사","name":"위생사"},{"slug":"보건교사","name":"보건교사"},{"slug":"영양사","name":"영양사"},{"slug":"식품공학기술자","name":"식품공학기술자"},{"slug":"환경공학기술자","name":"환경공학기술자"}]')) WHERE id = 6696;
UPDATE pages SET meta_data = json_set(meta_data, '$.relatedJobs', json('[{"slug":"주택관리사","name":"주택관리사"},{"slug":"부동산중개인","name":"부동산중개인"},{"slug":"건설자재관리사무원","name":"건설자재관리사무원"},{"slug":"열전기시설관리원","name":"열전기시설관리원"}]')) WHERE id = 6695;
UPDATE pages SET meta_data = json_set(meta_data, '$.relatedJobs', json('[{"slug":"건축가건축설계사","name":"건축가(건축설계사)"},{"slug":"건설안전관리원","name":"건설안전관리원"},{"slug":"건축사","name":"건축사"},{"slug":"공사현장관리자","name":"공사현장관리자"},{"slug":"일반공무원","name":"일반공무원"}]')) WHERE id = 6688;
UPDATE pages SET meta_data = json_set(meta_data, '$.relatedJobs', json('[{"slug":"관세사","name":"관세사"},{"slug":"세무사","name":"세무사"},{"slug":"회계사","name":"회계사"},{"slug":"물류관리사","name":"물류관리사"}]')) WHERE id = 6687;
UPDATE pages SET meta_data = json_set(meta_data, '$.relatedJobs', json('[{"slug":"정부행정사무원일반","name":"정부행정사무원(일반)"},{"slug":"경영지원관리자","name":"경영지원관리자"},{"slug":"회계사무원","name":"회계사무원"},{"slug":"데이터분석가일반","name":"데이터분석가(일반)"}]')) WHERE id = 6686;
UPDATE pages SET meta_data = json_set(meta_data, '$.relatedMajors', json('[{"slug":"관광경영학과","name":"관광경영학과"},{"slug":"영어영문학과","name":"영어영문학과"}]')) WHERE id = 6681;
UPDATE pages SET meta_data = json_set(json_set(meta_data, '$.relatedJobs', json('[{"slug":"바리스타","name":"바리스타"}]')), '$.relatedMajors', json('[{"slug":"식품영양학과","name":"식품영양학과"},{"slug":"호텔외식경영과","name":"호텔외식경영과"}]')) WHERE id = 6680;
UPDATE pages SET meta_data = json_set(meta_data, '$.relatedJobs', json('[{"slug":"노무사","name":"노무사"},{"slug":"인사사무원","name":"인사사무원"}]')) WHERE id = 6679;
UPDATE pages SET meta_data = json_set(json_set(meta_data, '$.relatedJobs', json('[{"slug":"응용소프트웨어개발자","name":"응용소프트웨어개발자"},{"slug":"데이터엔지니어","name":"데이터엔지니어"},{"slug":"웹개발자","name":"웹개발자"}]')), '$.relatedMajors', json('[{"slug":"컴퓨터공학과","name":"컴퓨터공학과"},{"slug":"소프트웨어공학과","name":"소프트웨어공학과"}]')) WHERE id = 3937;
DELETE FROM wiki_pages WHERE slug = '제과기능사-오븐-앞에서-울지-않으려면-이것만은-알아두자';
DELETE FROM wiki_pages WHERE slug = '빅데이터분석기사-비전공자가-실기까지-뚫는-6개월-전략';
DELETE FROM wiki_pages WHERE slug = '경비지도사-2차-커트라인-90점의-벽을-넘는-법';
DELETE FROM wiki_pages WHERE slug = '소방설비기사-쌍기사의-꿈은-현실이-될-수-있을까';
DELETE FROM wiki_pages WHERE slug = '손해사정사-합격률-5의-벽-너머에-있는-것들';
DELETE FROM wiki_pages WHERE slug = 'ADsP-비전공자도-한-달이면-데이터-문맹-탈출한다';
DELETE FROM wiki_pages WHERE slug = '위생사-보건소·식약처로-가는-조용한-자격증';
DELETE FROM wiki_pages WHERE slug = '주택관리사-아파트-관리소장이-되는-가장-현실적인-루트';
DELETE FROM wiki_pages WHERE slug = '건축기사-구조역학만-넘으면-절반은-온-거다';
DELETE FROM wiki_pages WHERE slug = '관세사-무역의-관문을-여는-열쇠는-법조문에-있다';
DELETE FROM wiki_pages WHERE slug = '컴활-1급-엑셀-왕초보도-한-달이면-딸-수-있다';
DELETE FROM wiki_pages WHERE slug = '관광통역안내사-외국어만-잘하면-되는-줄-알았다';
DELETE FROM wiki_pages WHERE slug = '바리스타-2급-커피-한-잔도-못-내리던-내가-한-달-만에-딴-이야기';
DELETE FROM wiki_pages WHERE slug = '공인노무사-2차-합격률-9의-벽을-넘으려면';
DELETE FROM wiki_pages WHERE slug = '코딩-테스트-합격-가이드-언어-선택부터-실전-전략까지';