SELECT COUNT(*) as total,
  SUM(CASE WHEN json_extract(merged_profile_json, '$.way') IS NOT NULL AND json_extract(merged_profile_json, '$.way') != '' THEN 1 ELSE 0 END) as has_way,
  SUM(CASE WHEN json_extract(merged_profile_json, '$.overviewWork.main') IS NOT NULL THEN 1 ELSE 0 END) as has_duties,
  SUM(CASE WHEN json_extract(merged_profile_json, '$.overviewSalary.sal') IS NOT NULL OR json_extract(merged_profile_json, '$.overviewSalary.wage') IS NOT NULL THEN 1 ELSE 0 END) as has_salary,
  SUM(CASE WHEN json_extract(merged_profile_json, '$.overviewProspect.main') IS NOT NULL THEN 1 ELSE 0 END) as has_prospect,
  SUM(CASE WHEN json_extract(merged_profile_json, '$.overviewAptitude.aptitudeList') IS NOT NULL THEN 1 ELSE 0 END) as has_aptitude,
  SUM(CASE WHEN json_extract(merged_profile_json, '$.overviewAptitude.interestList') IS NOT NULL THEN 1 ELSE 0 END) as has_interest,
  SUM(CASE WHEN json_extract(merged_profile_json, '$.detailReady.curriculum') IS NOT NULL THEN 1 ELSE 0 END) as has_curriculum,
  SUM(CASE WHEN json_extract(merged_profile_json, '$.detailReady.certificate') IS NOT NULL THEN 1 ELSE 0 END) as has_certificate,
  SUM(CASE WHEN json_extract(merged_profile_json, '$.detailReady.training') IS NOT NULL THEN 1 ELSE 0 END) as has_training,
  SUM(CASE WHEN json_extract(merged_profile_json, '$.trivia') IS NOT NULL AND json_extract(merged_profile_json, '$.trivia') != '[]' THEN 1 ELSE 0 END) as has_trivia,
  SUM(CASE WHEN json_extract(merged_profile_json, '$.sidebarJobs') IS NOT NULL THEN 1 ELSE 0 END) as has_sidebarJobs,
  SUM(CASE WHEN json_extract(merged_profile_json, '$.sidebarMajors') IS NOT NULL THEN 1 ELSE 0 END) as has_sidebarMajors,
  SUM(CASE WHEN json_extract(merged_profile_json, '$.sidebarCerts') IS NOT NULL THEN 1 ELSE 0 END) as has_sidebarCerts
FROM jobs WHERE is_active = 1
