-- Batch tagging SQL generated at 2026-01-06T08:12:07.322Z
-- Tagger version: tagger-v1.0.0
-- Total jobs: 24

BEGIN TRANSACTION;


INSERT INTO job_attributes (
  job_id, job_name, source_system, tagger_version, status,
  wlb, growth, stability, income,
  teamwork, solo_deep, analytical, creative, execution, people_facing,
  work_hours, shift_work, travel, remote_possible,
  degree_required, license_required, experience_required,
  _confidence, _field_confidence_json, evidence_json
) VALUES (
  '1765284410370881',
  '카드판촉사무원',
  'WORK24_DJOB',
  'tagger-v1.0.0',
  'tagged',
  65, 60, 75, 50,
  70, 30, 75, 50, 70, 60,
  'regular', 'none', 'none', 'partial',
  'bachelor', 'none', 'none',
  0.82,
  '{"wlb":0.8,"growth":0.7,"stability":0.85,"income":0.6,"teamwork":0.8,"solo_deep":0.5,"analytical":0.85,"creative":0.7,"execution":0.8,"people_facing":0.7,"degree_required":0.9,"license_required":0.8}',
  '{"wlb":"실내 사무직으로 정규 근무","growth":"판촉 기획으로 전문성 향상 기회 좋음","stability":"카드사 업무로 비교적 안정적","income":"전문 판촉 업무로 중상위 소득","teamwork":"지표 설정, 업적 평가로 협업 多","solo_deep":"정보 분석, 기획 수립으로 독립 작업","analytical":"판촉 자료 분석, 달성율 분석으로 분석 중심","creative":"서비스 개선 기획으로 창의성 요구","execution":"목표 설정, 제도 개선 실행 중심","people_facing":"지점 협의, 회원 유치 지원으로 대면 업무","degree_required":"대졸 정도 학력 요구","license_required":"특별 자격증 요구 없음"}'
)
ON CONFLICT(job_id) DO UPDATE SET
  job_name = excluded.job_name,
  tagger_version = excluded.tagger_version,
  status = excluded.status,
  wlb = excluded.wlb,
  growth = excluded.growth,
  stability = excluded.stability,
  income = excluded.income,
  teamwork = excluded.teamwork,
  solo_deep = excluded.solo_deep,
  analytical = excluded.analytical,
  creative = excluded.creative,
  execution = excluded.execution,
  people_facing = excluded.people_facing,
  work_hours = excluded.work_hours,
  shift_work = excluded.shift_work,
  travel = excluded.travel,
  remote_possible = excluded.remote_possible,
  degree_required = excluded.degree_required,
  license_required = excluded.license_required,
  experience_required = excluded.experience_required,
  _confidence = excluded._confidence,
  _field_confidence_json = excluded._field_confidence_json,
  evidence_json = excluded.evidence_json,
  updated_at = CURRENT_TIMESTAMP;


INSERT INTO job_attributes (
  job_id, job_name, source_system, tagger_version, status,
  wlb, growth, stability, income,
  teamwork, solo_deep, analytical, creative, execution, people_facing,
  work_hours, shift_work, travel, remote_possible,
  degree_required, license_required, experience_required,
  _confidence, _field_confidence_json, evidence_json
) VALUES (
  '1765284410701427',
  '카드회원사후관리원',
  'WORK24_DJOB',
  'tagger-v1.0.0',
  'tagged',
  65, 45, 80, 45,
  60, 40, 65, 25, 75, 70,
  'regular', 'none', 'none', 'none',
  'none', 'none', 'entry',
  0.85,
  '{"wlb":0.8,"growth":0.6,"stability":0.9,"income":0.6,"teamwork":0.7,"solo_deep":0.6,"analytical":0.7,"creative":0.4,"execution":0.8,"people_facing":0.8,"degree_required":0.95,"license_required":0.9}',
  '{"wlb":"실내 사무직으로 정규 근무","growth":"사후 관리 업무로 성장 기회 제한적","stability":"카드사 업무로 안정적","income":"사무직으로 중간 수준 소득","teamwork":"연체 관리, 자료 확인으로 협업 필요","solo_deep":"거래 정지 심사, 자료 입력으로 독립 작업 多","analytical":"연체 내역 분석, 거래 정지 결정으로 분석 요구","creative":"표준화된 업무로 창의성 낮음","execution":"연체 처리, 자료 입력 실행 중심","people_facing":"회원 상담, 거주지 변경 처리로 대면 업무 多","degree_required":"고졸 정도 학력 요구","license_required":"특별 자격증 요구 없음"}'
)
ON CONFLICT(job_id) DO UPDATE SET
  job_name = excluded.job_name,
  tagger_version = excluded.tagger_version,
  status = excluded.status,
  wlb = excluded.wlb,
  growth = excluded.growth,
  stability = excluded.stability,
  income = excluded.income,
  teamwork = excluded.teamwork,
  solo_deep = excluded.solo_deep,
  analytical = excluded.analytical,
  creative = excluded.creative,
  execution = excluded.execution,
  people_facing = excluded.people_facing,
  work_hours = excluded.work_hours,
  shift_work = excluded.shift_work,
  travel = excluded.travel,
  remote_possible = excluded.remote_possible,
  degree_required = excluded.degree_required,
  license_required = excluded.license_required,
  experience_required = excluded.experience_required,
  _confidence = excluded._confidence,
  _field_confidence_json = excluded._field_confidence_json,
  evidence_json = excluded.evidence_json,
  updated_at = CURRENT_TIMESTAMP;


INSERT INTO job_attributes (
  job_id, job_name, source_system, tagger_version, status,
  wlb, growth, stability, income,
  teamwork, solo_deep, analytical, creative, execution, people_facing,
  work_hours, shift_work, travel, remote_possible,
  degree_required, license_required, experience_required,
  _confidence, _field_confidence_json, evidence_json
) VALUES (
  '1765284411017378',
  '코스닥시장운영원',
  'WORK24_DJOB',
  'tagger-v1.0.0',
  'tagged',
  70, 60, 85, 55,
  60, 40, 75, 35, 75, 45,
  'regular', 'none', 'none', 'partial',
  'bachelor', 'none', 'none',
  0.83,
  '{"wlb":0.8,"growth":0.7,"stability":0.95,"income":0.7,"teamwork":0.7,"solo_deep":0.6,"analytical":0.85,"creative":0.6,"execution":0.8,"people_facing":0.6,"degree_required":0.9,"license_required":0.8}',
  '{"wlb":"실내 사무직으로 정규 근무","growth":"시장 운영으로 전문성 향상 기회 좋음","stability":"한국거래소 업무로 매우 안정적","income":"전문 시장 운영으로 상위 소득","teamwork":"시장 운영, 시황 분석으로 협업 필요","solo_deep":"매매 체결, 시세 공표로 독립 작업","analytical":"시황 분석, 동향 분석으로 분석 중심","creative":"시장 운영 제도 개선으로 일부 창의성","execution":"매매 체결, 시세 공표 실행 중심","people_facing":"내부 보고로 대면 업무 적음","degree_required":"대졸 정도 학력 요구","license_required":"특별 자격증 요구 없음"}'
)
ON CONFLICT(job_id) DO UPDATE SET
  job_name = excluded.job_name,
  tagger_version = excluded.tagger_version,
  status = excluded.status,
  wlb = excluded.wlb,
  growth = excluded.growth,
  stability = excluded.stability,
  income = excluded.income,
  teamwork = excluded.teamwork,
  solo_deep = excluded.solo_deep,
  analytical = excluded.analytical,
  creative = excluded.creative,
  execution = excluded.execution,
  people_facing = excluded.people_facing,
  work_hours = excluded.work_hours,
  shift_work = excluded.shift_work,
  travel = excluded.travel,
  remote_possible = excluded.remote_possible,
  degree_required = excluded.degree_required,
  license_required = excluded.license_required,
  experience_required = excluded.experience_required,
  _confidence = excluded._confidence,
  _field_confidence_json = excluded._field_confidence_json,
  evidence_json = excluded.evidence_json,
  updated_at = CURRENT_TIMESTAMP;


INSERT INTO job_attributes (
  job_id, job_name, source_system, tagger_version, status,
  wlb, growth, stability, income,
  teamwork, solo_deep, analytical, creative, execution, people_facing,
  work_hours, shift_work, travel, remote_possible,
  degree_required, license_required, experience_required,
  _confidence, _field_confidence_json, evidence_json
) VALUES (
  '1765284411370636',
  '파생상품시장운영원',
  'WORK24_DJOB',
  'tagger-v1.0.0',
  'tagged',
  70, 65, 85, 60,
  60, 40, 80, 40, 75, 40,
  'regular', 'none', 'none', 'partial',
  'bachelor', 'none', 'none',
  0.81,
  '{"wlb":0.8,"growth":0.8,"stability":0.95,"income":0.7,"teamwork":0.7,"solo_deep":0.6,"analytical":0.9,"creative":0.6,"execution":0.8,"people_facing":0.6,"degree_required":0.9,"license_required":0.8}',
  '{"wlb":"실내 사무직으로 정규 근무","growth":"파생상품 시장 운영으로 전문성 향상 기회 매우 좋음","stability":"한국거래소 업무로 매우 안정적","income":"전문 파생상품 운영으로 높은 소득","teamwork":"시장 운영, 시황 분석으로 협업 필요","solo_deep":"매매 체결, 시세 공표로 독립 작업","analytical":"파생상품 시황 분석, 동향 분석으로 분석 중심","creative":"시장 운영 전략으로 일부 창의성","execution":"매매 체결, 시장 조치 실행 중심","people_facing":"내부 협의로 대면 업무 적음","degree_required":"대졸 정도 학력 요구","license_required":"특별 자격증 요구 없음"}'
)
ON CONFLICT(job_id) DO UPDATE SET
  job_name = excluded.job_name,
  tagger_version = excluded.tagger_version,
  status = excluded.status,
  wlb = excluded.wlb,
  growth = excluded.growth,
  stability = excluded.stability,
  income = excluded.income,
  teamwork = excluded.teamwork,
  solo_deep = excluded.solo_deep,
  analytical = excluded.analytical,
  creative = excluded.creative,
  execution = excluded.execution,
  people_facing = excluded.people_facing,
  work_hours = excluded.work_hours,
  shift_work = excluded.shift_work,
  travel = excluded.travel,
  remote_possible = excluded.remote_possible,
  degree_required = excluded.degree_required,
  license_required = excluded.license_required,
  experience_required = excluded.experience_required,
  _confidence = excluded._confidence,
  _field_confidence_json = excluded._field_confidence_json,
  evidence_json = excluded.evidence_json,
  updated_at = CURRENT_TIMESTAMP;


INSERT INTO job_attributes (
  job_id, job_name, source_system, tagger_version, status,
  wlb, growth, stability, income,
  teamwork, solo_deep, analytical, creative, execution, people_facing,
  work_hours, shift_work, travel, remote_possible,
  degree_required, license_required, experience_required,
  _confidence, _field_confidence_json, evidence_json
) VALUES (
  '1765284411684706',
  '한국거래소시장감시원',
  'WORK24_DJOB',
  'tagger-v1.0.0',
  'tagged',
  70, 65, 85, 60,
  70, 30, 85, 45, 75, 55,
  'regular', 'none', 'none', 'partial',
  'bachelor', 'none', 'none',
  0.8,
  '{"wlb":0.8,"growth":0.8,"stability":0.95,"income":0.7,"teamwork":0.8,"solo_deep":0.5,"analytical":0.95,"creative":0.6,"execution":0.8,"people_facing":0.7,"degree_required":0.9,"license_required":0.8}',
  '{"wlb":"실내 사무직으로 정규 근무","growth":"시장 감시로 전문성 향상 기회 좋음","stability":"한국거래소 업무로 매우 안정적","income":"전문 시장 감시로 높은 소득","teamwork":"불공정거래 모니터링, 분쟁 조정으로 협업 多","solo_deep":"거래 모니터링, 심리로 독립 작업","analytical":"불공정거래 분석, 심리로 분석 중심","creative":"감시 전략 개발로 일부 창의성","execution":"감시 조치, 분쟁 처리 실행 중심","people_facing":"분쟁 상담, 고객 지원으로 대면 업무","degree_required":"대졸 정도 학력 요구","license_required":"특별 자격증 요구 없음"}'
)
ON CONFLICT(job_id) DO UPDATE SET
  job_name = excluded.job_name,
  tagger_version = excluded.tagger_version,
  status = excluded.status,
  wlb = excluded.wlb,
  growth = excluded.growth,
  stability = excluded.stability,
  income = excluded.income,
  teamwork = excluded.teamwork,
  solo_deep = excluded.solo_deep,
  analytical = excluded.analytical,
  creative = excluded.creative,
  execution = excluded.execution,
  people_facing = excluded.people_facing,
  work_hours = excluded.work_hours,
  shift_work = excluded.shift_work,
  travel = excluded.travel,
  remote_possible = excluded.remote_possible,
  degree_required = excluded.degree_required,
  license_required = excluded.license_required,
  experience_required = excluded.experience_required,
  _confidence = excluded._confidence,
  _field_confidence_json = excluded._field_confidence_json,
  evidence_json = excluded.evidence_json,
  updated_at = CURRENT_TIMESTAMP;


INSERT INTO job_attributes (
  job_id, job_name, source_system, tagger_version, status,
  wlb, growth, stability, income,
  teamwork, solo_deep, analytical, creative, execution, people_facing,
  work_hours, shift_work, travel, remote_possible,
  degree_required, license_required, experience_required,
  _confidence, _field_confidence_json, evidence_json
) VALUES (
  '1765284412101576',
  '한국거래소청산결제사무원',
  'WORK24_DJOB',
  'tagger-v1.0.0',
  'tagged',
  70, 60, 85, 55,
  65, 35, 75, 35, 80, 45,
  'regular', 'none', 'none', 'partial',
  'bachelor', 'none', 'none',
  0.82,
  '{"wlb":0.8,"growth":0.7,"stability":0.95,"income":0.7,"teamwork":0.8,"solo_deep":0.5,"analytical":0.85,"creative":0.6,"execution":0.9,"people_facing":0.6,"degree_required":0.9,"license_required":0.8}',
  '{"wlb":"실내 사무직으로 정규 근무","growth":"청산 결제 운영으로 전문성 향상 기회 좋음","stability":"한국거래소 업무로 매우 안정적","income":"전문 청산 결제로 상위 소득","teamwork":"결제 업무, 위원회 운영으로 협업 필요","solo_deep":"증거금 관리, 결제 처리로 독립 작업","analytical":"결제 제도 숙지, 손해배상 관리로 분석 요구","creative":"결제 시스템 개선으로 일부 창의성","execution":"청산 결제, 증거금 관리 실행 중심","people_facing":"내부 협의로 대면 업무 적음","degree_required":"대졸 정도 학력 요구","license_required":"특별 자격증 요구 없음"}'
)
ON CONFLICT(job_id) DO UPDATE SET
  job_name = excluded.job_name,
  tagger_version = excluded.tagger_version,
  status = excluded.status,
  wlb = excluded.wlb,
  growth = excluded.growth,
  stability = excluded.stability,
  income = excluded.income,
  teamwork = excluded.teamwork,
  solo_deep = excluded.solo_deep,
  analytical = excluded.analytical,
  creative = excluded.creative,
  execution = excluded.execution,
  people_facing = excluded.people_facing,
  work_hours = excluded.work_hours,
  shift_work = excluded.shift_work,
  travel = excluded.travel,
  remote_possible = excluded.remote_possible,
  degree_required = excluded.degree_required,
  license_required = excluded.license_required,
  experience_required = excluded.experience_required,
  _confidence = excluded._confidence,
  _field_confidence_json = excluded._field_confidence_json,
  evidence_json = excluded.evidence_json,
  updated_at = CURRENT_TIMESTAMP;


INSERT INTO job_attributes (
  job_id, job_name, source_system, tagger_version, status,
  wlb, growth, stability, income,
  teamwork, solo_deep, analytical, creative, execution, people_facing,
  work_hours, shift_work, travel, remote_possible,
  degree_required, license_required, experience_required,
  _confidence, _field_confidence_json, evidence_json
) VALUES (
  '1765284412483594',
  '무형재산권관리원',
  'WORK24_DJOB',
  'tagger-v1.0.0',
  'tagged',
  70, 65, 75, 55,
  60, 40, 75, 50, 70, 65,
  'regular', 'none', 'none', 'partial',
  'bachelor', 'none', 'none',
  0.81,
  '{"wlb":0.8,"growth":0.8,"stability":0.85,"income":0.7,"teamwork":0.7,"solo_deep":0.6,"analytical":0.85,"creative":0.7,"execution":0.8,"people_facing":0.8,"degree_required":0.9,"license_required":0.8}',
  '{"wlb":"실내 사무직으로 정규 근무","growth":"지식재산권 관리로 전문성 향상 기회 좋음","stability":"특허 관리 업무로 비교적 안정적","income":"전문 지식재산권 관리로 상위 소득","teamwork":"계약 체결, 불법 이용 조사로 협업 필요","solo_deep":"권리 조사, 계약 체결로 독립 작업","analytical":"권리 조사, 이용 현황 분석으로 분석 중심","creative":"권리 관리 전략으로 창의성 요구","execution":"계약 체결, 임대료 징수 실행 중심","people_facing":"권리자 협의, 이용자 상담으로 대면 업무 多","degree_required":"대졸 정도 학력 요구","license_required":"특별 자격증 요구 없음"}'
)
ON CONFLICT(job_id) DO UPDATE SET
  job_name = excluded.job_name,
  tagger_version = excluded.tagger_version,
  status = excluded.status,
  wlb = excluded.wlb,
  growth = excluded.growth,
  stability = excluded.stability,
  income = excluded.income,
  teamwork = excluded.teamwork,
  solo_deep = excluded.solo_deep,
  analytical = excluded.analytical,
  creative = excluded.creative,
  execution = excluded.execution,
  people_facing = excluded.people_facing,
  work_hours = excluded.work_hours,
  shift_work = excluded.shift_work,
  travel = excluded.travel,
  remote_possible = excluded.remote_possible,
  degree_required = excluded.degree_required,
  license_required = excluded.license_required,
  experience_required = excluded.experience_required,
  _confidence = excluded._confidence,
  _field_confidence_json = excluded._field_confidence_json,
  evidence_json = excluded.evidence_json,
  updated_at = CURRENT_TIMESTAMP;


INSERT INTO job_attributes (
  job_id, job_name, source_system, tagger_version, status,
  wlb, growth, stability, income,
  teamwork, solo_deep, analytical, creative, execution, people_facing,
  work_hours, shift_work, travel, remote_possible,
  degree_required, license_required, experience_required,
  _confidence, _field_confidence_json, evidence_json
) VALUES (
  '1765284412803877',
  '법무사무원',
  'WORK24_DJOB',
  'tagger-v1.0.0',
  'tagged',
  70, 60, 80, 50,
  65, 35, 75, 40, 75, 70,
  'regular', 'none', 'none', 'partial',
  'bachelor', 'none', 'none',
  0.83,
  '{"wlb":0.8,"growth":0.7,"stability":0.9,"income":0.6,"teamwork":0.8,"solo_deep":0.5,"analytical":0.85,"creative":0.6,"execution":0.8,"people_facing":0.8,"degree_required":0.9,"license_required":0.8}',
  '{"wlb":"실내 사무직으로 정규 근무","growth":"법무 업무 지원으로 전문성 향상 기회 좋음","stability":"법무사무소 업무로 안정적","income":"전문 법무 업무로 중상위 소득","teamwork":"서류 작성, 제출로 협업 필요","solo_deep":"법조문 조사, 서류 작성으로 독립 작업","analytical":"법조문 분석, 판례 조사로 분석 중심","creative":"법률 서류 작성으로 일부 창의성","execution":"서류 작성, 제출 실행 중심","people_facing":"의뢰인 상담으로 대면 업무 多","degree_required":"대졸 정도 학력 요구","license_required":"특별 자격증 요구 없음"}'
)
ON CONFLICT(job_id) DO UPDATE SET
  job_name = excluded.job_name,
  tagger_version = excluded.tagger_version,
  status = excluded.status,
  wlb = excluded.wlb,
  growth = excluded.growth,
  stability = excluded.stability,
  income = excluded.income,
  teamwork = excluded.teamwork,
  solo_deep = excluded.solo_deep,
  analytical = excluded.analytical,
  creative = excluded.creative,
  execution = excluded.execution,
  people_facing = excluded.people_facing,
  work_hours = excluded.work_hours,
  shift_work = excluded.shift_work,
  travel = excluded.travel,
  remote_possible = excluded.remote_possible,
  degree_required = excluded.degree_required,
  license_required = excluded.license_required,
  experience_required = excluded.experience_required,
  _confidence = excluded._confidence,
  _field_confidence_json = excluded._field_confidence_json,
  evidence_json = excluded.evidence_json,
  updated_at = CURRENT_TIMESTAMP;


INSERT INTO job_attributes (
  job_id, job_name, source_system, tagger_version, status,
  wlb, growth, stability, income,
  teamwork, solo_deep, analytical, creative, execution, people_facing,
  work_hours, shift_work, travel, remote_possible,
  degree_required, license_required, experience_required,
  _confidence, _field_confidence_json, evidence_json
) VALUES (
  '1765284413083891',
  '변호사사무원',
  'WORK24_DJOB',
  'tagger-v1.0.0',
  'tagged',
  70, 60, 80, 50,
  70, 30, 80, 45, 75, 75,
  'regular', 'none', 'none', 'partial',
  'bachelor', 'none', 'none',
  0.81,
  '{"wlb":0.8,"growth":0.7,"stability":0.9,"income":0.6,"teamwork":0.8,"solo_deep":0.5,"analytical":0.9,"creative":0.6,"execution":0.8,"people_facing":0.85,"degree_required":0.9,"license_required":0.8}',
  '{"wlb":"실내 사무직으로 정규 근무","growth":"변호사 업무 지원으로 전문성 향상 기회 좋음","stability":"법률 사무소 업무로 안정적","income":"전문 법률 업무로 중상위 소득","teamwork":"사건 자료 수집, 서류 작성으로 협업 多","solo_deep":"법조문 조사, 분석으로 독립 작업","analytical":"법조문 분석, 판례 조사로 분석 중심","creative":"법률 서류 작성으로 창의성 요구","execution":"서류 작성, 제출 실행 중심","people_facing":"의뢰인 상담, 법률 정보 제공으로 대면 업무 多","degree_required":"대졸 정도 학력 요구","license_required":"특별 자격증 요구 없음"}'
)
ON CONFLICT(job_id) DO UPDATE SET
  job_name = excluded.job_name,
  tagger_version = excluded.tagger_version,
  status = excluded.status,
  wlb = excluded.wlb,
  growth = excluded.growth,
  stability = excluded.stability,
  income = excluded.income,
  teamwork = excluded.teamwork,
  solo_deep = excluded.solo_deep,
  analytical = excluded.analytical,
  creative = excluded.creative,
  execution = excluded.execution,
  people_facing = excluded.people_facing,
  work_hours = excluded.work_hours,
  shift_work = excluded.shift_work,
  travel = excluded.travel,
  remote_possible = excluded.remote_possible,
  degree_required = excluded.degree_required,
  license_required = excluded.license_required,
  experience_required = excluded.experience_required,
  _confidence = excluded._confidence,
  _field_confidence_json = excluded._field_confidence_json,
  evidence_json = excluded.evidence_json,
  updated_at = CURRENT_TIMESTAMP;


INSERT INTO job_attributes (
  job_id, job_name, source_system, tagger_version, status,
  wlb, growth, stability, income,
  teamwork, solo_deep, analytical, creative, execution, people_facing,
  work_hours, shift_work, travel, remote_possible,
  degree_required, license_required, experience_required,
  _confidence, _field_confidence_json, evidence_json
) VALUES (
  '1765284413444681',
  '석유화학지식재산권관리자',
  'WORK24_DJOB',
  'tagger-v1.0.0',
  'tagged',
  70, 70, 75, 65,
  60, 40, 85, 55, 70, 55,
  'regular', 'none', 'none', 'partial',
  'bachelor', 'none', 'none',
  0.78,
  '{"wlb":0.8,"growth":0.8,"stability":0.85,"income":0.8,"teamwork":0.7,"solo_deep":0.6,"analytical":0.95,"creative":0.7,"execution":0.8,"people_facing":0.7,"degree_required":0.9,"license_required":0.8}',
  '{"wlb":"실내 사무직으로 정규 근무","growth":"석유화학 특허 관리로 전문성 향상 기회 매우 좋음","stability":"기업 지식재산권 업무로 비교적 안정적","income":"전문 특허 관리로 높은 소득","teamwork":"선행기술 조사, 특허 출원으로 협업 필요","solo_deep":"기술 분석, 특허 전략 수립으로 독립 작업","analytical":"선행기술 조사, 특허 평가로 분석 중심","creative":"특허 전략 수립으로 창의성 높음","execution":"특허 출원, 분쟁 대응 실행 중심","people_facing":"특허 담당자 협의로 대면 업무","degree_required":"대졸 정도 학력 요구","license_required":"특별 자격증 요구 없음"}'
)
ON CONFLICT(job_id) DO UPDATE SET
  job_name = excluded.job_name,
  tagger_version = excluded.tagger_version,
  status = excluded.status,
  wlb = excluded.wlb,
  growth = excluded.growth,
  stability = excluded.stability,
  income = excluded.income,
  teamwork = excluded.teamwork,
  solo_deep = excluded.solo_deep,
  analytical = excluded.analytical,
  creative = excluded.creative,
  execution = excluded.execution,
  people_facing = excluded.people_facing,
  work_hours = excluded.work_hours,
  shift_work = excluded.shift_work,
  travel = excluded.travel,
  remote_possible = excluded.remote_possible,
  degree_required = excluded.degree_required,
  license_required = excluded.license_required,
  experience_required = excluded.experience_required,
  _confidence = excluded._confidence,
  _field_confidence_json = excluded._field_confidence_json,
  evidence_json = excluded.evidence_json,
  updated_at = CURRENT_TIMESTAMP;


INSERT INTO job_attributes (
  job_id, job_name, source_system, tagger_version, status,
  wlb, growth, stability, income,
  teamwork, solo_deep, analytical, creative, execution, people_facing,
  work_hours, shift_work, travel, remote_possible,
  degree_required, license_required, experience_required,
  _confidence, _field_confidence_json, evidence_json
) VALUES (
  '1765284421549734',
  '여행콜센터상담원',
  'WORK24_DJOB',
  'tagger-v1.0.0',
  'tagged',
  55, 50, 70, 40,
  70, 30, 60, 40, 75, 90,
  'regular', 'possible', 'none', 'none',
  'college', 'none', 'entry',
  0.84,
  '{"wlb":0.7,"growth":0.6,"stability":0.8,"income":0.6,"teamwork":0.8,"solo_deep":0.5,"analytical":0.7,"creative":0.6,"execution":0.8,"people_facing":0.95,"degree_required":0.9,"license_required":0.9}',
  '{"wlb":"콜센터 업무로 교대 근무 가능, 야근 있을 수 있음","growth":"여행 상담으로 고객 응대 능력 향상 기회 있음","stability":"여행사 업무로 비교적 안정적","income":"콜센터 업무로 중간 수준 소득","teamwork":"콜센터 팀으로 협업 多","solo_deep":"개별 상담으로 독립 작업","analytical":"상품 정보 분석, 고객 요구 파악으로 분석 요구","creative":"여행 상품 제안으로 일부 창의성","execution":"상담, 판매 확정 실행 중심","people_facing":"고객 상담, 판매로 대면 업무 매우 多","degree_required":"전문대졸 정도 학력 요구","license_required":"특별 자격증 요구 없음"}'
)
ON CONFLICT(job_id) DO UPDATE SET
  job_name = excluded.job_name,
  tagger_version = excluded.tagger_version,
  status = excluded.status,
  wlb = excluded.wlb,
  growth = excluded.growth,
  stability = excluded.stability,
  income = excluded.income,
  teamwork = excluded.teamwork,
  solo_deep = excluded.solo_deep,
  analytical = excluded.analytical,
  creative = excluded.creative,
  execution = excluded.execution,
  people_facing = excluded.people_facing,
  work_hours = excluded.work_hours,
  shift_work = excluded.shift_work,
  travel = excluded.travel,
  remote_possible = excluded.remote_possible,
  degree_required = excluded.degree_required,
  license_required = excluded.license_required,
  experience_required = excluded.experience_required,
  _confidence = excluded._confidence,
  _field_confidence_json = excluded._field_confidence_json,
  evidence_json = excluded.evidence_json,
  updated_at = CURRENT_TIMESTAMP;


INSERT INTO job_attributes (
  job_id, job_name, source_system, tagger_version, status,
  wlb, growth, stability, income,
  teamwork, solo_deep, analytical, creative, execution, people_facing,
  work_hours, shift_work, travel, remote_possible,
  degree_required, license_required, experience_required,
  _confidence, _field_confidence_json, evidence_json
) VALUES (
  '1765284421929873',
  '경기장통신원',
  'WORK24_DJOB',
  'tagger-v1.0.0',
  'tagged',
  60, 35, 75, 35,
  70, 30, 50, 25, 80, 70,
  'regular', 'possible', 'none', 'none',
  'none', 'none', 'entry',
  0.86,
  '{"wlb":0.7,"growth":0.5,"stability":0.85,"income":0.5,"teamwork":0.8,"solo_deep":0.5,"analytical":0.6,"creative":0.4,"execution":0.9,"people_facing":0.8,"degree_required":0.95,"license_required":0.9}',
  '{"wlb":"경기장 업무로 교대 근무 가능","growth":"스포츠 행정 업무로 성장 기회 제한적","stability":"공공 스포츠 시설 업무로 안정적","income":"행정 업무로 중간 수준 소득","teamwork":"투표위원 협의로 협업 필요","solo_deep":"안내방송, 통보로 독립 작업","analytical":"매출, 인원 데이터 확인으로 일부 분석","creative":"표준화된 업무로 창의성 낮음","execution":"안내방송, 통보 실행 중심","people_facing":"투표위원, 관계자와 협의로 대면 업무 多","degree_required":"고졸 정도 학력 요구","license_required":"특별 자격증 요구 없음"}'
)
ON CONFLICT(job_id) DO UPDATE SET
  job_name = excluded.job_name,
  tagger_version = excluded.tagger_version,
  status = excluded.status,
  wlb = excluded.wlb,
  growth = excluded.growth,
  stability = excluded.stability,
  income = excluded.income,
  teamwork = excluded.teamwork,
  solo_deep = excluded.solo_deep,
  analytical = excluded.analytical,
  creative = excluded.creative,
  execution = excluded.execution,
  people_facing = excluded.people_facing,
  work_hours = excluded.work_hours,
  shift_work = excluded.shift_work,
  travel = excluded.travel,
  remote_possible = excluded.remote_possible,
  degree_required = excluded.degree_required,
  license_required = excluded.license_required,
  experience_required = excluded.experience_required,
  _confidence = excluded._confidence,
  _field_confidence_json = excluded._field_confidence_json,
  evidence_json = excluded.evidence_json,
  updated_at = CURRENT_TIMESTAMP;


INSERT INTO job_attributes (
  job_id, job_name, source_system, tagger_version, status,
  wlb, growth, stability, income,
  teamwork, solo_deep, analytical, creative, execution, people_facing,
  work_hours, shift_work, travel, remote_possible,
  degree_required, license_required, experience_required,
  _confidence, _field_confidence_json, evidence_json
) VALUES (
  '1765284422303809',
  '고객전자메일접수원',
  'WORK24_DJOB',
  'tagger-v1.0.0',
  'tagged',
  70, 40, 70, 35,
  60, 40, 55, 30, 75, 60,
  'regular', 'none', 'none', 'partial',
  'none', 'none', 'entry',
  0.87,
  '{"wlb":0.8,"growth":0.6,"stability":0.8,"income":0.5,"teamwork":0.7,"solo_deep":0.6,"analytical":0.7,"creative":0.5,"execution":0.8,"people_facing":0.7,"degree_required":0.95,"license_required":0.9}',
  '{"wlb":"실내 사무직으로 정규 근무","growth":"고객 응대 경험으로 성장 기회 제한적","stability":"인터넷 서비스 업무로 비교적 안정적","income":"접수 업무로 중간 수준 소득","teamwork":"응대 공유로 협업 필요","solo_deep":"메일 분석, 답변 작성으로 독립 작업","analytical":"문의 내용 파악으로 분석 요구","creative":"답변 작성으로 일부 창의성","execution":"답변 작성, 발송 실행 중심","people_facing":"고객 응대, 상담으로 대면 업무 적음","degree_required":"고졸 정도 학력 요구","license_required":"특별 자격증 요구 없음"}'
)
ON CONFLICT(job_id) DO UPDATE SET
  job_name = excluded.job_name,
  tagger_version = excluded.tagger_version,
  status = excluded.status,
  wlb = excluded.wlb,
  growth = excluded.growth,
  stability = excluded.stability,
  income = excluded.income,
  teamwork = excluded.teamwork,
  solo_deep = excluded.solo_deep,
  analytical = excluded.analytical,
  creative = excluded.creative,
  execution = excluded.execution,
  people_facing = excluded.people_facing,
  work_hours = excluded.work_hours,
  shift_work = excluded.shift_work,
  travel = excluded.travel,
  remote_possible = excluded.remote_possible,
  degree_required = excluded.degree_required,
  license_required = excluded.license_required,
  experience_required = excluded.experience_required,
  _confidence = excluded._confidence,
  _field_confidence_json = excluded._field_confidence_json,
  evidence_json = excluded.evidence_json,
  updated_at = CURRENT_TIMESTAMP;


INSERT INTO job_attributes (
  job_id, job_name, source_system, tagger_version, status,
  wlb, growth, stability, income,
  teamwork, solo_deep, analytical, creative, execution, people_facing,
  work_hours, shift_work, travel, remote_possible,
  degree_required, license_required, experience_required,
  _confidence, _field_confidence_json, evidence_json
) VALUES (
  '1765284422570332',
  '공항의전원',
  'WORK24_DJOB',
  'tagger-v1.0.0',
  'tagged',
  65, 50, 85, 45,
  75, 25, 50, 35, 80, 85,
  'regular', 'possible', 'none', 'none',
  'college', 'none', 'none',
  0.83,
  '{"wlb":0.8,"growth":0.7,"stability":0.95,"income":0.6,"teamwork":0.8,"solo_deep":0.4,"analytical":0.6,"creative":0.5,"execution":0.9,"people_facing":0.9,"degree_required":0.9,"license_required":0.8}',
  '{"wlb":"공항 업무로 교대 근무 가능","growth":"귀빈 의전으로 전문성 향상 기회 있음","stability":"공항 업무로 매우 안정적","income":"전문 의전 업무로 중상위 소득","teamwork":"관계 기관 협의로 협업 多","solo_deep":"접수, 안내로 독립 작업","analytical":"귀빈 대상자 확인으로 분석 요구","creative":"의전 절차로 일부 창의성","execution":"접수, 안내, 협의 실행 중심","people_facing":"귀빈 응대, 협의로 대면 업무 매우 多","degree_required":"전문대졸 정도 학력 요구","license_required":"특별 자격증 요구 없음"}'
)
ON CONFLICT(job_id) DO UPDATE SET
  job_name = excluded.job_name,
  tagger_version = excluded.tagger_version,
  status = excluded.status,
  wlb = excluded.wlb,
  growth = excluded.growth,
  stability = excluded.stability,
  income = excluded.income,
  teamwork = excluded.teamwork,
  solo_deep = excluded.solo_deep,
  analytical = excluded.analytical,
  creative = excluded.creative,
  execution = excluded.execution,
  people_facing = excluded.people_facing,
  work_hours = excluded.work_hours,
  shift_work = excluded.shift_work,
  travel = excluded.travel,
  remote_possible = excluded.remote_possible,
  degree_required = excluded.degree_required,
  license_required = excluded.license_required,
  experience_required = excluded.experience_required,
  _confidence = excluded._confidence,
  _field_confidence_json = excluded._field_confidence_json,
  evidence_json = excluded.evidence_json,
  updated_at = CURRENT_TIMESTAMP;


INSERT INTO job_attributes (
  job_id, job_name, source_system, tagger_version, status,
  wlb, growth, stability, income,
  teamwork, solo_deep, analytical, creative, execution, people_facing,
  work_hours, shift_work, travel, remote_possible,
  degree_required, license_required, experience_required,
  _confidence, _field_confidence_json, evidence_json
) VALUES (
  '1765284422903267',
  '방문안내원',
  'WORK24_DJOB',
  'tagger-v1.0.0',
  'tagged',
  70, 35, 75, 35,
  60, 40, 45, 30, 75, 90,
  'regular', 'none', 'none', 'none',
  'none', 'none', 'entry',
  0.88,
  '{"wlb":0.8,"growth":0.5,"stability":0.85,"income":0.5,"teamwork":0.7,"solo_deep":0.6,"analytical":0.6,"creative":0.5,"execution":0.8,"people_facing":0.95,"degree_required":0.95,"license_required":0.9}',
  '{"wlb":"실내 사무직으로 정규 근무","growth":"안내 업무로 성장 기회 제한적","stability":"산업체 업무로 안정적","income":"안내 업무로 중간 수준 소득","teamwork":"안내, 통제 업무로 협업 필요","solo_deep":"출입 통제, 안내로 독립 작업","analytical":"방문자 확인으로 일부 분석","creative":"응대 방법으로 일부 창의성","execution":"안내, 통제 실행 중심","people_facing":"방문객 응대, 설명으로 대면 업무 매우 多","degree_required":"고졸 정도 학력 요구","license_required":"특별 자격증 요구 없음"}'
)
ON CONFLICT(job_id) DO UPDATE SET
  job_name = excluded.job_name,
  tagger_version = excluded.tagger_version,
  status = excluded.status,
  wlb = excluded.wlb,
  growth = excluded.growth,
  stability = excluded.stability,
  income = excluded.income,
  teamwork = excluded.teamwork,
  solo_deep = excluded.solo_deep,
  analytical = excluded.analytical,
  creative = excluded.creative,
  execution = excluded.execution,
  people_facing = excluded.people_facing,
  work_hours = excluded.work_hours,
  shift_work = excluded.shift_work,
  travel = excluded.travel,
  remote_possible = excluded.remote_possible,
  degree_required = excluded.degree_required,
  license_required = excluded.license_required,
  experience_required = excluded.experience_required,
  _confidence = excluded._confidence,
  _field_confidence_json = excluded._field_confidence_json,
  evidence_json = excluded.evidence_json,
  updated_at = CURRENT_TIMESTAMP;


INSERT INTO job_attributes (
  job_id, job_name, source_system, tagger_version, status,
  wlb, growth, stability, income,
  teamwork, solo_deep, analytical, creative, execution, people_facing,
  work_hours, shift_work, travel, remote_possible,
  degree_required, license_required, experience_required,
  _confidence, _field_confidence_json, evidence_json
) VALUES (
  '1765284423268715',
  '방송국견학안내원',
  'WORK24_DJOB',
  'tagger-v1.0.0',
  'tagged',
  70, 40, 75, 40,
  60, 40, 50, 45, 75, 85,
  'regular', 'none', 'none', 'none',
  'none', 'none', 'entry',
  0.85,
  '{"wlb":0.8,"growth":0.6,"stability":0.85,"income":0.6,"teamwork":0.7,"solo_deep":0.6,"analytical":0.6,"creative":0.7,"execution":0.8,"people_facing":0.9,"degree_required":0.95,"license_required":0.9}',
  '{"wlb":"실내 사무직으로 정규 근무","growth":"방송국 안내로 미디어 이해 기회 있음","stability":"방송국 업무로 안정적","income":"안내 업무로 중간 수준 소득","teamwork":"견학 안내로 협업 필요","solo_deep":"시설 설명으로 독립 작업","analytical":"시설, 과정 이해로 분석 요구","creative":"설명 방식으로 창의성 요구","execution":"안내, 설명 실행 중심","people_facing":"견학단 안내, 설명으로 대면 업무 매우 多","degree_required":"고졸 정도 학력 요구","license_required":"특별 자격증 요구 없음"}'
)
ON CONFLICT(job_id) DO UPDATE SET
  job_name = excluded.job_name,
  tagger_version = excluded.tagger_version,
  status = excluded.status,
  wlb = excluded.wlb,
  growth = excluded.growth,
  stability = excluded.stability,
  income = excluded.income,
  teamwork = excluded.teamwork,
  solo_deep = excluded.solo_deep,
  analytical = excluded.analytical,
  creative = excluded.creative,
  execution = excluded.execution,
  people_facing = excluded.people_facing,
  work_hours = excluded.work_hours,
  shift_work = excluded.shift_work,
  travel = excluded.travel,
  remote_possible = excluded.remote_possible,
  degree_required = excluded.degree_required,
  license_required = excluded.license_required,
  experience_required = excluded.experience_required,
  _confidence = excluded._confidence,
  _field_confidence_json = excluded._field_confidence_json,
  evidence_json = excluded.evidence_json,
  updated_at = CURRENT_TIMESTAMP;


INSERT INTO job_attributes (
  job_id, job_name, source_system, tagger_version, status,
  wlb, growth, stability, income,
  teamwork, solo_deep, analytical, creative, execution, people_facing,
  work_hours, shift_work, travel, remote_possible,
  degree_required, license_required, experience_required,
  _confidence, _field_confidence_json, evidence_json
) VALUES (
  '1765284423714772',
  '방송안내원',
  'WORK24_DJOB',
  'tagger-v1.0.0',
  'tagged',
  65, 35, 70, 35,
  55, 45, 45, 50, 80, 60,
  'regular', 'possible', 'none', 'none',
  'none', 'none', 'entry',
  0.86,
  '{"wlb":0.8,"growth":0.5,"stability":0.8,"income":0.5,"teamwork":0.6,"solo_deep":0.7,"analytical":0.6,"creative":0.7,"execution":0.9,"people_facing":0.7,"degree_required":0.95,"license_required":0.9}',
  '{"wlb":"공공장소 업무로 교대 근무 가능","growth":"방송 안내로 성장 기회 제한적","stability":"공공 업무로 비교적 안정적","income":"안내 업무로 중간 수준 소득","teamwork":"안내방송으로 협업 적음","solo_deep":"방송 준비, 송출로 독립 작업 多","analytical":"안내 내용 준비로 일부 분석","creative":"안내 내용 구성으로 창의성 요구","execution":"안내방송 송출 실행 중심","people_facing":"긴급 방송으로 대면 업무 적음","degree_required":"고졸 정도 학력 요구","license_required":"특별 자격증 요구 없음"}'
)
ON CONFLICT(job_id) DO UPDATE SET
  job_name = excluded.job_name,
  tagger_version = excluded.tagger_version,
  status = excluded.status,
  wlb = excluded.wlb,
  growth = excluded.growth,
  stability = excluded.stability,
  income = excluded.income,
  teamwork = excluded.teamwork,
  solo_deep = excluded.solo_deep,
  analytical = excluded.analytical,
  creative = excluded.creative,
  execution = excluded.execution,
  people_facing = excluded.people_facing,
  work_hours = excluded.work_hours,
  shift_work = excluded.shift_work,
  travel = excluded.travel,
  remote_possible = excluded.remote_possible,
  degree_required = excluded.degree_required,
  license_required = excluded.license_required,
  experience_required = excluded.experience_required,
  _confidence = excluded._confidence,
  _field_confidence_json = excluded._field_confidence_json,
  evidence_json = excluded.evidence_json,
  updated_at = CURRENT_TIMESTAMP;


INSERT INTO job_attributes (
  job_id, job_name, source_system, tagger_version, status,
  wlb, growth, stability, income,
  teamwork, solo_deep, analytical, creative, execution, people_facing,
  work_hours, shift_work, travel, remote_possible,
  degree_required, license_required, experience_required,
  _confidence, _field_confidence_json, evidence_json
) VALUES (
  '1765284424070438',
  '산업체안내원',
  'WORK24_DJOB',
  'tagger-v1.0.0',
  'tagged',
  70, 40, 80, 40,
  60, 40, 50, 45, 75, 85,
  'regular', 'none', 'none', 'none',
  'none', 'none', 'entry',
  0.84,
  '{"wlb":0.8,"growth":0.6,"stability":0.9,"income":0.6,"teamwork":0.7,"solo_deep":0.6,"analytical":0.6,"creative":0.7,"execution":0.8,"people_facing":0.9,"degree_required":0.95,"license_required":0.9}',
  '{"wlb":"실내외 사무직으로 정규 근무","growth":"산업체 안내로 이해도 향상 기회 있음","stability":"제조업 업무로 안정적","income":"안내 업무로 중간 수준 소득","teamwork":"안내 업무로 협업 필요","solo_deep":"시설 설명으로 독립 작업","analytical":"생산 과정 이해로 분석 요구","creative":"설명 방식으로 창의성 요구","execution":"안내, 설명 실행 중심","people_facing":"방문객 안내, 설명으로 대면 업무 매우 多","degree_required":"고졸 정도 학력 요구","license_required":"특별 자격증 요구 없음"}'
)
ON CONFLICT(job_id) DO UPDATE SET
  job_name = excluded.job_name,
  tagger_version = excluded.tagger_version,
  status = excluded.status,
  wlb = excluded.wlb,
  growth = excluded.growth,
  stability = excluded.stability,
  income = excluded.income,
  teamwork = excluded.teamwork,
  solo_deep = excluded.solo_deep,
  analytical = excluded.analytical,
  creative = excluded.creative,
  execution = excluded.execution,
  people_facing = excluded.people_facing,
  work_hours = excluded.work_hours,
  shift_work = excluded.shift_work,
  travel = excluded.travel,
  remote_possible = excluded.remote_possible,
  degree_required = excluded.degree_required,
  license_required = excluded.license_required,
  experience_required = excluded.experience_required,
  _confidence = excluded._confidence,
  _field_confidence_json = excluded._field_confidence_json,
  evidence_json = excluded.evidence_json,
  updated_at = CURRENT_TIMESTAMP;


INSERT INTO job_attributes (
  job_id, job_name, source_system, tagger_version, status,
  wlb, growth, stability, income,
  teamwork, solo_deep, analytical, creative, execution, people_facing,
  work_hours, shift_work, travel, remote_possible,
  degree_required, license_required, experience_required,
  _confidence, _field_confidence_json, evidence_json
) VALUES (
  '1765284424402519',
  '숙박업소전화교환원',
  'WORK24_DJOB',
  'tagger-v1.0.0',
  'tagged',
  60, 30, 75, 35,
  70, 30, 40, 25, 80, 85,
  'regular', 'required', 'none', 'none',
  'none', 'none', 'entry',
  0.87,
  '{"wlb":0.7,"growth":0.4,"stability":0.85,"income":0.5,"teamwork":0.8,"solo_deep":0.5,"analytical":0.5,"creative":0.4,"execution":0.9,"people_facing":0.9,"degree_required":0.95,"license_required":0.9}',
  '{"wlb":"숙박업소 업무로 교대 근무 필수","growth":"전화 교환 업무로 성장 기회 매우 제한적","stability":"숙박업 업무로 안정적","income":"교환 업무로 중간 수준 소득","teamwork":"고객 응대로 협업 필요","solo_deep":"전화 연결로 독립 작업","analytical":"요청 파악으로 일부 분석","creative":"표준화된 업무로 창의성 낮음","execution":"전화 연결, 모닝콜 실행 중심","people_facing":"고객 불만 응대, 서비스 지원으로 대면 업무 매우 多","degree_required":"고졸 정도 학력 요구","license_required":"특별 자격증 요구 없음"}'
)
ON CONFLICT(job_id) DO UPDATE SET
  job_name = excluded.job_name,
  tagger_version = excluded.tagger_version,
  status = excluded.status,
  wlb = excluded.wlb,
  growth = excluded.growth,
  stability = excluded.stability,
  income = excluded.income,
  teamwork = excluded.teamwork,
  solo_deep = excluded.solo_deep,
  analytical = excluded.analytical,
  creative = excluded.creative,
  execution = excluded.execution,
  people_facing = excluded.people_facing,
  work_hours = excluded.work_hours,
  shift_work = excluded.shift_work,
  travel = excluded.travel,
  remote_possible = excluded.remote_possible,
  degree_required = excluded.degree_required,
  license_required = excluded.license_required,
  experience_required = excluded.experience_required,
  _confidence = excluded._confidence,
  _field_confidence_json = excluded._field_confidence_json,
  evidence_json = excluded.evidence_json,
  updated_at = CURRENT_TIMESTAMP;


INSERT INTO job_attributes (
  job_id, job_name, source_system, tagger_version, status,
  wlb, growth, stability, income,
  teamwork, solo_deep, analytical, creative, execution, people_facing,
  work_hours, shift_work, travel, remote_possible,
  degree_required, license_required, experience_required,
  _confidence, _field_confidence_json, evidence_json
) VALUES (
  '1765284424749972',
  '예약접수원',
  'WORK24_DJOB',
  'tagger-v1.0.0',
  'tagged',
  70, 35, 70, 35,
  65, 35, 50, 30, 80, 80,
  'regular', 'none', 'none', 'partial',
  'none', 'none', 'entry',
  0.89,
  '{"wlb":0.8,"growth":0.5,"stability":0.8,"income":0.5,"teamwork":0.8,"solo_deep":0.5,"analytical":0.6,"creative":0.5,"execution":0.9,"people_facing":0.9,"degree_required":0.95,"license_required":0.9}',
  '{"wlb":"실내 사무직으로 정규 근무","growth":"예약 업무로 성장 기회 제한적","stability":"여행사 업무로 비교적 안정적","income":"접수 업무로 중간 수준 소득","teamwork":"예약 관리로 협업 필요","solo_deep":"시스템 입력으로 독립 작업","analytical":"예약 상황 확인으로 분석 요구","creative":"응대 방식으로 일부 창의성","execution":"접수, 입력 실행 중심","people_facing":"고객 안내, 문의 응대로 대면 업무 매우 多","degree_required":"고졸 정도 학력 요구","license_required":"특별 자격증 요구 없음"}'
)
ON CONFLICT(job_id) DO UPDATE SET
  job_name = excluded.job_name,
  tagger_version = excluded.tagger_version,
  status = excluded.status,
  wlb = excluded.wlb,
  growth = excluded.growth,
  stability = excluded.stability,
  income = excluded.income,
  teamwork = excluded.teamwork,
  solo_deep = excluded.solo_deep,
  analytical = excluded.analytical,
  creative = excluded.creative,
  execution = excluded.execution,
  people_facing = excluded.people_facing,
  work_hours = excluded.work_hours,
  shift_work = excluded.shift_work,
  travel = excluded.travel,
  remote_possible = excluded.remote_possible,
  degree_required = excluded.degree_required,
  license_required = excluded.license_required,
  experience_required = excluded.experience_required,
  _confidence = excluded._confidence,
  _field_confidence_json = excluded._field_confidence_json,
  evidence_json = excluded.evidence_json,
  updated_at = CURRENT_TIMESTAMP;


INSERT INTO job_attributes (
  job_id, job_name, source_system, tagger_version, status,
  wlb, growth, stability, income,
  teamwork, solo_deep, analytical, creative, execution, people_facing,
  work_hours, shift_work, travel, remote_possible,
  degree_required, license_required, experience_required,
  _confidence, _field_confidence_json, evidence_json
) VALUES (
  '1765284425055890',
  '입국안내원',
  'WORK24_DJOB',
  'tagger-v1.0.0',
  'tagged',
  65, 45, 85, 45,
  70, 30, 55, 35, 80, 95,
  'regular', 'possible', 'none', 'none',
  'college', 'none', 'entry',
  0.83,
  '{"wlb":0.8,"growth":0.6,"stability":0.95,"income":0.6,"teamwork":0.8,"solo_deep":0.5,"analytical":0.7,"creative":0.5,"execution":0.9,"people_facing":0.98,"degree_required":0.9,"license_required":0.8}',
  '{"wlb":"공항 업무로 교대 근무 가능","growth":"공항 안내로 언어 능력 향상 기회 있음","stability":"공항 업무로 매우 안정적","income":"전문 안내 업무로 중상위 소득","teamwork":"안내 데스크로 협업 필요","solo_deep":"안내 제공으로 독립 작업","analytical":"절차, 시설 이해로 분석 요구","creative":"안내 방식으로 일부 창의성","execution":"안내, 방송 실행 중심","people_facing":"내외국인 고객 안내로 대면 업무 매우 多","degree_required":"전문대졸 정도 학력 요구","license_required":"특별 자격증 요구 없음"}'
)
ON CONFLICT(job_id) DO UPDATE SET
  job_name = excluded.job_name,
  tagger_version = excluded.tagger_version,
  status = excluded.status,
  wlb = excluded.wlb,
  growth = excluded.growth,
  stability = excluded.stability,
  income = excluded.income,
  teamwork = excluded.teamwork,
  solo_deep = excluded.solo_deep,
  analytical = excluded.analytical,
  creative = excluded.creative,
  execution = excluded.execution,
  people_facing = excluded.people_facing,
  work_hours = excluded.work_hours,
  shift_work = excluded.shift_work,
  travel = excluded.travel,
  remote_possible = excluded.remote_possible,
  degree_required = excluded.degree_required,
  license_required = excluded.license_required,
  experience_required = excluded.experience_required,
  _confidence = excluded._confidence,
  _field_confidence_json = excluded._field_confidence_json,
  evidence_json = excluded.evidence_json,
  updated_at = CURRENT_TIMESTAMP;


INSERT INTO job_attributes (
  job_id, job_name, source_system, tagger_version, status,
  wlb, growth, stability, income,
  teamwork, solo_deep, analytical, creative, execution, people_facing,
  work_hours, shift_work, travel, remote_possible,
  degree_required, license_required, experience_required,
  _confidence, _field_confidence_json, evidence_json
) VALUES (
  '1765284425334380',
  '전화번호안내원',
  'WORK24_DJOB',
  'tagger-v1.0.0',
  'tagged',
  60, 25, 80, 35,
  50, 50, 35, 20, 85, 70,
  'regular', 'required', 'none', 'none',
  'none', 'none', 'entry',
  0.91,
  '{"wlb":0.7,"growth":0.3,"stability":0.9,"income":0.5,"teamwork":0.6,"solo_deep":0.7,"analytical":0.5,"creative":0.3,"execution":0.95,"people_facing":0.8,"degree_required":0.95,"license_required":0.9}',
  '{"wlb":"콜센터 업무로 교대 근무 필수","growth":"안내 업무로 성장 기회 매우 제한적","stability":"통신사 업무로 안정적","income":"안내 업무로 중간 수준 소득","teamwork":"안내 업무로 협업 적음","solo_deep":"번호 검색, 안내로 독립 작업 多","analytical":"문의 파악으로 최소 분석","creative":"표준화된 업무로 창의성 낮음","execution":"번호 검색, 안내 실행 중심","people_facing":"전화 응대로 대면 업무 多","degree_required":"고졸 정도 학력 요구","license_required":"특별 자격증 요구 없음"}'
)
ON CONFLICT(job_id) DO UPDATE SET
  job_name = excluded.job_name,
  tagger_version = excluded.tagger_version,
  status = excluded.status,
  wlb = excluded.wlb,
  growth = excluded.growth,
  stability = excluded.stability,
  income = excluded.income,
  teamwork = excluded.teamwork,
  solo_deep = excluded.solo_deep,
  analytical = excluded.analytical,
  creative = excluded.creative,
  execution = excluded.execution,
  people_facing = excluded.people_facing,
  work_hours = excluded.work_hours,
  shift_work = excluded.shift_work,
  travel = excluded.travel,
  remote_possible = excluded.remote_possible,
  degree_required = excluded.degree_required,
  license_required = excluded.license_required,
  experience_required = excluded.experience_required,
  _confidence = excluded._confidence,
  _field_confidence_json = excluded._field_confidence_json,
  evidence_json = excluded.evidence_json,
  updated_at = CURRENT_TIMESTAMP;


INSERT INTO job_attributes (
  job_id, job_name, source_system, tagger_version, status,
  wlb, growth, stability, income,
  teamwork, solo_deep, analytical, creative, execution, people_facing,
  work_hours, shift_work, travel, remote_possible,
  degree_required, license_required, experience_required,
  _confidence, _field_confidence_json, evidence_json
) VALUES (
  '1765284425638676',
  '진료접수계원',
  'WORK24_DJOB',
  'tagger-v1.0.0',
  'tagged',
  70, 40, 85, 40,
  70, 30, 50, 25, 80, 90,
  'regular', 'none', 'none', 'none',
  'none', 'none', 'entry',
  0.86,
  '{"wlb":0.8,"growth":0.6,"stability":0.95,"income":0.6,"teamwork":0.8,"solo_deep":0.5,"analytical":0.6,"creative":0.4,"execution":0.9,"people_facing":0.95,"degree_required":0.95,"license_required":0.9}',
  '{"wlb":"병원 업무로 정규 근무","growth":"진료 접수로 의료 이해 기회 있음","stability":"병원 업무로 매우 안정적","income":"접수 업무로 중간 수준 소득","teamwork":"접수 창구로 협업 필요","solo_deep":"기록 정리로 독립 작업","analytical":"환자 정보 확인으로 분석 요구","creative":"표준화된 업무로 창의성 낮음","execution":"접수, 안내, 처방전 발급 실행 중심","people_facing":"환자 접대, 안내로 대면 업무 매우 多","degree_required":"고졸 정도 학력 요구","license_required":"특별 자격증 요구 없음"}'
)
ON CONFLICT(job_id) DO UPDATE SET
  job_name = excluded.job_name,
  tagger_version = excluded.tagger_version,
  status = excluded.status,
  wlb = excluded.wlb,
  growth = excluded.growth,
  stability = excluded.stability,
  income = excluded.income,
  teamwork = excluded.teamwork,
  solo_deep = excluded.solo_deep,
  analytical = excluded.analytical,
  creative = excluded.creative,
  execution = excluded.execution,
  people_facing = excluded.people_facing,
  work_hours = excluded.work_hours,
  shift_work = excluded.shift_work,
  travel = excluded.travel,
  remote_possible = excluded.remote_possible,
  degree_required = excluded.degree_required,
  license_required = excluded.license_required,
  experience_required = excluded.experience_required,
  _confidence = excluded._confidence,
  _field_confidence_json = excluded._field_confidence_json,
  evidence_json = excluded.evidence_json,
  updated_at = CURRENT_TIMESTAMP;


INSERT INTO job_attributes (
  job_id, job_name, source_system, tagger_version, status,
  wlb, growth, stability, income,
  teamwork, solo_deep, analytical, creative, execution, people_facing,
  work_hours, shift_work, travel, remote_possible,
  degree_required, license_required, experience_required,
  _confidence, _field_confidence_json, evidence_json
) VALUES (
  '1765284425992914',
  '항공기탑승안내원',
  'WORK24_DJOB',
  'tagger-v1.0.0',
  'tagged',
  55, 45, 80, 45,
  75, 25, 55, 30, 85, 90,
  'regular', 'required', 'none', 'none',
  'college', 'none', 'entry',
  0.84,
  '{"wlb":0.6,"growth":0.6,"stability":0.9,"income":0.6,"teamwork":0.8,"solo_deep":0.4,"analytical":0.7,"creative":0.5,"execution":0.95,"people_facing":0.95,"degree_required":0.9,"license_required":0.8}',
  '{"wlb":"공항 업무로 교대 근무 필수","growth":"항공기 탑승 안내로 전문성 향상 기회 있음","stability":"항공사 업무로 안정적","income":"전문 안내 업무로 중상위 소득","teamwork":"게이트 안내로 협업 多","solo_deep":"안내 업무로 독립 작업","analytical":"탑승 정보 확인으로 분석 요구","creative":"긴급 상황 대응으로 일부 창의성","execution":"안내, 확인 실행 중심","people_facing":"승객 안내, 응대로 대면 업무 매우 多","degree_required":"전문대졸 정도 학력 요구","license_required":"특별 자격증 요구 없음"}'
)
ON CONFLICT(job_id) DO UPDATE SET
  job_name = excluded.job_name,
  tagger_version = excluded.tagger_version,
  status = excluded.status,
  wlb = excluded.wlb,
  growth = excluded.growth,
  stability = excluded.stability,
  income = excluded.income,
  teamwork = excluded.teamwork,
  solo_deep = excluded.solo_deep,
  analytical = excluded.analytical,
  creative = excluded.creative,
  execution = excluded.execution,
  people_facing = excluded.people_facing,
  work_hours = excluded.work_hours,
  shift_work = excluded.shift_work,
  travel = excluded.travel,
  remote_possible = excluded.remote_possible,
  degree_required = excluded.degree_required,
  license_required = excluded.license_required,
  experience_required = excluded.experience_required,
  _confidence = excluded._confidence,
  _field_confidence_json = excluded._field_confidence_json,
  evidence_json = excluded.evidence_json,
  updated_at = CURRENT_TIMESTAMP;

COMMIT;