-- Batch tagging SQL generated at 2026-01-06T09:55:03.663Z
-- Tagger version: tagger-v1.0.0
-- Total jobs: 18

BEGIN TRANSACTION;


INSERT INTO job_attributes (
  job_id, job_name, source_system, tagger_version, status,
  wlb, growth, stability, income,
  teamwork, solo_deep, analytical, creative, execution, people_facing,
  work_hours, shift_work, travel, remote_possible,
  degree_required, license_required, experience_required,
  _confidence, _field_confidence_json, evidence_json
) VALUES (
  '1765284785785268',
  '단청기술자',
  'WORK24_DJOB',
  'tagger-v1.0.0',
  'tagged',
  70, 65, 85, 70,
  80, 45, 80, 85, 75, 75,
  'regular', 'none', 'frequent', 'none',
  'none', 'required', 'none',
  0.78,
  '{"wlb":0.75,"growth":0.8,"stability":0.95,"income":0.85,"teamwork":0.9,"solo_deep":0.6,"analytical":0.9,"creative":0.95,"execution":0.85,"people_facing":0.9,"degree_required":0.9,"license_required":0.95}',
  '{"wlb":"야외 단청 작업으로 야근 적고 교대 근무 없음","growth":"전통 문화재 분야 기술 발전 기회 좋음","stability":"문화재 분야로 고용 안정성 매우 높음","income":"전문 단청 기술자로 상위 소득","teamwork":"단청편수 관리, 감독 업무로 협업 매우 중요","solo_deep":"현장 조사, 도안 작성 작업으로 독립 작업 多","analytical":"고증 자료 분석, 문양 모사로 분석 매우 중요","creative":"문양 복원, 색채 디자인으로 창의성 매우 높음","execution":"단청 시공 총괄, 감독 실행 중심","people_facing":"단청편수 지시, 감독원 입회 업무 매우 多","degree_required":"고졸 정도 학력 요구","license_required":"단청기술자 자격증 필수"}'
)
ON CONFLICT(job_id) DO UPDATE SET
  job_name = excluded.job_name,
  tagger_version = excluded.tagger_version,
  status = excluded.status,
  wlb = excluded.wlb,
  growth = excluded.growth,
  stability = excluded.stability,
  income = excluded.income,
  teamwork = excluded.teamwork,
  solo_deep = excluded.solo_deep,
  analytical = excluded.analytical,
  creative = excluded.creative,
  execution = excluded.execution,
  people_facing = excluded.people_facing,
  work_hours = excluded.work_hours,
  shift_work = excluded.shift_work,
  travel = excluded.travel,
  remote_possible = excluded.remote_possible,
  degree_required = excluded.degree_required,
  license_required = excluded.license_required,
  experience_required = excluded.experience_required,
  _confidence = excluded._confidence,
  _field_confidence_json = excluded._field_confidence_json,
  evidence_json = excluded.evidence_json,
  updated_at = CURRENT_TIMESTAMP;


INSERT INTO job_attributes (
  job_id, job_name, source_system, tagger_version, status,
  wlb, growth, stability, income,
  teamwork, solo_deep, analytical, creative, execution, people_facing,
  work_hours, shift_work, travel, remote_possible,
  degree_required, license_required, experience_required,
  _confidence, _field_confidence_json, evidence_json
) VALUES (
  '1765284786139305',
  '단청편수',
  'WORK24_DJOB',
  'tagger-v1.0.0',
  'tagged',
  70, 65, 85, 70,
  85, 35, 75, 75, 75, 80,
  'regular', 'none', 'frequent', 'none',
  'none', 'required', 'none',
  0.77,
  '{"wlb":0.75,"growth":0.8,"stability":0.95,"income":0.85,"teamwork":0.95,"solo_deep":0.5,"analytical":0.85,"creative":0.9,"execution":0.85,"people_facing":0.95,"degree_required":0.9,"license_required":0.95}',
  '{"wlb":"야외 단청 작업으로 야근 적고 교대 근무 없음","growth":"전통 문화재 분야 기술 발전 기회 좋음","stability":"문화재 분야로 고용 안정성 매우 높음","income":"전문 단청 편수로 상위 소득","teamwork":"화공 시공 총지휘, 감독 업무로 협업 매우 중요","solo_deep":"시공 순서 파악 작업으로 독립 작업","analytical":"시공 순서 결정, 기술적 지원으로 분석 중심","creative":"시공 진행 조정으로 창의성 요구","execution":"시공 과정 감독 실행 중심","people_facing":"화공 지시, 기술자 협의 업무 매우 多","degree_required":"고졸 정도 학력 요구","license_required":"단청편수 자격증 필수"}'
)
ON CONFLICT(job_id) DO UPDATE SET
  job_name = excluded.job_name,
  tagger_version = excluded.tagger_version,
  status = excluded.status,
  wlb = excluded.wlb,
  growth = excluded.growth,
  stability = excluded.stability,
  income = excluded.income,
  teamwork = excluded.teamwork,
  solo_deep = excluded.solo_deep,
  analytical = excluded.analytical,
  creative = excluded.creative,
  execution = excluded.execution,
  people_facing = excluded.people_facing,
  work_hours = excluded.work_hours,
  shift_work = excluded.shift_work,
  travel = excluded.travel,
  remote_possible = excluded.remote_possible,
  degree_required = excluded.degree_required,
  license_required = excluded.license_required,
  experience_required = excluded.experience_required,
  _confidence = excluded._confidence,
  _field_confidence_json = excluded._field_confidence_json,
  evidence_json = excluded.evidence_json,
  updated_at = CURRENT_TIMESTAMP;


INSERT INTO job_attributes (
  job_id, job_name, source_system, tagger_version, status,
  wlb, growth, stability, income,
  teamwork, solo_deep, analytical, creative, execution, people_facing,
  work_hours, shift_work, travel, remote_possible,
  degree_required, license_required, experience_required,
  _confidence, _field_confidence_json, evidence_json
) VALUES (
  '1765284786563300',
  '도자기검사원',
  'WORK24_DJOB',
  'tagger-v1.0.0',
  'tagged',
  75, 55, 75, 60,
  75, 40, 75, 55, 75, 65,
  'regular', 'required', 'none', 'none',
  'none', 'none', 'none',
  0.74,
  '{"wlb":0.8,"growth":0.7,"stability":0.85,"income":0.75,"teamwork":0.85,"solo_deep":0.55,"analytical":0.85,"creative":0.7,"execution":0.85,"people_facing":0.8,"degree_required":0.9,"license_required":0.9}',
  '{"wlb":"일반 사무 환경으로 야근 적고 교대 근무 필수","growth":"도자기 산업 기술 발전 기회 보통","stability":"제조업으로 고용 안정성 좋음","income":"전문 검사로 중위 소득","teamwork":"검사 작업 협업 요구","solo_deep":"완성품 검사, 불량 선별 작업으로 독립 작업","analytical":"색채, 표면, 균열 검사로 분석 중심","creative":"검사 방법 개선으로 창의성 요구","execution":"불량품 선별, 기록 실행 중심","people_facing":"작업 점검 업무","degree_required":"중졸 정도 학력 요구","license_required":"특별 자격증 불필요"}'
)
ON CONFLICT(job_id) DO UPDATE SET
  job_name = excluded.job_name,
  tagger_version = excluded.tagger_version,
  status = excluded.status,
  wlb = excluded.wlb,
  growth = excluded.growth,
  stability = excluded.stability,
  income = excluded.income,
  teamwork = excluded.teamwork,
  solo_deep = excluded.solo_deep,
  analytical = excluded.analytical,
  creative = excluded.creative,
  execution = excluded.execution,
  people_facing = excluded.people_facing,
  work_hours = excluded.work_hours,
  shift_work = excluded.shift_work,
  travel = excluded.travel,
  remote_possible = excluded.remote_possible,
  degree_required = excluded.degree_required,
  license_required = excluded.license_required,
  experience_required = excluded.experience_required,
  _confidence = excluded._confidence,
  _field_confidence_json = excluded._field_confidence_json,
  evidence_json = excluded.evidence_json,
  updated_at = CURRENT_TIMESTAMP;


INSERT INTO job_attributes (
  job_id, job_name, source_system, tagger_version, status,
  wlb, growth, stability, income,
  teamwork, solo_deep, analytical, creative, execution, people_facing,
  work_hours, shift_work, travel, remote_possible,
  degree_required, license_required, experience_required,
  _confidence, _field_confidence_json, evidence_json
) VALUES (
  '1765284786933710',
  '도자기인쇄원',
  'WORK24_DJOB',
  'tagger-v1.0.0',
  'tagged',
  75, 55, 75, 65,
  75, 40, 70, 70, 75, 65,
  'regular', 'none', 'none', 'none',
  'none', 'none', 'none',
  0.75,
  '{"wlb":0.8,"growth":0.7,"stability":0.85,"income":0.8,"teamwork":0.85,"solo_deep":0.55,"analytical":0.8,"creative":0.85,"execution":0.85,"people_facing":0.8,"degree_required":0.9,"license_required":0.9}',
  '{"wlb":"일반 사무 환경으로 야근 적고 교대 근무 없음","growth":"도자기 인쇄 산업 기술 발전 기회 보통","stability":"제조업으로 고용 안정성 좋음","income":"전문 인쇄로 중위 소득","teamwork":"인쇄 작업 협업 요구","solo_deep":"도안 확인, 기계 조작 작업으로 독립 작업","analytical":"도안 비교, 압력 조정으로 분석 중심","creative":"도안 디자인, 잉크 배합으로 창의성 요구","execution":"기계 조작, 인쇄 실행 중심","people_facing":"작업 점검 업무","degree_required":"고졸 정도 학력 요구","license_required":"특별 자격증 불필요"}'
)
ON CONFLICT(job_id) DO UPDATE SET
  job_name = excluded.job_name,
  tagger_version = excluded.tagger_version,
  status = excluded.status,
  wlb = excluded.wlb,
  growth = excluded.growth,
  stability = excluded.stability,
  income = excluded.income,
  teamwork = excluded.teamwork,
  solo_deep = excluded.solo_deep,
  analytical = excluded.analytical,
  creative = excluded.creative,
  execution = excluded.execution,
  people_facing = excluded.people_facing,
  work_hours = excluded.work_hours,
  shift_work = excluded.shift_work,
  travel = excluded.travel,
  remote_possible = excluded.remote_possible,
  degree_required = excluded.degree_required,
  license_required = excluded.license_required,
  experience_required = excluded.experience_required,
  _confidence = excluded._confidence,
  _field_confidence_json = excluded._field_confidence_json,
  evidence_json = excluded.evidence_json,
  updated_at = CURRENT_TIMESTAMP;


INSERT INTO job_attributes (
  job_id, job_name, source_system, tagger_version, status,
  wlb, growth, stability, income,
  teamwork, solo_deep, analytical, creative, execution, people_facing,
  work_hours, shift_work, travel, remote_possible,
  degree_required, license_required, experience_required,
  _confidence, _field_confidence_json, evidence_json
) VALUES (
  '1765284787239882',
  '도자기장식원',
  'WORK24_DJOB',
  'tagger-v1.0.0',
  'tagged',
  75, 60, 75, 65,
  75, 45, 70, 80, 75, 70,
  'regular', 'none', 'none', 'none',
  'none', 'none', 'none',
  0.76,
  '{"wlb":0.8,"growth":0.75,"stability":0.85,"income":0.8,"teamwork":0.85,"solo_deep":0.6,"analytical":0.8,"creative":0.9,"execution":0.85,"people_facing":0.85,"degree_required":0.9,"license_required":0.9}',
  '{"wlb":"일반 사무 환경으로 야근 적고 교대 근무 없음","growth":"도자기 장식 산업 기술 발전 기회 좋음","stability":"제조업으로 고용 안정성 좋음","income":"전문 장식으로 중위 소득","teamwork":"장식 작업 협업 요구","solo_deep":"도안 확인, 붓 사용 작업으로 독립 작업 多","analytical":"도안 비교, 색상 확인으로 분석 중심","creative":"그림 그리기, 색칠 디자인으로 창의성 높음","execution":"붓 사용, 그림 그리기 실행 중심","people_facing":"작업 인계 업무 매우 多","degree_required":"중졸 정도 학력 요구","license_required":"특별 자격증 불필요"}'
)
ON CONFLICT(job_id) DO UPDATE SET
  job_name = excluded.job_name,
  tagger_version = excluded.tagger_version,
  status = excluded.status,
  wlb = excluded.wlb,
  growth = excluded.growth,
  stability = excluded.stability,
  income = excluded.income,
  teamwork = excluded.teamwork,
  solo_deep = excluded.solo_deep,
  analytical = excluded.analytical,
  creative = excluded.creative,
  execution = excluded.execution,
  people_facing = excluded.people_facing,
  work_hours = excluded.work_hours,
  shift_work = excluded.shift_work,
  travel = excluded.travel,
  remote_possible = excluded.remote_possible,
  degree_required = excluded.degree_required,
  license_required = excluded.license_required,
  experience_required = excluded.experience_required,
  _confidence = excluded._confidence,
  _field_confidence_json = excluded._field_confidence_json,
  evidence_json = excluded.evidence_json,
  updated_at = CURRENT_TIMESTAMP;


INSERT INTO job_attributes (
  job_id, job_name, source_system, tagger_version, status,
  wlb, growth, stability, income,
  teamwork, solo_deep, analytical, creative, execution, people_facing,
  work_hours, shift_work, travel, remote_possible,
  degree_required, license_required, experience_required,
  _confidence, _field_confidence_json, evidence_json
) VALUES (
  '1765284787571151',
  '도자기조각원',
  'WORK24_DJOB',
  'tagger-v1.0.0',
  'tagged',
  75, 60, 75, 70,
  75, 45, 75, 85, 75, 65,
  'regular', 'none', 'none', 'none',
  'none', 'none', 'none',
  0.77,
  '{"wlb":0.8,"growth":0.75,"stability":0.85,"income":0.85,"teamwork":0.85,"solo_deep":0.6,"analytical":0.85,"creative":0.95,"execution":0.85,"people_facing":0.8,"degree_required":0.9,"license_required":0.9}',
  '{"wlb":"일반 사무 환경으로 야근 적고 교대 근무 없음","growth":"도자기 조각 산업 기술 발전 기회 좋음","stability":"제조업으로 고용 안정성 좋음","income":"전문 조각으로 상위 소득","teamwork":"조각 작업 협업 요구","solo_deep":"문양 확인, 조각칼 사용 작업으로 독립 작업 多","analytical":"문양 부위 확인, 형태 분석으로 분석 중심","creative":"자유로운 창작 문양으로 창의성 매우 높음","execution":"조각칼 사용, 다듬기 실행 중심","people_facing":"작업 점검 업무","degree_required":"중졸 정도 학력 요구","license_required":"특별 자격증 불필요"}'
)
ON CONFLICT(job_id) DO UPDATE SET
  job_name = excluded.job_name,
  tagger_version = excluded.tagger_version,
  status = excluded.status,
  wlb = excluded.wlb,
  growth = excluded.growth,
  stability = excluded.stability,
  income = excluded.income,
  teamwork = excluded.teamwork,
  solo_deep = excluded.solo_deep,
  analytical = excluded.analytical,
  creative = excluded.creative,
  execution = excluded.execution,
  people_facing = excluded.people_facing,
  work_hours = excluded.work_hours,
  shift_work = excluded.shift_work,
  travel = excluded.travel,
  remote_possible = excluded.remote_possible,
  degree_required = excluded.degree_required,
  license_required = excluded.license_required,
  experience_required = excluded.experience_required,
  _confidence = excluded._confidence,
  _field_confidence_json = excluded._field_confidence_json,
  evidence_json = excluded.evidence_json,
  updated_at = CURRENT_TIMESTAMP;


INSERT INTO job_attributes (
  job_id, job_name, source_system, tagger_version, status,
  wlb, growth, stability, income,
  teamwork, solo_deep, analytical, creative, execution, people_facing,
  work_hours, shift_work, travel, remote_possible,
  degree_required, license_required, experience_required,
  _confidence, _field_confidence_json, evidence_json
) VALUES (
  '1765284787825262',
  '도자기조립원',
  'WORK24_DJOB',
  'tagger-v1.0.0',
  'tagged',
  75, 55, 75, 65,
  80, 40, 70, 55, 80, 70,
  'regular', 'none', 'none', 'none',
  'none', 'none', 'none',
  0.74,
  '{"wlb":0.8,"growth":0.7,"stability":0.85,"income":0.8,"teamwork":0.9,"solo_deep":0.55,"analytical":0.8,"creative":0.7,"execution":0.9,"people_facing":0.85,"degree_required":0.9,"license_required":0.9}',
  '{"wlb":"일반 사무 환경으로 야근 적고 교대 근무 없음","growth":"도자기 조립 산업 기술 발전 기회 보통","stability":"제조업으로 고용 안정성 좋음","income":"전문 조립으로 중위 소득","teamwork":"조립 작업 협업 매우 중요","solo_deep":"부품 확인, 결합 작업으로 독립 작업","analytical":"조립 순서 확인, 규격 파악으로 분석 중심","creative":"조립 방법 개선으로 창의성 요구","execution":"부품 결합, 슬립 칠하기 실행 중심","people_facing":"작업 점검 업무 매우 多","degree_required":"중졸 정도 학력 요구","license_required":"특별 자격증 불필요"}'
)
ON CONFLICT(job_id) DO UPDATE SET
  job_name = excluded.job_name,
  tagger_version = excluded.tagger_version,
  status = excluded.status,
  wlb = excluded.wlb,
  growth = excluded.growth,
  stability = excluded.stability,
  income = excluded.income,
  teamwork = excluded.teamwork,
  solo_deep = excluded.solo_deep,
  analytical = excluded.analytical,
  creative = excluded.creative,
  execution = excluded.execution,
  people_facing = excluded.people_facing,
  work_hours = excluded.work_hours,
  shift_work = excluded.shift_work,
  travel = excluded.travel,
  remote_possible = excluded.remote_possible,
  degree_required = excluded.degree_required,
  license_required = excluded.license_required,
  experience_required = excluded.experience_required,
  _confidence = excluded._confidence,
  _field_confidence_json = excluded._field_confidence_json,
  evidence_json = excluded.evidence_json,
  updated_at = CURRENT_TIMESTAMP;


INSERT INTO job_attributes (
  job_id, job_name, source_system, tagger_version, status,
  wlb, growth, stability, income,
  teamwork, solo_deep, analytical, creative, execution, people_facing,
  work_hours, shift_work, travel, remote_possible,
  degree_required, license_required, experience_required,
  _confidence, _field_confidence_json, evidence_json
) VALUES (
  '1765284788100655',
  '돗자리제조원',
  'WORK24_DJOB',
  'tagger-v1.0.0',
  'tagged',
  75, 50, 75, 60,
  70, 45, 65, 70, 80, 65,
  'regular', 'none', 'none', 'none',
  'none', 'none', 'none',
  0.73,
  '{"wlb":0.8,"growth":0.65,"stability":0.85,"income":0.75,"teamwork":0.8,"solo_deep":0.6,"analytical":0.75,"creative":0.85,"execution":0.9,"people_facing":0.8,"degree_required":0.9,"license_required":0.9}',
  '{"wlb":"일반 사무 환경으로 야근 적고 교대 근무 없음","growth":"돗자리 제조 산업으로 성장 기회 제한적","stability":"제조업으로 고용 안정성 좋음","income":"전문 제조로 중위 소득","teamwork":"제조 작업 협업 요구","solo_deep":"완초 손질, 엮기 작업으로 독립 작업 多","analytical":"완초 품질 확인, 무늬 배치로 분석 중심","creative":"무늬 넣기, 디자인으로 창의성 높음","execution":"완초 엮기, 마무리 실행 중심","people_facing":"작업 점검 업무","degree_required":"고졸 정도 학력 요구","license_required":"특별 자격증 불필요"}'
)
ON CONFLICT(job_id) DO UPDATE SET
  job_name = excluded.job_name,
  tagger_version = excluded.tagger_version,
  status = excluded.status,
  wlb = excluded.wlb,
  growth = excluded.growth,
  stability = excluded.stability,
  income = excluded.income,
  teamwork = excluded.teamwork,
  solo_deep = excluded.solo_deep,
  analytical = excluded.analytical,
  creative = excluded.creative,
  execution = excluded.execution,
  people_facing = excluded.people_facing,
  work_hours = excluded.work_hours,
  shift_work = excluded.shift_work,
  travel = excluded.travel,
  remote_possible = excluded.remote_possible,
  degree_required = excluded.degree_required,
  license_required = excluded.license_required,
  experience_required = excluded.experience_required,
  _confidence = excluded._confidence,
  _field_confidence_json = excluded._field_confidence_json,
  evidence_json = excluded.evidence_json,
  updated_at = CURRENT_TIMESTAMP;


INSERT INTO job_attributes (
  job_id, job_name, source_system, tagger_version, status,
  wlb, growth, stability, income,
  teamwork, solo_deep, analytical, creative, execution, people_facing,
  work_hours, shift_work, travel, remote_possible,
  degree_required, license_required, experience_required,
  _confidence, _field_confidence_json, evidence_json
) VALUES (
  '1765284788386961',
  '모사공',
  'WORK24_DJOB',
  'tagger-v1.0.0',
  'tagged',
  75, 60, 80, 70,
  75, 50, 80, 85, 75, 75,
  'regular', 'none', 'none', 'none',
  'none', 'required', 'none',
  0.78,
  '{"wlb":0.8,"growth":0.75,"stability":0.9,"income":0.85,"teamwork":0.85,"solo_deep":0.65,"analytical":0.9,"creative":0.95,"execution":0.85,"people_facing":0.9,"degree_required":0.9,"license_required":0.95}',
  '{"wlb":"일반 사무 환경으로 야근 적고 교대 근무 없음","growth":"모사 공예 산업 기술 발전 기회 좋음","stability":"문화재 분야로 고용 안정성 높음","income":"전문 모사로 상위 소득","teamwork":"모사 작업 협업 요구","solo_deep":"작품 분석, 재료 파악 작업으로 독립 작업 多","analytical":"작품 재료 조사, 기법 분석으로 분석 매우 중요","creative":"형상과 색채 재현으로 창의성 높음","execution":"선묘사, 채색 실행 중심","people_facing":"자문위원 의견 참조 업무 매우 多","degree_required":"고졸 정도 학력 요구","license_required":"모사공 자격증 필수"}'
)
ON CONFLICT(job_id) DO UPDATE SET
  job_name = excluded.job_name,
  tagger_version = excluded.tagger_version,
  status = excluded.status,
  wlb = excluded.wlb,
  growth = excluded.growth,
  stability = excluded.stability,
  income = excluded.income,
  teamwork = excluded.teamwork,
  solo_deep = excluded.solo_deep,
  analytical = excluded.analytical,
  creative = excluded.creative,
  execution = excluded.execution,
  people_facing = excluded.people_facing,
  work_hours = excluded.work_hours,
  shift_work = excluded.shift_work,
  travel = excluded.travel,
  remote_possible = excluded.remote_possible,
  degree_required = excluded.degree_required,
  license_required = excluded.license_required,
  experience_required = excluded.experience_required,
  _confidence = excluded._confidence,
  _field_confidence_json = excluded._field_confidence_json,
  evidence_json = excluded.evidence_json,
  updated_at = CURRENT_TIMESTAMP;


INSERT INTO job_attributes (
  job_id, job_name, source_system, tagger_version, status,
  wlb, growth, stability, income,
  teamwork, solo_deep, analytical, creative, execution, people_facing,
  work_hours, shift_work, travel, remote_possible,
  degree_required, license_required, experience_required,
  _confidence, _field_confidence_json, evidence_json
) VALUES (
  '1765284788687550',
  '목조각원',
  'WORK24_DJOB',
  'tagger-v1.0.0',
  'tagged',
  75, 60, 75, 70,
  75, 45, 75, 85, 75, 65,
  'regular', 'none', 'none', 'none',
  'none', 'none', 'none',
  0.77,
  '{"wlb":0.8,"growth":0.75,"stability":0.85,"income":0.85,"teamwork":0.85,"solo_deep":0.6,"analytical":0.85,"creative":0.95,"execution":0.85,"people_facing":0.8,"degree_required":0.9,"license_required":0.9}',
  '{"wlb":"일반 사무 환경으로 야근 적고 교대 근무 없음","growth":"목조각 산업 기술 발전 기회 좋음","stability":"제조업으로 고용 안정성 좋음","income":"전문 조각으로 상위 소득","teamwork":"조각 작업 협업 요구","solo_deep":"도안 분석, 조각칼 사용 작업으로 독립 작업 多","analytical":"선과 면 분석, 깊이 측정으로 분석 중심","creative":"문양 조각 디자인으로 창의성 매우 높음","execution":"조각칼 사용, 다듬기 실행 중심","people_facing":"작업 점검 업무","degree_required":"고졸 정도 학력 요구","license_required":"특별 자격증 불필요"}'
)
ON CONFLICT(job_id) DO UPDATE SET
  job_name = excluded.job_name,
  tagger_version = excluded.tagger_version,
  status = excluded.status,
  wlb = excluded.wlb,
  growth = excluded.growth,
  stability = excluded.stability,
  income = excluded.income,
  teamwork = excluded.teamwork,
  solo_deep = excluded.solo_deep,
  analytical = excluded.analytical,
  creative = excluded.creative,
  execution = excluded.execution,
  people_facing = excluded.people_facing,
  work_hours = excluded.work_hours,
  shift_work = excluded.shift_work,
  travel = excluded.travel,
  remote_possible = excluded.remote_possible,
  degree_required = excluded.degree_required,
  license_required = excluded.license_required,
  experience_required = excluded.experience_required,
  _confidence = excluded._confidence,
  _field_confidence_json = excluded._field_confidence_json,
  evidence_json = excluded.evidence_json,
  updated_at = CURRENT_TIMESTAMP;


INSERT INTO job_attributes (
  job_id, job_name, source_system, tagger_version, status,
  wlb, growth, stability, income,
  teamwork, solo_deep, analytical, creative, execution, people_facing,
  work_hours, shift_work, travel, remote_possible,
  degree_required, license_required, experience_required,
  _confidence, _field_confidence_json, evidence_json
) VALUES (
  '1765284788963726',
  '물레성형원',
  'WORK24_DJOB',
  'tagger-v1.0.0',
  'tagged',
  75, 55, 75, 65,
  75, 45, 70, 75, 75, 65,
  'regular', 'none', 'none', 'none',
  'none', 'none', 'none',
  0.75,
  '{"wlb":0.8,"growth":0.7,"stability":0.85,"income":0.8,"teamwork":0.85,"solo_deep":0.6,"analytical":0.8,"creative":0.9,"execution":0.85,"people_facing":0.8,"degree_required":0.9,"license_required":0.9}',
  '{"wlb":"일반 사무 환경으로 야근 적고 교대 근무 없음","growth":"물레 성형 산업 기술 발전 기회 보통","stability":"제조업으로 고용 안정성 좋음","income":"전문 성형으로 중위 소득","teamwork":"성형 작업 협업 요구","solo_deep":"물레 회전, 도구 사용 작업으로 독립 작업 多","analytical":"모양과 크기 확인, 도구 선택으로 분석 중심","creative":"기물 형태 디자인으로 창의성 높음","execution":"물레 회전, 도구 사용 실행 중심","people_facing":"작업 점검 업무","degree_required":"중졸 정도 학력 요구","license_required":"특별 자격증 불필요"}'
)
ON CONFLICT(job_id) DO UPDATE SET
  job_name = excluded.job_name,
  tagger_version = excluded.tagger_version,
  status = excluded.status,
  wlb = excluded.wlb,
  growth = excluded.growth,
  stability = excluded.stability,
  income = excluded.income,
  teamwork = excluded.teamwork,
  solo_deep = excluded.solo_deep,
  analytical = excluded.analytical,
  creative = excluded.creative,
  execution = excluded.execution,
  people_facing = excluded.people_facing,
  work_hours = excluded.work_hours,
  shift_work = excluded.shift_work,
  travel = excluded.travel,
  remote_possible = excluded.remote_possible,
  degree_required = excluded.degree_required,
  license_required = excluded.license_required,
  experience_required = excluded.experience_required,
  _confidence = excluded._confidence,
  _field_confidence_json = excluded._field_confidence_json,
  evidence_json = excluded.evidence_json,
  updated_at = CURRENT_TIMESTAMP;


INSERT INTO job_attributes (
  job_id, job_name, source_system, tagger_version, status,
  wlb, growth, stability, income,
  teamwork, solo_deep, analytical, creative, execution, people_facing,
  work_hours, shift_work, travel, remote_possible,
  degree_required, license_required, experience_required,
  _confidence, _field_confidence_json, evidence_json
) VALUES (
  '1765284789269921',
  '부채제조원',
  'WORK24_DJOB',
  'tagger-v1.0.0',
  'tagged',
  75, 50, 75, 60,
  75, 40, 65, 70, 80, 70,
  'regular', 'none', 'none', 'none',
  'none', 'none', 'none',
  0.74,
  '{"wlb":0.8,"growth":0.65,"stability":0.85,"income":0.75,"teamwork":0.85,"solo_deep":0.55,"analytical":0.75,"creative":0.85,"execution":0.9,"people_facing":0.85,"degree_required":0.9,"license_required":0.9}',
  '{"wlb":"일반 사무 환경으로 야근 적고 교대 근무 없음","growth":"부채 제조 산업으로 성장 기회 제한적","stability":"제조업으로 고용 안정성 좋음","income":"전문 제조로 중위 소득","teamwork":"제조 작업 협업 요구","solo_deep":"원단 재단, 부챗살 배열 작업으로 독립 작업","analytical":"치수 계산, 형태 확인으로 분석 중심","creative":"장식 디자인, 그림 그리기로 창의성 높음","execution":"재단, 배열, 부착 실행 중심","people_facing":"작업 점검, 협의 업무 매우 多","degree_required":"고졸 정도 학력 요구","license_required":"특별 자격증 불필요"}'
)
ON CONFLICT(job_id) DO UPDATE SET
  job_name = excluded.job_name,
  tagger_version = excluded.tagger_version,
  status = excluded.status,
  wlb = excluded.wlb,
  growth = excluded.growth,
  stability = excluded.stability,
  income = excluded.income,
  teamwork = excluded.teamwork,
  solo_deep = excluded.solo_deep,
  analytical = excluded.analytical,
  creative = excluded.creative,
  execution = excluded.execution,
  people_facing = excluded.people_facing,
  work_hours = excluded.work_hours,
  shift_work = excluded.shift_work,
  travel = excluded.travel,
  remote_possible = excluded.remote_possible,
  degree_required = excluded.degree_required,
  license_required = excluded.license_required,
  experience_required = excluded.experience_required,
  _confidence = excluded._confidence,
  _field_confidence_json = excluded._field_confidence_json,
  evidence_json = excluded.evidence_json,
  updated_at = CURRENT_TIMESTAMP;


INSERT INTO job_attributes (
  job_id, job_name, source_system, tagger_version, status,
  wlb, growth, stability, income,
  teamwork, solo_deep, analytical, creative, execution, people_facing,
  work_hours, shift_work, travel, remote_possible,
  degree_required, license_required, experience_required,
  _confidence, _field_confidence_json, evidence_json
) VALUES (
  '1765284789569134',
  '상감원',
  'WORK24_DJOB',
  'tagger-v1.0.0',
  'tagged',
  75, 60, 75, 70,
  75, 45, 75, 85, 75, 65,
  'regular', 'none', 'none', 'none',
  'none', 'none', 'none',
  0.77,
  '{"wlb":0.8,"growth":0.75,"stability":0.85,"income":0.85,"teamwork":0.85,"solo_deep":0.6,"analytical":0.85,"creative":0.95,"execution":0.85,"people_facing":0.8,"degree_required":0.9,"license_required":0.9}',
  '{"wlb":"일반 사무 환경으로 야근 적고 교대 근무 없음","growth":"상감 공예 산업 기술 발전 기회 좋음","stability":"제조업으로 고용 안정성 좋음","income":"전문 상감으로 상위 소득","teamwork":"상감 작업 협업 요구","solo_deep":"문양 그리기, 음각 조각 작업으로 독립 작업 多","analytical":"문양 도안 분석, 재료 맞춤으로 분석 중심","creative":"상감 효과 디자인으로 창의성 매우 높음","execution":"음각 조각, 접착 실행 중심","people_facing":"작업 점검 업무","degree_required":"고졸 정도 학력 요구","license_required":"특별 자격증 불필요"}'
)
ON CONFLICT(job_id) DO UPDATE SET
  job_name = excluded.job_name,
  tagger_version = excluded.tagger_version,
  status = excluded.status,
  wlb = excluded.wlb,
  growth = excluded.growth,
  stability = excluded.stability,
  income = excluded.income,
  teamwork = excluded.teamwork,
  solo_deep = excluded.solo_deep,
  analytical = excluded.analytical,
  creative = excluded.creative,
  execution = excluded.execution,
  people_facing = excluded.people_facing,
  work_hours = excluded.work_hours,
  shift_work = excluded.shift_work,
  travel = excluded.travel,
  remote_possible = excluded.remote_possible,
  degree_required = excluded.degree_required,
  license_required = excluded.license_required,
  experience_required = excluded.experience_required,
  _confidence = excluded._confidence,
  _field_confidence_json = excluded._field_confidence_json,
  evidence_json = excluded.evidence_json,
  updated_at = CURRENT_TIMESTAMP;


INSERT INTO job_attributes (
  job_id, job_name, source_system, tagger_version, status,
  wlb, growth, stability, income,
  teamwork, solo_deep, analytical, creative, execution, people_facing,
  work_hours, shift_work, travel, remote_possible,
  degree_required, license_required, experience_required,
  _confidence, _field_confidence_json, evidence_json
) VALUES (
  '1765284789839617',
  '석고형제작원',
  'WORK24_DJOB',
  'tagger-v1.0.0',
  'tagged',
  75, 55, 75, 65,
  75, 40, 75, 60, 80, 65,
  'regular', 'none', 'none', 'none',
  'none', 'none', 'none',
  0.75,
  '{"wlb":0.8,"growth":0.7,"stability":0.85,"income":0.8,"teamwork":0.85,"solo_deep":0.55,"analytical":0.85,"creative":0.75,"execution":0.9,"people_facing":0.8,"degree_required":0.9,"license_required":0.9}',
  '{"wlb":"일반 사무 환경으로 야근 적고 교대 근무 없음","growth":"석고형 제작 산업 기술 발전 기회 보통","stability":"제조업으로 고용 안정성 좋음","income":"전문 제작으로 중위 소득","teamwork":"제작 작업 협업 요구","solo_deep":"도면 파악, 석고 혼합 작업으로 독립 작업","analytical":"규격 확인, 석고 양 파악으로 분석 중심","creative":"형태 디자인으로 창의성 요구","execution":"석고 혼합, 성형 실행 중심","people_facing":"작업 점검 업무","degree_required":"고졸 정도 학력 요구","license_required":"특별 자격증 불필요"}'
)
ON CONFLICT(job_id) DO UPDATE SET
  job_name = excluded.job_name,
  tagger_version = excluded.tagger_version,
  status = excluded.status,
  wlb = excluded.wlb,
  growth = excluded.growth,
  stability = excluded.stability,
  income = excluded.income,
  teamwork = excluded.teamwork,
  solo_deep = excluded.solo_deep,
  analytical = excluded.analytical,
  creative = excluded.creative,
  execution = excluded.execution,
  people_facing = excluded.people_facing,
  work_hours = excluded.work_hours,
  shift_work = excluded.shift_work,
  travel = excluded.travel,
  remote_possible = excluded.remote_possible,
  degree_required = excluded.degree_required,
  license_required = excluded.license_required,
  experience_required = excluded.experience_required,
  _confidence = excluded._confidence,
  _field_confidence_json = excluded._field_confidence_json,
  evidence_json = excluded.evidence_json,
  updated_at = CURRENT_TIMESTAMP;


INSERT INTO job_attributes (
  job_id, job_name, source_system, tagger_version, status,
  wlb, growth, stability, income,
  teamwork, solo_deep, analytical, creative, execution, people_facing,
  work_hours, shift_work, travel, remote_possible,
  degree_required, license_required, experience_required,
  _confidence, _field_confidence_json, evidence_json
) VALUES (
  '1765284790150693',
  '석제품제작원',
  'WORK24_DJOB',
  'tagger-v1.0.0',
  'tagged',
  70, 60, 75, 70,
  80, 45, 80, 85, 75, 75,
  'regular', 'none', 'frequent', 'none',
  'college', 'none', 'none',
  0.78,
  '{"wlb":0.75,"growth":0.75,"stability":0.85,"income":0.85,"teamwork":0.9,"solo_deep":0.6,"analytical":0.9,"creative":0.95,"execution":0.85,"people_facing":0.9,"degree_required":0.95,"license_required":0.9}',
  '{"wlb":"야외 작업 환경으로 야근 적고 교대 근무 없음","growth":"석제품 제작 산업 기술 발전 기회 좋음","stability":"제조업으로 고용 안정성 좋음","income":"전문 제작으로 상위 소득","teamwork":"제작 작업 협업 매우 중요","solo_deep":"도안 구상, 작업계획 수립 작업으로 독립 작업 多","analytical":"용도, 주제, 표현방법 분석으로 분석 매우 중요","creative":"제품 디자인, 표현기법으로 창의성 매우 높음","execution":"제작 계획 수립, 감독 실행 중심","people_facing":"의뢰인 상담, 협의 업무 매우 多","degree_required":"대졸 정도 학력 요구","license_required":"특별 자격증 불필요"}'
)
ON CONFLICT(job_id) DO UPDATE SET
  job_name = excluded.job_name,
  tagger_version = excluded.tagger_version,
  status = excluded.status,
  wlb = excluded.wlb,
  growth = excluded.growth,
  stability = excluded.stability,
  income = excluded.income,
  teamwork = excluded.teamwork,
  solo_deep = excluded.solo_deep,
  analytical = excluded.analytical,
  creative = excluded.creative,
  execution = excluded.execution,
  people_facing = excluded.people_facing,
  work_hours = excluded.work_hours,
  shift_work = excluded.shift_work,
  travel = excluded.travel,
  remote_possible = excluded.remote_possible,
  degree_required = excluded.degree_required,
  license_required = excluded.license_required,
  experience_required = excluded.experience_required,
  _confidence = excluded._confidence,
  _field_confidence_json = excluded._field_confidence_json,
  evidence_json = excluded.evidence_json,
  updated_at = CURRENT_TIMESTAMP;


INSERT INTO job_attributes (
  job_id, job_name, source_system, tagger_version, status,
  wlb, growth, stability, income,
  teamwork, solo_deep, analytical, creative, execution, people_facing,
  work_hours, shift_work, travel, remote_possible,
  degree_required, license_required, experience_required,
  _confidence, _field_confidence_json, evidence_json
) VALUES (
  '1765284790444847',
  '선물큐레이터',
  'WORK24_DJOB',
  'tagger-v1.0.0',
  'tagged',
  80, 70, 70, 65,
  75, 50, 80, 90, 70, 95,
  'regular', 'none', 'none', 'none',
  'none', 'none', 'none',
  0.79,
  '{"wlb":0.9,"growth":0.85,"stability":0.8,"income":0.8,"teamwork":0.85,"solo_deep":0.65,"analytical":0.9,"creative":0.95,"execution":0.8,"people_facing":0.98,"degree_required":0.9,"license_required":0.9}',
  '{"wlb":"일반 사무 환경으로 야근 적고 교대 근무 없음","growth":"선물 큐레이션 산업 기술 발전 기회 매우 좋음","stability":"서비스업으로 고용 안정성 보통","income":"전문 큐레이션으로 중위 소득","teamwork":"큐레이션 작업 협업 요구","solo_deep":"상황 분석, 콘셉트 정립 작업으로 독립 작업 多","analytical":"관계, 상황, 이유 파악으로 분석 매우 중요","creative":"콘셉트 기획, 스토리텔링으로 창의성 매우 높음","execution":"품목 추천, 기획 실행 중심","people_facing":"고객 상담, 상황 파악 업무 매우 多","degree_required":"고졸 정도 학력 요구","license_required":"특별 자격증 불필요"}'
)
ON CONFLICT(job_id) DO UPDATE SET
  job_name = excluded.job_name,
  tagger_version = excluded.tagger_version,
  status = excluded.status,
  wlb = excluded.wlb,
  growth = excluded.growth,
  stability = excluded.stability,
  income = excluded.income,
  teamwork = excluded.teamwork,
  solo_deep = excluded.solo_deep,
  analytical = excluded.analytical,
  creative = excluded.creative,
  execution = excluded.execution,
  people_facing = excluded.people_facing,
  work_hours = excluded.work_hours,
  shift_work = excluded.shift_work,
  travel = excluded.travel,
  remote_possible = excluded.remote_possible,
  degree_required = excluded.degree_required,
  license_required = excluded.license_required,
  experience_required = excluded.experience_required,
  _confidence = excluded._confidence,
  _field_confidence_json = excluded._field_confidence_json,
  evidence_json = excluded.evidence_json,
  updated_at = CURRENT_TIMESTAMP;


INSERT INTO job_attributes (
  job_id, job_name, source_system, tagger_version, status,
  wlb, growth, stability, income,
  teamwork, solo_deep, analytical, creative, execution, people_facing,
  work_hours, shift_work, travel, remote_possible,
  degree_required, license_required, experience_required,
  _confidence, _field_confidence_json, evidence_json
) VALUES (
  '1765284790705417',
  '섬유공예가',
  'WORK24_DJOB',
  'tagger-v1.0.0',
  'tagged',
  75, 65, 75, 65,
  70, 45, 70, 85, 75, 70,
  'regular', 'none', 'none', 'none',
  'none', 'none', 'none',
  0.77,
  '{"wlb":0.8,"growth":0.8,"stability":0.85,"income":0.8,"teamwork":0.8,"solo_deep":0.6,"analytical":0.8,"creative":0.95,"execution":0.85,"people_facing":0.85,"degree_required":0.9,"license_required":0.9}',
  '{"wlb":"일반 사무 환경으로 야근 적고 교대 근무 없음","growth":"섬유 공예 산업 기술 발전 기회 좋음","stability":"제조업으로 고용 안정성 좋음","income":"전문 공예로 중위 소득","teamwork":"공예 작업 협업 요구","solo_deep":"디자인 개발, 재료 선택 작업으로 독립 작업 多","analytical":"재료 특성 파악, 조합으로 분석 중심","creative":"디자인 개발, 가공방법으로 창의성 매우 높음","execution":"재료 가공, 제품 완성 실행 중심","people_facing":"작업 점검 업무","degree_required":"고졸 정도 학력 요구","license_required":"특별 자격증 불필요"}'
)
ON CONFLICT(job_id) DO UPDATE SET
  job_name = excluded.job_name,
  tagger_version = excluded.tagger_version,
  status = excluded.status,
  wlb = excluded.wlb,
  growth = excluded.growth,
  stability = excluded.stability,
  income = excluded.income,
  teamwork = excluded.teamwork,
  solo_deep = excluded.solo_deep,
  analytical = excluded.analytical,
  creative = excluded.creative,
  execution = excluded.execution,
  people_facing = excluded.people_facing,
  work_hours = excluded.work_hours,
  shift_work = excluded.shift_work,
  travel = excluded.travel,
  remote_possible = excluded.remote_possible,
  degree_required = excluded.degree_required,
  license_required = excluded.license_required,
  experience_required = excluded.experience_required,
  _confidence = excluded._confidence,
  _field_confidence_json = excluded._field_confidence_json,
  evidence_json = excluded.evidence_json,
  updated_at = CURRENT_TIMESTAMP;


INSERT INTO job_attributes (
  job_id, job_name, source_system, tagger_version, status,
  wlb, growth, stability, income,
  teamwork, solo_deep, analytical, creative, execution, people_facing,
  work_hours, shift_work, travel, remote_possible,
  degree_required, license_required, experience_required,
  _confidence, _field_confidence_json, evidence_json
) VALUES (
  '1765284790988963',
  '수타성형원',
  'WORK24_DJOB',
  'tagger-v1.0.0',
  'tagged',
  75, 55, 75, 65,
  75, 45, 70, 75, 75, 65,
  'regular', 'none', 'none', 'none',
  'none', 'none', 'none',
  0.75,
  '{"wlb":0.8,"growth":0.7,"stability":0.85,"income":0.8,"teamwork":0.85,"solo_deep":0.6,"analytical":0.8,"creative":0.9,"execution":0.85,"people_facing":0.8,"degree_required":0.9,"license_required":0.9}',
  '{"wlb":"일반 사무 환경으로 야근 적고 교대 근무 없음","growth":"수타 성형 산업 기술 발전 기회 보통","stability":"제조업으로 고용 안정성 좋음","income":"전문 성형으로 중위 소득","teamwork":"성형 작업 협업 요구","solo_deep":"소지 다루기, 도구 사용 작업으로 독립 작업 多","analytical":"규격, 형태 확인으로 분석 중심","creative":"기물 형태 디자인으로 창의성 높음","execution":"소지 다루기, 성형 실행 중심","people_facing":"작업 점검 업무","degree_required":"중졸 정도 학력 요구","license_required":"특별 자격증 불필요"}'
)
ON CONFLICT(job_id) DO UPDATE SET
  job_name = excluded.job_name,
  tagger_version = excluded.tagger_version,
  status = excluded.status,
  wlb = excluded.wlb,
  growth = excluded.growth,
  stability = excluded.stability,
  income = excluded.income,
  teamwork = excluded.teamwork,
  solo_deep = excluded.solo_deep,
  analytical = excluded.analytical,
  creative = excluded.creative,
  execution = excluded.execution,
  people_facing = excluded.people_facing,
  work_hours = excluded.work_hours,
  shift_work = excluded.shift_work,
  travel = excluded.travel,
  remote_possible = excluded.remote_possible,
  degree_required = excluded.degree_required,
  license_required = excluded.license_required,
  experience_required = excluded.experience_required,
  _confidence = excluded._confidence,
  _field_confidence_json = excluded._field_confidence_json,
  evidence_json = excluded.evidence_json,
  updated_at = CURRENT_TIMESTAMP;

COMMIT;