-- Batch tagging SQL generated at 2026-01-06T08:08:21.600Z
-- Tagger version: tagger-v1.0.0
-- Total jobs: 24

BEGIN TRANSACTION;


INSERT INTO job_attributes (
  job_id, job_name, source_system, tagger_version, status,
  wlb, growth, stability, income,
  teamwork, solo_deep, analytical, creative, execution, people_facing,
  work_hours, shift_work, travel, remote_possible,
  degree_required, license_required, experience_required,
  _confidence, _field_confidence_json, evidence_json
) VALUES (
  '1765284365990816',
  '공과금담당원',
  'WORK24_DJOB',
  'tagger-v1.0.0',
  'tagged',
  70, 40, 85, 40,
  50, 50, 55, 25, 70, 60,
  'regular', 'none', 'none', 'partial',
  'none', 'none', 'entry',
  0.86,
  '{"wlb":0.8,"growth":0.6,"stability":0.9,"income":0.6,"teamwork":0.7,"solo_deep":0.7,"analytical":0.7,"creative":0.5,"execution":0.8,"people_facing":0.8,"degree_required":0.95,"license_required":0.9}',
  '{"wlb":"실내 사무직으로 정규 근무시간, 야근 거의 없음","growth":"공과금 수납 업무로 성장 기회 제한적","stability":"공공금융 업무로 매우 안정적","income":"사무직으로 중간 수준 소득","teamwork":"수납 업무로 일부 협업","solo_deep":"수납, 송금 업무로 독립 작업 多","analytical":"수납 데이터 확인, 송금 처리로 분석 요구","creative":"표준화된 업무로 창의성 낮음","execution":"수납, 송금 실행 중심","people_facing":"고객 응대, 영수증 교부로 대면 업무","degree_required":"고졸 정도 학력 요구","license_required":"특별 자격증 요구 없음"}'
)
ON CONFLICT(job_id) DO UPDATE SET
  job_name = excluded.job_name,
  tagger_version = excluded.tagger_version,
  status = excluded.status,
  wlb = excluded.wlb,
  growth = excluded.growth,
  stability = excluded.stability,
  income = excluded.income,
  teamwork = excluded.teamwork,
  solo_deep = excluded.solo_deep,
  analytical = excluded.analytical,
  creative = excluded.creative,
  execution = excluded.execution,
  people_facing = excluded.people_facing,
  work_hours = excluded.work_hours,
  shift_work = excluded.shift_work,
  travel = excluded.travel,
  remote_possible = excluded.remote_possible,
  degree_required = excluded.degree_required,
  license_required = excluded.license_required,
  experience_required = excluded.experience_required,
  _confidence = excluded._confidence,
  _field_confidence_json = excluded._field_confidence_json,
  evidence_json = excluded.evidence_json,
  updated_at = CURRENT_TIMESTAMP;


INSERT INTO job_attributes (
  job_id, job_name, source_system, tagger_version, status,
  wlb, growth, stability, income,
  teamwork, solo_deep, analytical, creative, execution, people_facing,
  work_hours, shift_work, travel, remote_possible,
  degree_required, license_required, experience_required,
  _confidence, _field_confidence_json, evidence_json
) VALUES (
  '1765284366277152',
  '교환어음처리원',
  'WORK24_DJOB',
  'tagger-v1.0.0',
  'tagged',
  65, 50, 85, 45,
  60, 40, 70, 25, 75, 50,
  'regular', 'none', 'none', 'partial',
  'bachelor', 'none', 'entry',
  0.84,
  '{"wlb":0.8,"growth":0.7,"stability":0.9,"income":0.6,"teamwork":0.7,"solo_deep":0.6,"analytical":0.8,"creative":0.5,"execution":0.8,"people_facing":0.7,"degree_required":0.9,"license_required":0.8}',
  '{"wlb":"실내 사무직으로 정규 근무, 야근 적음","growth":"어음 처리 업무로 일부 전문성 향상","stability":"금융결제원 업무로 매우 안정적","income":"사무직으로 중간 수준 소득","teamwork":"어음 교환 입회, 협의로 협업 필요","solo_deep":"데이터 집계, 확인으로 독립 작업","analytical":"어음 자료 확인, 집계, 결제 자료 작성으로 분석 중심","creative":"표준화된 업무로 창의성 낮음","execution":"어음 교환, 자료 처리 실행 중심","people_facing":"은행 담당자와 협의로 대면 업무","degree_required":"대졸 정도 학력 요구","license_required":"특별 자격증 요구 없음"}'
)
ON CONFLICT(job_id) DO UPDATE SET
  job_name = excluded.job_name,
  tagger_version = excluded.tagger_version,
  status = excluded.status,
  wlb = excluded.wlb,
  growth = excluded.growth,
  stability = excluded.stability,
  income = excluded.income,
  teamwork = excluded.teamwork,
  solo_deep = excluded.solo_deep,
  analytical = excluded.analytical,
  creative = excluded.creative,
  execution = excluded.execution,
  people_facing = excluded.people_facing,
  work_hours = excluded.work_hours,
  shift_work = excluded.shift_work,
  travel = excluded.travel,
  remote_possible = excluded.remote_possible,
  degree_required = excluded.degree_required,
  license_required = excluded.license_required,
  experience_required = excluded.experience_required,
  _confidence = excluded._confidence,
  _field_confidence_json = excluded._field_confidence_json,
  evidence_json = excluded.evidence_json,
  updated_at = CURRENT_TIMESTAMP;


INSERT INTO job_attributes (
  job_id, job_name, source_system, tagger_version, status,
  wlb, growth, stability, income,
  teamwork, solo_deep, analytical, creative, execution, people_facing,
  work_hours, shift_work, travel, remote_possible,
  degree_required, license_required, experience_required,
  _confidence, _field_confidence_json, evidence_json
) VALUES (
  '1765284366578539',
  '국민주택기금관리원',
  'WORK24_DJOB',
  'tagger-v1.0.0',
  'tagged',
  65, 60, 85, 50,
  55, 45, 75, 35, 70, 50,
  'regular', 'none', 'none', 'partial',
  'bachelor', 'none', 'none',
  0.82,
  '{"wlb":0.8,"growth":0.7,"stability":0.9,"income":0.6,"teamwork":0.7,"solo_deep":0.6,"analytical":0.85,"creative":0.6,"execution":0.8,"people_facing":0.7,"degree_required":0.9,"license_required":0.8}',
  '{"wlb":"실내 사무직으로 정규 근무","growth":"기금 운용 정책 수립으로 성장 기회 좋음","stability":"정부 기금 관리로 매우 안정적","income":"전문 사무직으로 중상위 소득","teamwork":"조사연구, 심사로 협업 필요","solo_deep":"운용계획 수립, 조사연구로 독립 작업","analytical":"기금 운용 분석, 정책 제안, 심사로 분석 중심","creative":"운용계획 수립, 정책 제안으로 창의성 요구","execution":"기금 집행, 관리 실행 중심","people_facing":"대출 심사, 사후관리로 대면 업무","degree_required":"대졸 정도 학력 요구","license_required":"특별 자격증 요구 없음"}'
)
ON CONFLICT(job_id) DO UPDATE SET
  job_name = excluded.job_name,
  tagger_version = excluded.tagger_version,
  status = excluded.status,
  wlb = excluded.wlb,
  growth = excluded.growth,
  stability = excluded.stability,
  income = excluded.income,
  teamwork = excluded.teamwork,
  solo_deep = excluded.solo_deep,
  analytical = excluded.analytical,
  creative = excluded.creative,
  execution = excluded.execution,
  people_facing = excluded.people_facing,
  work_hours = excluded.work_hours,
  shift_work = excluded.shift_work,
  travel = excluded.travel,
  remote_possible = excluded.remote_possible,
  degree_required = excluded.degree_required,
  license_required = excluded.license_required,
  experience_required = excluded.experience_required,
  _confidence = excluded._confidence,
  _field_confidence_json = excluded._field_confidence_json,
  evidence_json = excluded.evidence_json,
  updated_at = CURRENT_TIMESTAMP;


INSERT INTO job_attributes (
  job_id, job_name, source_system, tagger_version, status,
  wlb, growth, stability, income,
  teamwork, solo_deep, analytical, creative, execution, people_facing,
  work_hours, shift_work, travel, remote_possible,
  degree_required, license_required, experience_required,
  _confidence, _field_confidence_json, evidence_json
) VALUES (
  '1765284366904758',
  '국제증권예탁결제사무원',
  'WORK24_DJOB',
  'tagger-v1.0.0',
  'tagged',
  70, 55, 80, 50,
  55, 45, 70, 30, 75, 45,
  'regular', 'none', 'none', 'partial',
  'bachelor', 'none', 'entry',
  0.83,
  '{"wlb":0.8,"growth":0.7,"stability":0.9,"income":0.6,"teamwork":0.7,"solo_deep":0.6,"analytical":0.8,"creative":0.5,"execution":0.8,"people_facing":0.6,"degree_required":0.9,"license_required":0.8}',
  '{"wlb":"실내 사무직으로 정규 근무","growth":"국제 증권 업무로 전문성 향상 기회","stability":"증권예탁원 업무로 안정적","income":"전문 금융 업무로 중상위 소득","teamwork":"계좌 관리, 결제 처리로 협업 필요","solo_deep":"결제 업무, 권리 행사로 독립 작업","analytical":"외화증권 관리, 결제, 권리 행사로 분석 요구","creative":"시스템 운영으로 일부 창의성","execution":"예탁, 결제, 권리 행사 실행 중심","people_facing":"기관 투자자 협의로 대면 업무","degree_required":"대졸 정도 학력 요구","license_required":"특별 자격증 요구 없음"}'
)
ON CONFLICT(job_id) DO UPDATE SET
  job_name = excluded.job_name,
  tagger_version = excluded.tagger_version,
  status = excluded.status,
  wlb = excluded.wlb,
  growth = excluded.growth,
  stability = excluded.stability,
  income = excluded.income,
  teamwork = excluded.teamwork,
  solo_deep = excluded.solo_deep,
  analytical = excluded.analytical,
  creative = excluded.creative,
  execution = excluded.execution,
  people_facing = excluded.people_facing,
  work_hours = excluded.work_hours,
  shift_work = excluded.shift_work,
  travel = excluded.travel,
  remote_possible = excluded.remote_possible,
  degree_required = excluded.degree_required,
  license_required = excluded.license_required,
  experience_required = excluded.experience_required,
  _confidence = excluded._confidence,
  _field_confidence_json = excluded._field_confidence_json,
  evidence_json = excluded.evidence_json,
  updated_at = CURRENT_TIMESTAMP;


INSERT INTO job_attributes (
  job_id, job_name, source_system, tagger_version, status,
  wlb, growth, stability, income,
  teamwork, solo_deep, analytical, creative, execution, people_facing,
  work_hours, shift_work, travel, remote_possible,
  degree_required, license_required, experience_required,
  _confidence, _field_confidence_json, evidence_json
) VALUES (
  '1765284367200806',
  '국제투자신탁사무원',
  'WORK24_DJOB',
  'tagger-v1.0.0',
  'tagged',
  65, 65, 75, 55,
  60, 40, 80, 50, 65, 55,
  'regular', 'none', 'none', 'partial',
  'bachelor', 'none', 'none',
  0.81,
  '{"wlb":0.8,"growth":0.8,"stability":0.85,"income":0.7,"teamwork":0.7,"solo_deep":0.6,"analytical":0.9,"creative":0.7,"execution":0.7,"people_facing":0.7,"degree_required":0.9,"license_required":0.8}',
  '{"wlb":"실내 사무직으로 정규 근무","growth":"국제 투자 분석, 신상품 개발로 성장 기회 매우 좋음","stability":"투자신탁 업무로 비교적 안정적","income":"전문 투자 업무로 상위 소득","teamwork":"시장 조사, 상품 개발로 협업 필요","solo_deep":"투자 분석, 계획 수립으로 독립 작업","analytical":"시장 조사, 투자 분석, 신상품 개발로 분석 중심","creative":"신상품 개발, 마케팅 전략으로 창의성 높음","execution":"투자 실행, 계약 체결로 실행 중심","people_facing":"기관 투자자 협의로 대면 업무","degree_required":"대졸 정도 학력 요구","license_required":"특별 자격증 요구 없음"}'
)
ON CONFLICT(job_id) DO UPDATE SET
  job_name = excluded.job_name,
  tagger_version = excluded.tagger_version,
  status = excluded.status,
  wlb = excluded.wlb,
  growth = excluded.growth,
  stability = excluded.stability,
  income = excluded.income,
  teamwork = excluded.teamwork,
  solo_deep = excluded.solo_deep,
  analytical = excluded.analytical,
  creative = excluded.creative,
  execution = excluded.execution,
  people_facing = excluded.people_facing,
  work_hours = excluded.work_hours,
  shift_work = excluded.shift_work,
  travel = excluded.travel,
  remote_possible = excluded.remote_possible,
  degree_required = excluded.degree_required,
  license_required = excluded.license_required,
  experience_required = excluded.experience_required,
  _confidence = excluded._confidence,
  _field_confidence_json = excluded._field_confidence_json,
  evidence_json = excluded.evidence_json,
  updated_at = CURRENT_TIMESTAMP;


INSERT INTO job_attributes (
  job_id, job_name, source_system, tagger_version, status,
  wlb, growth, stability, income,
  teamwork, solo_deep, analytical, creative, execution, people_facing,
  work_hours, shift_work, travel, remote_possible,
  degree_required, license_required, experience_required,
  _confidence, _field_confidence_json, evidence_json
) VALUES (
  '1765284367542714',
  '금고담당은행사무원',
  'WORK24_DJOB',
  'tagger-v1.0.0',
  'tagged',
  70, 40, 90, 40,
  50, 50, 55, 20, 75, 40,
  'regular', 'none', 'none', 'none',
  'college', 'none', 'entry',
  0.87,
  '{"wlb":0.8,"growth":0.6,"stability":0.95,"income":0.6,"teamwork":0.7,"solo_deep":0.7,"analytical":0.7,"creative":0.4,"execution":0.8,"people_facing":0.6,"degree_required":0.9,"license_required":0.9}',
  '{"wlb":"실내 사무직으로 정규 근무","growth":"금고 관리 업무로 성장 기회 제한적","stability":"공공기관 금고 업무로 매우 안정적","income":"사무직으로 중간 수준 소득","teamwork":"수납, 지급 업무로 협업 적음","solo_deep":"집계, 확인 업무로 독립 작업 多","analytical":"수입지출 집계, 확인으로 분석 요구","creative":"표준화된 업무로 창의성 낮음","execution":"수납, 지급, 집계 실행 중심","people_facing":"공공기관 담당자와 협의로 대면 업무 적음","degree_required":"전문대졸 정도 학력 요구","license_required":"특별 자격증 요구 없음"}'
)
ON CONFLICT(job_id) DO UPDATE SET
  job_name = excluded.job_name,
  tagger_version = excluded.tagger_version,
  status = excluded.status,
  wlb = excluded.wlb,
  growth = excluded.growth,
  stability = excluded.stability,
  income = excluded.income,
  teamwork = excluded.teamwork,
  solo_deep = excluded.solo_deep,
  analytical = excluded.analytical,
  creative = excluded.creative,
  execution = excluded.execution,
  people_facing = excluded.people_facing,
  work_hours = excluded.work_hours,
  shift_work = excluded.shift_work,
  travel = excluded.travel,
  remote_possible = excluded.remote_possible,
  degree_required = excluded.degree_required,
  license_required = excluded.license_required,
  experience_required = excluded.experience_required,
  _confidence = excluded._confidence,
  _field_confidence_json = excluded._field_confidence_json,
  evidence_json = excluded.evidence_json,
  updated_at = CURRENT_TIMESTAMP;


INSERT INTO job_attributes (
  job_id, job_name, source_system, tagger_version, status,
  wlb, growth, stability, income,
  teamwork, solo_deep, analytical, creative, execution, people_facing,
  work_hours, shift_work, travel, remote_possible,
  degree_required, license_required, experience_required,
  _confidence, _field_confidence_json, evidence_json
) VALUES (
  '1765284367916872',
  '금융고객관리사무원',
  'WORK24_DJOB',
  'tagger-v1.0.0',
  'tagged',
  65, 60, 75, 50,
  70, 30, 75, 55, 65, 75,
  'regular', 'none', 'none', 'partial',
  'bachelor', 'none', 'none',
  0.83,
  '{"wlb":0.8,"growth":0.7,"stability":0.85,"income":0.6,"teamwork":0.8,"solo_deep":0.5,"analytical":0.85,"creative":0.8,"execution":0.7,"people_facing":0.9,"degree_required":0.9,"license_required":0.8}',
  '{"wlb":"실내 사무직으로 정규 근무","growth":"고객 분석, 마케팅으로 성장 기회 좋음","stability":"금융기관 업무로 비교적 안정적","income":"전문 고객 관리로 중상위 소득","teamwork":"프로모션 기획, 마케팅으로 협업 多","solo_deep":"고객 분석, 전략 수립으로 독립 작업","analytical":"고객 특성 분석, 시장 조사로 분석 중심","creative":"프로모션 테마 개발, 마케팅 전략으로 창의성 높음","execution":"프로모션 실시, 전략 추진으로 실행 중심","people_facing":"고객 유치, 관리로 대면 업무 多","degree_required":"대졸 정도 학력 요구","license_required":"특별 자격증 요구 없음"}'
)
ON CONFLICT(job_id) DO UPDATE SET
  job_name = excluded.job_name,
  tagger_version = excluded.tagger_version,
  status = excluded.status,
  wlb = excluded.wlb,
  growth = excluded.growth,
  stability = excluded.stability,
  income = excluded.income,
  teamwork = excluded.teamwork,
  solo_deep = excluded.solo_deep,
  analytical = excluded.analytical,
  creative = excluded.creative,
  execution = excluded.execution,
  people_facing = excluded.people_facing,
  work_hours = excluded.work_hours,
  shift_work = excluded.shift_work,
  travel = excluded.travel,
  remote_possible = excluded.remote_possible,
  degree_required = excluded.degree_required,
  license_required = excluded.license_required,
  experience_required = excluded.experience_required,
  _confidence = excluded._confidence,
  _field_confidence_json = excluded._field_confidence_json,
  evidence_json = excluded.evidence_json,
  updated_at = CURRENT_TIMESTAMP;


INSERT INTO job_attributes (
  job_id, job_name, source_system, tagger_version, status,
  wlb, growth, stability, income,
  teamwork, solo_deep, analytical, creative, execution, people_facing,
  work_hours, shift_work, travel, remote_possible,
  degree_required, license_required, experience_required,
  _confidence, _field_confidence_json, evidence_json
) VALUES (
  '1765284368255746',
  '금융기관지점관리사무원',
  'WORK24_DJOB',
  'tagger-v1.0.0',
  'tagged',
  60, 65, 80, 55,
  70, 30, 80, 50, 70, 80,
  'regular', 'none', 'some', 'none',
  'bachelor', 'none', 'entry',
  0.82,
  '{"wlb":0.7,"growth":0.8,"stability":0.9,"income":0.7,"teamwork":0.8,"solo_deep":0.5,"analytical":0.9,"creative":0.7,"execution":0.8,"people_facing":0.9,"degree_required":0.9,"license_required":0.8}',
  '{"wlb":"실내 사무직으로 정규 근무, 출장 가능","growth":"지점 관리, 교육으로 성장 기회 매우 좋음","stability":"금융기관 업무로 안정적","income":"관리 업무로 상위 소득","teamwork":"지점 평가, 교육 실시로 협업 多","solo_deep":"실적 분석, 계획 수립으로 독립 작업","analytical":"지점 실적 분석, 판촉계획 수립으로 분석 중심","creative":"교육계획 수립, 개선방안 마련으로 창의성 요구","execution":"평가 실시, 교육 진행으로 실행 중심","people_facing":"지점장 협의, 교육 실시로 대면 업무 多","degree_required":"대졸 정도 학력 요구","license_required":"특별 자격증 요구 없음"}'
)
ON CONFLICT(job_id) DO UPDATE SET
  job_name = excluded.job_name,
  tagger_version = excluded.tagger_version,
  status = excluded.status,
  wlb = excluded.wlb,
  growth = excluded.growth,
  stability = excluded.stability,
  income = excluded.income,
  teamwork = excluded.teamwork,
  solo_deep = excluded.solo_deep,
  analytical = excluded.analytical,
  creative = excluded.creative,
  execution = excluded.execution,
  people_facing = excluded.people_facing,
  work_hours = excluded.work_hours,
  shift_work = excluded.shift_work,
  travel = excluded.travel,
  remote_possible = excluded.remote_possible,
  degree_required = excluded.degree_required,
  license_required = excluded.license_required,
  experience_required = excluded.experience_required,
  _confidence = excluded._confidence,
  _field_confidence_json = excluded._field_confidence_json,
  evidence_json = excluded.evidence_json,
  updated_at = CURRENT_TIMESTAMP;


INSERT INTO job_attributes (
  job_id, job_name, source_system, tagger_version, status,
  wlb, growth, stability, income,
  teamwork, solo_deep, analytical, creative, execution, people_facing,
  work_hours, shift_work, travel, remote_possible,
  degree_required, license_required, experience_required,
  _confidence, _field_confidence_json, evidence_json
) VALUES (
  '1765284368538570',
  '금융대출감정사무원',
  'WORK24_DJOB',
  'tagger-v1.0.0',
  'tagged',
  60, 55, 75, 50,
  55, 45, 75, 35, 70, 45,
  'regular', 'none', 'some', 'none',
  'bachelor', 'none', 'none',
  0.84,
  '{"wlb":0.7,"growth":0.7,"stability":0.85,"income":0.6,"teamwork":0.7,"solo_deep":0.6,"analytical":0.85,"creative":0.6,"execution":0.8,"people_facing":0.6,"degree_required":0.9,"license_required":0.8}',
  '{"wlb":"실내외 업무로 정규 근무, 현장답사","growth":"담보물 감정으로 전문성 향상 기회 좋음","stability":"금융기관 업무로 비교적 안정적","income":"전문 감정 업무로 중상위 소득","teamwork":"감정 업무로 협업 적음","solo_deep":"현장 조사, 평가서 작성으로 독립 작업 多","analytical":"토지 감정, 가격 평가, 공부 열람으로 분석 중심","creative":"평가 방법 결정으로 일부 창의성","execution":"현장 조사, 평가서 작성 실행 중심","people_facing":"관계자 협의로 대면 업무 적음","degree_required":"대졸 정도 학력 요구","license_required":"특별 자격증 요구 없음"}'
)
ON CONFLICT(job_id) DO UPDATE SET
  job_name = excluded.job_name,
  tagger_version = excluded.tagger_version,
  status = excluded.status,
  wlb = excluded.wlb,
  growth = excluded.growth,
  stability = excluded.stability,
  income = excluded.income,
  teamwork = excluded.teamwork,
  solo_deep = excluded.solo_deep,
  analytical = excluded.analytical,
  creative = excluded.creative,
  execution = excluded.execution,
  people_facing = excluded.people_facing,
  work_hours = excluded.work_hours,
  shift_work = excluded.shift_work,
  travel = excluded.travel,
  remote_possible = excluded.remote_possible,
  degree_required = excluded.degree_required,
  license_required = excluded.license_required,
  experience_required = excluded.experience_required,
  _confidence = excluded._confidence,
  _field_confidence_json = excluded._field_confidence_json,
  evidence_json = excluded.evidence_json,
  updated_at = CURRENT_TIMESTAMP;


INSERT INTO job_attributes (
  job_id, job_name, source_system, tagger_version, status,
  wlb, growth, stability, income,
  teamwork, solo_deep, analytical, creative, execution, people_facing,
  work_hours, shift_work, travel, remote_possible,
  degree_required, license_required, experience_required,
  _confidence, _field_confidence_json, evidence_json
) VALUES (
  '1765284368913454',
  '금융위험모니터링원',
  'WORK24_DJOB',
  'tagger-v1.0.0',
  'tagged',
  65, 65, 75, 55,
  55, 45, 85, 40, 65, 40,
  'regular', 'none', 'none', 'partial',
  'bachelor', 'none', 'entry',
  0.83,
  '{"wlb":0.8,"growth":0.8,"stability":0.85,"income":0.7,"teamwork":0.7,"solo_deep":0.6,"analytical":0.95,"creative":0.6,"execution":0.7,"people_facing":0.6,"degree_required":0.9,"license_required":0.8}',
  '{"wlb":"실내 사무직으로 정규 근무","growth":"위험 모니터링으로 전문성 향상 기회 매우 좋음","stability":"금융기관 업무로 비교적 안정적","income":"전문 리스크 관리로 상위 소득","teamwork":"모니터링 결과 공유로 협업 필요","solo_deep":"자산현황 파악, 분석으로 독립 작업 多","analytical":"자산운용 모니터링, 위험 분석으로 분석 중심","creative":"모니터링 방법 개발로 일부 창의성","execution":"모니터링, 보고서 작성 실행 중심","people_facing":"내부 보고로 대면 업무 적음","degree_required":"대졸 정도 학력 요구","license_required":"특별 자격증 요구 없음"}'
)
ON CONFLICT(job_id) DO UPDATE SET
  job_name = excluded.job_name,
  tagger_version = excluded.tagger_version,
  status = excluded.status,
  wlb = excluded.wlb,
  growth = excluded.growth,
  stability = excluded.stability,
  income = excluded.income,
  teamwork = excluded.teamwork,
  solo_deep = excluded.solo_deep,
  analytical = excluded.analytical,
  creative = excluded.creative,
  execution = excluded.execution,
  people_facing = excluded.people_facing,
  work_hours = excluded.work_hours,
  shift_work = excluded.shift_work,
  travel = excluded.travel,
  remote_possible = excluded.remote_possible,
  degree_required = excluded.degree_required,
  license_required = excluded.license_required,
  experience_required = excluded.experience_required,
  _confidence = excluded._confidence,
  _field_confidence_json = excluded._field_confidence_json,
  evidence_json = excluded.evidence_json,
  updated_at = CURRENT_TIMESTAMP;


INSERT INTO job_attributes (
  job_id, job_name, source_system, tagger_version, status,
  wlb, growth, stability, income,
  teamwork, solo_deep, analytical, creative, execution, people_facing,
  work_hours, shift_work, travel, remote_possible,
  degree_required, license_required, experience_required,
  _confidence, _field_confidence_json, evidence_json
) VALUES (
  '1765284372771868',
  '수신사무관리자',
  'WORK24_DJOB',
  'tagger-v1.0.0',
  'tagged',
  55, 70, 75, 60,
  65, 35, 75, 55, 70, 70,
  'regular', 'none', 'none', 'partial',
  'bachelor', 'none', 'none',
  0.79,
  '{"wlb":0.6,"growth":0.8,"stability":0.85,"income":0.7,"teamwork":0.8,"solo_deep":0.5,"analytical":0.85,"creative":0.7,"execution":0.8,"people_facing":0.8,"degree_required":0.9,"license_required":0.8}',
  '{"wlb":"실내 사무직으로 정규 근무","growth":"수신 상품 개발, 정책 수립으로 성장 기회 매우 좋음","stability":"은행 업무로 안정적","income":"관리자급으로 높은 소득","teamwork":"상품 개발, 제도 개선으로 협업 多","solo_deep":"상품 개발, 정책 수립으로 독립 작업","analytical":"수신 데이터 분석, 정책 수립으로 분석 중심","creative":"새 상품 개발, 마케팅으로 창의성 높음","execution":"상품 개발, 정책 실행 중심","people_facing":"고객 상담, 상품 안내로 대면 업무 多","degree_required":"대졸 정도 학력 요구","license_required":"특별 자격증 요구 없음"}'
)
ON CONFLICT(job_id) DO UPDATE SET
  job_name = excluded.job_name,
  tagger_version = excluded.tagger_version,
  status = excluded.status,
  wlb = excluded.wlb,
  growth = excluded.growth,
  stability = excluded.stability,
  income = excluded.income,
  teamwork = excluded.teamwork,
  solo_deep = excluded.solo_deep,
  analytical = excluded.analytical,
  creative = excluded.creative,
  execution = excluded.execution,
  people_facing = excluded.people_facing,
  work_hours = excluded.work_hours,
  shift_work = excluded.shift_work,
  travel = excluded.travel,
  remote_possible = excluded.remote_possible,
  degree_required = excluded.degree_required,
  license_required = excluded.license_required,
  experience_required = excluded.experience_required,
  _confidence = excluded._confidence,
  _field_confidence_json = excluded._field_confidence_json,
  evidence_json = excluded.evidence_json,
  updated_at = CURRENT_TIMESTAMP;


INSERT INTO job_attributes (
  job_id, job_name, source_system, tagger_version, status,
  wlb, growth, stability, income,
  teamwork, solo_deep, analytical, creative, execution, people_facing,
  work_hours, shift_work, travel, remote_possible,
  degree_required, license_required, experience_required,
  _confidence, _field_confidence_json, evidence_json
) VALUES (
  '1765284373066487',
  '수신사무원',
  'WORK24_DJOB',
  'tagger-v1.0.0',
  'tagged',
  65, 40, 85, 40,
  60, 40, 50, 25, 75, 80,
  'regular', 'none', 'none', 'none',
  'none', 'none', 'entry',
  0.86,
  '{"wlb":0.8,"growth":0.6,"stability":0.95,"income":0.6,"teamwork":0.7,"solo_deep":0.6,"analytical":0.7,"creative":0.4,"execution":0.8,"people_facing":0.9,"degree_required":0.95,"license_required":0.9}',
  '{"wlb":"실내 창구 업무로 정규 근무","growth":"수신 업무 경험으로 성장 기회 제한적","stability":"은행 창구 업무로 매우 안정적","income":"사무직으로 중간 수준 소득","teamwork":"창구 업무, 고객 응대로 협업 필요","solo_deep":"통장 발행, 입출금 업무로 독립 작업","analytical":"거래 확인, 서류 검토로 일부 분석","creative":"표준화된 업무로 창의성 낮음","execution":"입출금, 발행 실행 중심","people_facing":"고객 응대, 상담으로 대면 업무 多","degree_required":"고졸 정도 학력 요구","license_required":"특별 자격증 요구 없음"}'
)
ON CONFLICT(job_id) DO UPDATE SET
  job_name = excluded.job_name,
  tagger_version = excluded.tagger_version,
  status = excluded.status,
  wlb = excluded.wlb,
  growth = excluded.growth,
  stability = excluded.stability,
  income = excluded.income,
  teamwork = excluded.teamwork,
  solo_deep = excluded.solo_deep,
  analytical = excluded.analytical,
  creative = excluded.creative,
  execution = excluded.execution,
  people_facing = excluded.people_facing,
  work_hours = excluded.work_hours,
  shift_work = excluded.shift_work,
  travel = excluded.travel,
  remote_possible = excluded.remote_possible,
  degree_required = excluded.degree_required,
  license_required = excluded.license_required,
  experience_required = excluded.experience_required,
  _confidence = excluded._confidence,
  _field_confidence_json = excluded._field_confidence_json,
  evidence_json = excluded.evidence_json,
  updated_at = CURRENT_TIMESTAMP;


INSERT INTO job_attributes (
  job_id, job_name, source_system, tagger_version, status,
  wlb, growth, stability, income,
  teamwork, solo_deep, analytical, creative, execution, people_facing,
  work_hours, shift_work, travel, remote_possible,
  degree_required, license_required, experience_required,
  _confidence, _field_confidence_json, evidence_json
) VALUES (
  '1765284373379355',
  '수신제도기획원',
  'WORK24_DJOB',
  'tagger-v1.0.0',
  'tagged',
  65, 70, 75, 55,
  70, 30, 80, 60, 65, 60,
  'regular', 'none', 'none', 'partial',
  'bachelor', 'none', 'none',
  0.81,
  '{"wlb":0.8,"growth":0.8,"stability":0.85,"income":0.7,"teamwork":0.8,"solo_deep":0.5,"analytical":0.9,"creative":0.8,"execution":0.7,"people_facing":0.7,"degree_required":0.9,"license_required":0.8}',
  '{"wlb":"실내 사무직으로 정규 근무","growth":"수신 제도 기획으로 전문성 향상 기회 매우 좋음","stability":"은행 업무로 비교적 안정적","income":"전문 기획 업무로 상위 소득","teamwork":"상품 개발, 제휴로 협업 多","solo_deep":"시장 조사, 기획 수립으로 독립 작업","analytical":"시장 조사, 상품 분석으로 분석 중심","creative":"신상품 개발, 제휴 기획으로 창의성 높음","execution":"제도 개선, 상품 개발 실행 중심","people_facing":"제휴사 협의, 고객 분석으로 대면 업무","degree_required":"대졸 정도 학력 요구","license_required":"특별 자격증 요구 없음"}'
)
ON CONFLICT(job_id) DO UPDATE SET
  job_name = excluded.job_name,
  tagger_version = excluded.tagger_version,
  status = excluded.status,
  wlb = excluded.wlb,
  growth = excluded.growth,
  stability = excluded.stability,
  income = excluded.income,
  teamwork = excluded.teamwork,
  solo_deep = excluded.solo_deep,
  analytical = excluded.analytical,
  creative = excluded.creative,
  execution = excluded.execution,
  people_facing = excluded.people_facing,
  work_hours = excluded.work_hours,
  shift_work = excluded.shift_work,
  travel = excluded.travel,
  remote_possible = excluded.remote_possible,
  degree_required = excluded.degree_required,
  license_required = excluded.license_required,
  experience_required = excluded.experience_required,
  _confidence = excluded._confidence,
  _field_confidence_json = excluded._field_confidence_json,
  evidence_json = excluded.evidence_json,
  updated_at = CURRENT_TIMESTAMP;


INSERT INTO job_attributes (
  job_id, job_name, source_system, tagger_version, status,
  wlb, growth, stability, income,
  teamwork, solo_deep, analytical, creative, execution, people_facing,
  work_hours, shift_work, travel, remote_possible,
  degree_required, license_required, experience_required,
  _confidence, _field_confidence_json, evidence_json
) VALUES (
  '176528437367064',
  '수신총괄사무원',
  'WORK24_DJOB',
  'tagger-v1.0.0',
  'tagged',
  60, 65, 80, 55,
  75, 25, 75, 50, 70, 70,
  'regular', 'none', 'none', 'partial',
  'bachelor', 'none', 'entry',
  0.82,
  '{"wlb":0.7,"growth":0.8,"stability":0.9,"income":0.7,"teamwork":0.85,"solo_deep":0.4,"analytical":0.85,"creative":0.7,"execution":0.8,"people_facing":0.8,"degree_required":0.9,"license_required":0.8}',
  '{"wlb":"실내 사무직으로 정규 근무","growth":"수신 총괄로 전문성 향상 기회 좋음","stability":"은행 업무로 안정적","income":"총괄 업무로 상위 소득","teamwork":"지점 관리, 교육 실시로 협업 多","solo_deep":"실적 분석, 전략 수립으로 독립 작업","analytical":"수신 데이터 분석, 실적 평가로 분석 중심","creative":"마케팅 전략 수립으로 창의성 요구","execution":"계획 수립, 교육 진행으로 실행 중심","people_facing":"지점장 협의, 교육 실시로 대면 업무 多","degree_required":"대졸 정도 학력 요구","license_required":"특별 자격증 요구 없음"}'
)
ON CONFLICT(job_id) DO UPDATE SET
  job_name = excluded.job_name,
  tagger_version = excluded.tagger_version,
  status = excluded.status,
  wlb = excluded.wlb,
  growth = excluded.growth,
  stability = excluded.stability,
  income = excluded.income,
  teamwork = excluded.teamwork,
  solo_deep = excluded.solo_deep,
  analytical = excluded.analytical,
  creative = excluded.creative,
  execution = excluded.execution,
  people_facing = excluded.people_facing,
  work_hours = excluded.work_hours,
  shift_work = excluded.shift_work,
  travel = excluded.travel,
  remote_possible = excluded.remote_possible,
  degree_required = excluded.degree_required,
  license_required = excluded.license_required,
  experience_required = excluded.experience_required,
  _confidence = excluded._confidence,
  _field_confidence_json = excluded._field_confidence_json,
  evidence_json = excluded.evidence_json,
  updated_at = CURRENT_TIMESTAMP;


INSERT INTO job_attributes (
  job_id, job_name, source_system, tagger_version, status,
  wlb, growth, stability, income,
  teamwork, solo_deep, analytical, creative, execution, people_facing,
  work_hours, shift_work, travel, remote_possible,
  degree_required, license_required, experience_required,
  _confidence, _field_confidence_json, evidence_json
) VALUES (
  '1765284373931888',
  '수입업무금융사무원',
  'WORK24_DJOB',
  'tagger-v1.0.0',
  'tagged',
  65, 60, 75, 50,
  65, 35, 70, 40, 75, 60,
  'regular', 'none', 'none', 'partial',
  'bachelor', 'none', 'none',
  0.83,
  '{"wlb":0.8,"growth":0.7,"stability":0.85,"income":0.6,"teamwork":0.8,"solo_deep":0.5,"analytical":0.8,"creative":0.6,"execution":0.8,"people_facing":0.7,"degree_required":0.9,"license_required":0.8}',
  '{"wlb":"실내 사무직으로 정규 근무","growth":"수입 무역 금융으로 전문성 향상 기회 좋음","stability":"금융기관 업무로 비교적 안정적","income":"전문 금융 업무로 중상위 소득","teamwork":"신용장 개설, 서류 확인으로 협업 필요","solo_deep":"서류 심사, 계약 체결로 독립 작업","analytical":"신용장 심사, 환어음 확인으로 분석 요구","creative":"무역 금융 상품 개발로 일부 창의성","execution":"신용장 개설, 결제 실행 중심","people_facing":"무역회사 협의로 대면 업무","degree_required":"대졸 정도 학력 요구","license_required":"특별 자격증 요구 없음"}'
)
ON CONFLICT(job_id) DO UPDATE SET
  job_name = excluded.job_name,
  tagger_version = excluded.tagger_version,
  status = excluded.status,
  wlb = excluded.wlb,
  growth = excluded.growth,
  stability = excluded.stability,
  income = excluded.income,
  teamwork = excluded.teamwork,
  solo_deep = excluded.solo_deep,
  analytical = excluded.analytical,
  creative = excluded.creative,
  execution = excluded.execution,
  people_facing = excluded.people_facing,
  work_hours = excluded.work_hours,
  shift_work = excluded.shift_work,
  travel = excluded.travel,
  remote_possible = excluded.remote_possible,
  degree_required = excluded.degree_required,
  license_required = excluded.license_required,
  experience_required = excluded.experience_required,
  _confidence = excluded._confidence,
  _field_confidence_json = excluded._field_confidence_json,
  evidence_json = excluded.evidence_json,
  updated_at = CURRENT_TIMESTAMP;


INSERT INTO job_attributes (
  job_id, job_name, source_system, tagger_version, status,
  wlb, growth, stability, income,
  teamwork, solo_deep, analytical, creative, execution, people_facing,
  work_hours, shift_work, travel, remote_possible,
  degree_required, license_required, experience_required,
  _confidence, _field_confidence_json, evidence_json
) VALUES (
  '1765284374222483',
  '수출업무금융사무원',
  'WORK24_DJOB',
  'tagger-v1.0.0',
  'tagged',
  65, 60, 75, 50,
  65, 35, 70, 40, 75, 60,
  'regular', 'none', 'none', 'partial',
  'bachelor', 'none', 'none',
  0.83,
  '{"wlb":0.8,"growth":0.7,"stability":0.85,"income":0.6,"teamwork":0.8,"solo_deep":0.5,"analytical":0.8,"creative":0.6,"execution":0.8,"people_facing":0.7,"degree_required":0.9,"license_required":0.8}',
  '{"wlb":"실내 사무직으로 정규 근무","growth":"수출 무역 금융으로 전문성 향상 기회 좋음","stability":"금융기관 업무로 비교적 안정적","income":"전문 금융 업무로 중상위 소득","teamwork":"환어음 매입, 추심으로 협업 필요","solo_deep":"서류 심사, 계약 체결로 독립 작업","analytical":"환어음 심사, 신용장 확인으로 분석 요구","creative":"무역 금융 상품 개발로 일부 창의성","execution":"환어음 매입, 결제 실행 중심","people_facing":"수출회사 협의로 대면 업무","degree_required":"대졸 정도 학력 요구","license_required":"특별 자격증 요구 없음"}'
)
ON CONFLICT(job_id) DO UPDATE SET
  job_name = excluded.job_name,
  tagger_version = excluded.tagger_version,
  status = excluded.status,
  wlb = excluded.wlb,
  growth = excluded.growth,
  stability = excluded.stability,
  income = excluded.income,
  teamwork = excluded.teamwork,
  solo_deep = excluded.solo_deep,
  analytical = excluded.analytical,
  creative = excluded.creative,
  execution = excluded.execution,
  people_facing = excluded.people_facing,
  work_hours = excluded.work_hours,
  shift_work = excluded.shift_work,
  travel = excluded.travel,
  remote_possible = excluded.remote_possible,
  degree_required = excluded.degree_required,
  license_required = excluded.license_required,
  experience_required = excluded.experience_required,
  _confidence = excluded._confidence,
  _field_confidence_json = excluded._field_confidence_json,
  evidence_json = excluded.evidence_json,
  updated_at = CURRENT_TIMESTAMP;


INSERT INTO job_attributes (
  job_id, job_name, source_system, tagger_version, status,
  wlb, growth, stability, income,
  teamwork, solo_deep, analytical, creative, execution, people_facing,
  work_hours, shift_work, travel, remote_possible,
  degree_required, license_required, experience_required,
  _confidence, _field_confidence_json, evidence_json
) VALUES (
  '1765284374528141',
  '시장위험관리사무원',
  'WORK24_DJOB',
  'tagger-v1.0.0',
  'tagged',
  65, 70, 75, 60,
  60, 40, 90, 50, 65, 45,
  'regular', 'none', 'none', 'partial',
  'bachelor', 'none', 'none',
  0.78,
  '{"wlb":0.8,"growth":0.8,"stability":0.85,"income":0.7,"teamwork":0.7,"solo_deep":0.6,"analytical":0.95,"creative":0.7,"execution":0.7,"people_facing":0.6,"degree_required":0.9,"license_required":0.8}',
  '{"wlb":"실내 사무직으로 정규 근무","growth":"시장 위험 분석으로 전문성 향상 기회 매우 좋음","stability":"금융기관 업무로 비교적 안정적","income":"전문 리스크 관리로 높은 소득","teamwork":"시장 분석 공유로 협업 필요","solo_deep":"경제 지표 분석, 모델 개발로 독립 작업","analytical":"시장 동향 분석, 위험 평가로 분석 중심","creative":"리스크 관리 전략 수립으로 창의성 요구","execution":"모델 개발, 정책 수립 실행 중심","people_facing":"내부 보고, 협의로 대면 업무 적음","degree_required":"대졸 정도 학력 요구","license_required":"특별 자격증 요구 없음"}'
)
ON CONFLICT(job_id) DO UPDATE SET
  job_name = excluded.job_name,
  tagger_version = excluded.tagger_version,
  status = excluded.status,
  wlb = excluded.wlb,
  growth = excluded.growth,
  stability = excluded.stability,
  income = excluded.income,
  teamwork = excluded.teamwork,
  solo_deep = excluded.solo_deep,
  analytical = excluded.analytical,
  creative = excluded.creative,
  execution = excluded.execution,
  people_facing = excluded.people_facing,
  work_hours = excluded.work_hours,
  shift_work = excluded.shift_work,
  travel = excluded.travel,
  remote_possible = excluded.remote_possible,
  degree_required = excluded.degree_required,
  license_required = excluded.license_required,
  experience_required = excluded.experience_required,
  _confidence = excluded._confidence,
  _field_confidence_json = excluded._field_confidence_json,
  evidence_json = excluded.evidence_json,
  updated_at = CURRENT_TIMESTAMP;


INSERT INTO job_attributes (
  job_id, job_name, source_system, tagger_version, status,
  wlb, growth, stability, income,
  teamwork, solo_deep, analytical, creative, execution, people_facing,
  work_hours, shift_work, travel, remote_possible,
  degree_required, license_required, experience_required,
  _confidence, _field_confidence_json, evidence_json
) VALUES (
  '1765284374791742',
  '신용위험관리사무원',
  'WORK24_DJOB',
  'tagger-v1.0.0',
  'tagged',
  65, 65, 75, 55,
  60, 40, 85, 45, 70, 50,
  'regular', 'none', 'none', 'partial',
  'bachelor', 'none', 'none',
  0.8,
  '{"wlb":0.8,"growth":0.8,"stability":0.85,"income":0.7,"teamwork":0.7,"solo_deep":0.6,"analytical":0.95,"creative":0.6,"execution":0.8,"people_facing":0.7,"degree_required":0.9,"license_required":0.8}',
  '{"wlb":"실내 사무직으로 정규 근무","growth":"신용 위험 분석으로 전문성 향상 기회 좋음","stability":"금융기관 업무로 비교적 안정적","income":"전문 신용 관리로 상위 소득","teamwork":"신용 심사 공유로 협업 필요","solo_deep":"기업 분석, 평가로 독립 작업","analytical":"신용 조사, 위험 평가로 분석 중심","creative":"리스크 관리 전략으로 일부 창의성","execution":"심사, 보고 실행 중심","people_facing":"기업 방문, 보고로 대면 업무","degree_required":"대졸 정도 학력 요구","license_required":"특별 자격증 요구 없음"}'
)
ON CONFLICT(job_id) DO UPDATE SET
  job_name = excluded.job_name,
  tagger_version = excluded.tagger_version,
  status = excluded.status,
  wlb = excluded.wlb,
  growth = excluded.growth,
  stability = excluded.stability,
  income = excluded.income,
  teamwork = excluded.teamwork,
  solo_deep = excluded.solo_deep,
  analytical = excluded.analytical,
  creative = excluded.creative,
  execution = excluded.execution,
  people_facing = excluded.people_facing,
  work_hours = excluded.work_hours,
  shift_work = excluded.shift_work,
  travel = excluded.travel,
  remote_possible = excluded.remote_possible,
  degree_required = excluded.degree_required,
  license_required = excluded.license_required,
  experience_required = excluded.experience_required,
  _confidence = excluded._confidence,
  _field_confidence_json = excluded._field_confidence_json,
  evidence_json = excluded.evidence_json,
  updated_at = CURRENT_TIMESTAMP;


INSERT INTO job_attributes (
  job_id, job_name, source_system, tagger_version, status,
  wlb, growth, stability, income,
  teamwork, solo_deep, analytical, creative, execution, people_facing,
  work_hours, shift_work, travel, remote_possible,
  degree_required, license_required, experience_required,
  _confidence, _field_confidence_json, evidence_json
) VALUES (
  '1765284375106282',
  '신용조사담당원',
  'WORK24_DJOB',
  'tagger-v1.0.0',
  'tagged',
  60, 60, 75, 50,
  65, 35, 80, 40, 75, 70,
  'regular', 'none', 'some', 'none',
  'bachelor', 'none', 'entry',
  0.82,
  '{"wlb":0.7,"growth":0.7,"stability":0.85,"income":0.6,"teamwork":0.8,"solo_deep":0.5,"analytical":0.9,"creative":0.6,"execution":0.8,"people_facing":0.8,"degree_required":0.9,"license_required":0.8}',
  '{"wlb":"실내외 업무로 정규 근무, 현장 방문","growth":"신용 조사로 전문성 향상 기회 좋음","stability":"금융기관 업무로 비교적 안정적","income":"전문 조사 업무로 중상위 소득","teamwork":"조사 공유, 보고로 협업 필요","solo_deep":"기업 분석, 조사서 작성으로 독립 작업","analytical":"재무 분석, 신용 평가로 분석 중심","creative":"조사 방법 개발로 일부 창의성","execution":"현장 조사, 보고서 작성 실행 중심","people_facing":"기업 방문, 면접으로 대면 업무 多","degree_required":"대졸 정도 학력 요구","license_required":"특별 자격증 요구 없음"}'
)
ON CONFLICT(job_id) DO UPDATE SET
  job_name = excluded.job_name,
  tagger_version = excluded.tagger_version,
  status = excluded.status,
  wlb = excluded.wlb,
  growth = excluded.growth,
  stability = excluded.stability,
  income = excluded.income,
  teamwork = excluded.teamwork,
  solo_deep = excluded.solo_deep,
  analytical = excluded.analytical,
  creative = excluded.creative,
  execution = excluded.execution,
  people_facing = excluded.people_facing,
  work_hours = excluded.work_hours,
  shift_work = excluded.shift_work,
  travel = excluded.travel,
  remote_possible = excluded.remote_possible,
  degree_required = excluded.degree_required,
  license_required = excluded.license_required,
  experience_required = excluded.experience_required,
  _confidence = excluded._confidence,
  _field_confidence_json = excluded._field_confidence_json,
  evidence_json = excluded.evidence_json,
  updated_at = CURRENT_TIMESTAMP;


INSERT INTO job_attributes (
  job_id, job_name, source_system, tagger_version, status,
  wlb, growth, stability, income,
  teamwork, solo_deep, analytical, creative, execution, people_facing,
  work_hours, shift_work, travel, remote_possible,
  degree_required, license_required, experience_required,
  _confidence, _field_confidence_json, evidence_json
) VALUES (
  '1765284375419753',
  '신용카드고객데이터분석원',
  'WORK24_DJOB',
  'tagger-v1.0.0',
  'tagged',
  70, 65, 75, 55,
  65, 35, 85, 50, 70, 50,
  'regular', 'none', 'none', 'partial',
  'bachelor', 'none', 'entry',
  0.81,
  '{"wlb":0.8,"growth":0.8,"stability":0.85,"income":0.7,"teamwork":0.8,"solo_deep":0.5,"analytical":0.95,"creative":0.7,"execution":0.8,"people_facing":0.7,"degree_required":0.9,"license_required":0.8}',
  '{"wlb":"실내 사무직으로 정규 근무","growth":"고객 데이터 분석으로 전문성 향상 기회 좋음","stability":"카드사 업무로 비교적 안정적","income":"전문 데이터 분석으로 상위 소득","teamwork":"데이터 분석 공유로 협업 필요","solo_deep":"데이터 마이닝, 모델링으로 독립 작업","analytical":"고객 데이터 분석, 패턴 발견으로 분석 중심","creative":"CRM 전략 개발로 창의성 요구","execution":"분석 결과 적용 실행 중심","people_facing":"팀 협의, 보고로 대면 업무 적음","degree_required":"대졸 정도 학력 요구","license_required":"특별 자격증 요구 없음"}'
)
ON CONFLICT(job_id) DO UPDATE SET
  job_name = excluded.job_name,
  tagger_version = excluded.tagger_version,
  status = excluded.status,
  wlb = excluded.wlb,
  growth = excluded.growth,
  stability = excluded.stability,
  income = excluded.income,
  teamwork = excluded.teamwork,
  solo_deep = excluded.solo_deep,
  analytical = excluded.analytical,
  creative = excluded.creative,
  execution = excluded.execution,
  people_facing = excluded.people_facing,
  work_hours = excluded.work_hours,
  shift_work = excluded.shift_work,
  travel = excluded.travel,
  remote_possible = excluded.remote_possible,
  degree_required = excluded.degree_required,
  license_required = excluded.license_required,
  experience_required = excluded.experience_required,
  _confidence = excluded._confidence,
  _field_confidence_json = excluded._field_confidence_json,
  evidence_json = excluded.evidence_json,
  updated_at = CURRENT_TIMESTAMP;


INSERT INTO job_attributes (
  job_id, job_name, source_system, tagger_version, status,
  wlb, growth, stability, income,
  teamwork, solo_deep, analytical, creative, execution, people_facing,
  work_hours, shift_work, travel, remote_possible,
  degree_required, license_required, experience_required,
  _confidence, _field_confidence_json, evidence_json
) VALUES (
  '1765284375784913',
  '신용카드신사업기획원',
  'WORK24_DJOB',
  'tagger-v1.0.0',
  'tagged',
  65, 70, 75, 60,
  70, 30, 75, 65, 65, 60,
  'regular', 'none', 'none', 'partial',
  'bachelor', 'none', 'entry',
  0.8,
  '{"wlb":0.8,"growth":0.8,"stability":0.85,"income":0.7,"teamwork":0.8,"solo_deep":0.5,"analytical":0.85,"creative":0.8,"execution":0.7,"people_facing":0.7,"degree_required":0.9,"license_required":0.8}',
  '{"wlb":"실내 사무직으로 정규 근무","growth":"신사업 기획으로 전문성 향상 기회 매우 좋음","stability":"카드사 업무로 비교적 안정적","income":"전문 기획 업무로 높은 소득","teamwork":"사업 기획, 검토로 협업 多","solo_deep":"시장 조사, 기획서 작성으로 독립 작업","analytical":"시장 분석, 수익성 평가로 분석 중심","creative":"신사업 아이디어 개발로 창의성 매우 높음","execution":"사업 추진, 도입 실행 중심","people_facing":"제휴사 협의로 대면 업무","degree_required":"대졸 정도 학력 요구","license_required":"특별 자격증 요구 없음"}'
)
ON CONFLICT(job_id) DO UPDATE SET
  job_name = excluded.job_name,
  tagger_version = excluded.tagger_version,
  status = excluded.status,
  wlb = excluded.wlb,
  growth = excluded.growth,
  stability = excluded.stability,
  income = excluded.income,
  teamwork = excluded.teamwork,
  solo_deep = excluded.solo_deep,
  analytical = excluded.analytical,
  creative = excluded.creative,
  execution = excluded.execution,
  people_facing = excluded.people_facing,
  work_hours = excluded.work_hours,
  shift_work = excluded.shift_work,
  travel = excluded.travel,
  remote_possible = excluded.remote_possible,
  degree_required = excluded.degree_required,
  license_required = excluded.license_required,
  experience_required = excluded.experience_required,
  _confidence = excluded._confidence,
  _field_confidence_json = excluded._field_confidence_json,
  evidence_json = excluded.evidence_json,
  updated_at = CURRENT_TIMESTAMP;


INSERT INTO job_attributes (
  job_id, job_name, source_system, tagger_version, status,
  wlb, growth, stability, income,
  teamwork, solo_deep, analytical, creative, execution, people_facing,
  work_hours, shift_work, travel, remote_possible,
  degree_required, license_required, experience_required,
  _confidence, _field_confidence_json, evidence_json
) VALUES (
  '1765284376132973',
  '신용평가기획원',
  'WORK24_DJOB',
  'tagger-v1.0.0',
  'tagged',
  65, 70, 75, 55,
  65, 35, 85, 55, 70, 50,
  'regular', 'none', 'none', 'partial',
  'bachelor', 'none', 'none',
  0.79,
  '{"wlb":0.8,"growth":0.8,"stability":0.85,"income":0.7,"teamwork":0.8,"solo_deep":0.5,"analytical":0.95,"creative":0.7,"execution":0.8,"people_facing":0.7,"degree_required":0.9,"license_required":0.8}',
  '{"wlb":"실내 사무직으로 정규 근무","growth":"신용 평가 모델 개발로 전문성 향상 기회 매우 좋음","stability":"신용 평가 기관 업무로 비교적 안정적","income":"전문 평가 업무로 상위 소득","teamwork":"모델 개발, 평가로 협업 필요","solo_deep":"기업 분석, 모델링으로 독립 작업","analytical":"기업 재무 분석, 평가 모델링으로 분석 중심","creative":"평가 시스템 개발로 창의성 요구","execution":"평가 실시, 보고 실행 중심","people_facing":"기업 협의, 보고로 대면 업무","degree_required":"대졸 정도 학력 요구","license_required":"특별 자격증 요구 없음"}'
)
ON CONFLICT(job_id) DO UPDATE SET
  job_name = excluded.job_name,
  tagger_version = excluded.tagger_version,
  status = excluded.status,
  wlb = excluded.wlb,
  growth = excluded.growth,
  stability = excluded.stability,
  income = excluded.income,
  teamwork = excluded.teamwork,
  solo_deep = excluded.solo_deep,
  analytical = excluded.analytical,
  creative = excluded.creative,
  execution = excluded.execution,
  people_facing = excluded.people_facing,
  work_hours = excluded.work_hours,
  shift_work = excluded.shift_work,
  travel = excluded.travel,
  remote_possible = excluded.remote_possible,
  degree_required = excluded.degree_required,
  license_required = excluded.license_required,
  experience_required = excluded.experience_required,
  _confidence = excluded._confidence,
  _field_confidence_json = excluded._field_confidence_json,
  evidence_json = excluded.evidence_json,
  updated_at = CURRENT_TIMESTAMP;


INSERT INTO job_attributes (
  job_id, job_name, source_system, tagger_version, status,
  wlb, growth, stability, income,
  teamwork, solo_deep, analytical, creative, execution, people_facing,
  work_hours, shift_work, travel, remote_possible,
  degree_required, license_required, experience_required,
  _confidence, _field_confidence_json, evidence_json
) VALUES (
  '1765284376413472',
  '신탁기획원',
  'WORK24_DJOB',
  'tagger-v1.0.0',
  'tagged',
  65, 65, 75, 55,
  70, 30, 75, 55, 70, 60,
  'regular', 'none', 'none', 'partial',
  'bachelor', 'none', 'none',
  0.81,
  '{"wlb":0.8,"growth":0.8,"stability":0.85,"income":0.7,"teamwork":0.8,"solo_deep":0.5,"analytical":0.85,"creative":0.7,"execution":0.8,"people_facing":0.7,"degree_required":0.9,"license_required":0.8}',
  '{"wlb":"실내 사무직으로 정규 근무","growth":"신탁 상품 기획으로 전문성 향상 기회 좋음","stability":"금융기관 업무로 비교적 안정적","income":"전문 기획 업무로 상위 소득","teamwork":"상품 개발, 제도 개선으로 협업 多","solo_deep":"시장 조사, 상품 개발로 독립 작업","analytical":"시장 분석, 상품 평가로 분석 중심","creative":"신탁 상품 개발로 창의성 높음","execution":"제도 개선, 상품 개발 실행 중심","people_facing":"영업점 지도, 고객 분석으로 대면 업무","degree_required":"대졸 정도 학력 요구","license_required":"특별 자격증 요구 없음"}'
)
ON CONFLICT(job_id) DO UPDATE SET
  job_name = excluded.job_name,
  tagger_version = excluded.tagger_version,
  status = excluded.status,
  wlb = excluded.wlb,
  growth = excluded.growth,
  stability = excluded.stability,
  income = excluded.income,
  teamwork = excluded.teamwork,
  solo_deep = excluded.solo_deep,
  analytical = excluded.analytical,
  creative = excluded.creative,
  execution = excluded.execution,
  people_facing = excluded.people_facing,
  work_hours = excluded.work_hours,
  shift_work = excluded.shift_work,
  travel = excluded.travel,
  remote_possible = excluded.remote_possible,
  degree_required = excluded.degree_required,
  license_required = excluded.license_required,
  experience_required = excluded.experience_required,
  _confidence = excluded._confidence,
  _field_confidence_json = excluded._field_confidence_json,
  evidence_json = excluded.evidence_json,
  updated_at = CURRENT_TIMESTAMP;


INSERT INTO job_attributes (
  job_id, job_name, source_system, tagger_version, status,
  wlb, growth, stability, income,
  teamwork, solo_deep, analytical, creative, execution, people_facing,
  work_hours, shift_work, travel, remote_possible,
  degree_required, license_required, experience_required,
  _confidence, _field_confidence_json, evidence_json
) VALUES (
  '1765284376823908',
  '신탁대출사무원',
  'WORK24_DJOB',
  'tagger-v1.0.0',
  'tagged',
  65, 50, 80, 45,
  65, 35, 70, 35, 75, 70,
  'regular', 'none', 'none', 'none',
  'bachelor', 'none', 'entry',
  0.84,
  '{"wlb":0.8,"growth":0.6,"stability":0.9,"income":0.6,"teamwork":0.8,"solo_deep":0.5,"analytical":0.8,"creative":0.6,"execution":0.8,"people_facing":0.8,"degree_required":0.9,"license_required":0.8}',
  '{"wlb":"실내 사무직으로 정규 근무","growth":"신탁 대출 업무로 일부 성장 기회","stability":"금융기관 업무로 안정적","income":"사무직으로 중간 수준 소득","teamwork":"대출 심사, 실행으로 협업 필요","solo_deep":"서류 검토, 계약 체결로 독립 작업","analytical":"신용 평가, 대출 심사로 분석 요구","creative":"대출 상품 개발로 일부 창의성","execution":"대출 실행, 관리 중심","people_facing":"고객 상담, 담보 취득으로 대면 업무 多","degree_required":"대졸 정도 학력 요구","license_required":"특별 자격증 요구 없음"}'
)
ON CONFLICT(job_id) DO UPDATE SET
  job_name = excluded.job_name,
  tagger_version = excluded.tagger_version,
  status = excluded.status,
  wlb = excluded.wlb,
  growth = excluded.growth,
  stability = excluded.stability,
  income = excluded.income,
  teamwork = excluded.teamwork,
  solo_deep = excluded.solo_deep,
  analytical = excluded.analytical,
  creative = excluded.creative,
  execution = excluded.execution,
  people_facing = excluded.people_facing,
  work_hours = excluded.work_hours,
  shift_work = excluded.shift_work,
  travel = excluded.travel,
  remote_possible = excluded.remote_possible,
  degree_required = excluded.degree_required,
  license_required = excluded.license_required,
  experience_required = excluded.experience_required,
  _confidence = excluded._confidence,
  _field_confidence_json = excluded._field_confidence_json,
  evidence_json = excluded.evidence_json,
  updated_at = CURRENT_TIMESTAMP;

COMMIT;