-- Batch tagging SQL generated at 2026-01-06T10:45:00.217Z
-- Tagger version: tagger-v1.0.0
-- Total jobs: 23

BEGIN TRANSACTION;


INSERT INTO job_attributes (
  job_id, job_name, source_system, tagger_version, status,
  wlb, growth, stability, income,
  teamwork, solo_deep, analytical, creative, execution, people_facing,
  work_hours, shift_work, travel, remote_possible,
  degree_required, license_required, experience_required,
  _confidence, _field_confidence_json, evidence_json
) VALUES (
  '1765285617470422',
  '어업단순노무자',
  'WORK24_DJOB',
  'tagger-v1.0.0',
  'tagged',
  45, 35, 70, 50,
  80, 30, 40, 30, 70, 75,
  'regular', 'possible', 'none', 'none',
  'none', 'none', 'entry',
  0.68,
  '{"wlb":0.5,"growth":0.5,"stability":0.8,"income":0.6,"teamwork":0.9,"solo_deep":0.4,"analytical":0.5,"creative":0.4,"execution":0.8,"people_facing":0.9,"degree_required":0.9,"license_required":0.9}',
  '{"wlb":"해상 작업으로 야근 가능, 교대 근무 가능, 출장 없음","growth":"어업 산업 기술 발전 기회 낮음","stability":"계절성 강한 일용직으로 고용 안정성 보통","income":"단순 노무로 하위 소득","teamwork":"어업 작업 협업 매우 중요","solo_deep":"청소, 채취 작업으로 독립 작업 少","analytical":"작업 상태 확인으로 분석 낮음","creative":"반복 작업으로 창의성 낮음","execution":"어업 보조 실행 중심","people_facing":"어업종사원 협업 매우 多","degree_required":"고졸 정도 학력 요구","license_required":"특별 자격증 불필요"}'
)
ON CONFLICT(job_id) DO UPDATE SET
  job_name = excluded.job_name,
  tagger_version = excluded.tagger_version,
  status = excluded.status,
  wlb = excluded.wlb,
  growth = excluded.growth,
  stability = excluded.stability,
  income = excluded.income,
  teamwork = excluded.teamwork,
  solo_deep = excluded.solo_deep,
  analytical = excluded.analytical,
  creative = excluded.creative,
  execution = excluded.execution,
  people_facing = excluded.people_facing,
  work_hours = excluded.work_hours,
  shift_work = excluded.shift_work,
  travel = excluded.travel,
  remote_possible = excluded.remote_possible,
  degree_required = excluded.degree_required,
  license_required = excluded.license_required,
  experience_required = excluded.experience_required,
  _confidence = excluded._confidence,
  _field_confidence_json = excluded._field_confidence_json,
  evidence_json = excluded.evidence_json,
  updated_at = CURRENT_TIMESTAMP;


INSERT INTO job_attributes (
  job_id, job_name, source_system, tagger_version, status,
  wlb, growth, stability, income,
  teamwork, solo_deep, analytical, creative, execution, people_facing,
  work_hours, shift_work, travel, remote_possible,
  degree_required, license_required, experience_required,
  _confidence, _field_confidence_json, evidence_json
) VALUES (
  '1765285617820366',
  '임업단순노무자',
  'WORK24_DJOB',
  'tagger-v1.0.0',
  'tagged',
  40, 35, 70, 50,
  85, 35, 45, 35, 75, 80,
  'regular', 'none', 'none', 'none',
  'none', 'none', 'entry',
  0.68,
  '{"wlb":0.45,"growth":0.5,"stability":0.8,"income":0.6,"teamwork":0.95,"solo_deep":0.5,"analytical":0.6,"creative":0.5,"execution":0.85,"people_facing":0.95,"degree_required":0.9,"license_required":0.9}',
  '{"wlb":"산림 작업으로 야근 가능, 교대 근무 없음, 출장 가능","growth":"임업 산업 기술 발전 기회 낮음","stability":"계절성 강한 일용직으로 고용 안정성 보통","income":"단순 노무로 하위 소득","teamwork":"임업 작업 협업 매우 중요","solo_deep":"나무 정리, 운반 작업으로 독립 작업 少","analytical":"작업 상태 확인으로 분석 보통","creative":"반복 작업으로 창의성 낮음","execution":"임업 보조 실행 중심","people_facing":"임업종사원 협업 매우 多","degree_required":"고졸 정도 학력 요구","license_required":"특별 자격증 불필요"}'
)
ON CONFLICT(job_id) DO UPDATE SET
  job_name = excluded.job_name,
  tagger_version = excluded.tagger_version,
  status = excluded.status,
  wlb = excluded.wlb,
  growth = excluded.growth,
  stability = excluded.stability,
  income = excluded.income,
  teamwork = excluded.teamwork,
  solo_deep = excluded.solo_deep,
  analytical = excluded.analytical,
  creative = excluded.creative,
  execution = excluded.execution,
  people_facing = excluded.people_facing,
  work_hours = excluded.work_hours,
  shift_work = excluded.shift_work,
  travel = excluded.travel,
  remote_possible = excluded.remote_possible,
  degree_required = excluded.degree_required,
  license_required = excluded.license_required,
  experience_required = excluded.experience_required,
  _confidence = excluded._confidence,
  _field_confidence_json = excluded._field_confidence_json,
  evidence_json = excluded.evidence_json,
  updated_at = CURRENT_TIMESTAMP;


INSERT INTO job_attributes (
  job_id, job_name, source_system, tagger_version, status,
  wlb, growth, stability, income,
  teamwork, solo_deep, analytical, creative, execution, people_facing,
  work_hours, shift_work, travel, remote_possible,
  degree_required, license_required, experience_required,
  _confidence, _field_confidence_json, evidence_json
) VALUES (
  '1765285618170310',
  '검침사무원',
  'WORK24_DJOB',
  'tagger-v1.0.0',
  'tagged',
  75, 45, 80, 65,
  70, 60, 75, 45, 70, 75,
  'regular', 'none', 'none', 'none',
  'none', 'none', 'none',
  0.74,
  '{"wlb":0.85,"growth":0.65,"stability":0.9,"income":0.8,"teamwork":0.8,"solo_deep":0.8,"analytical":0.9,"creative":0.7,"execution":0.8,"people_facing":0.9,"degree_required":0.9,"license_required":0.9}',
  '{"wlb":"사무실 작업으로 야근 적고 교대 근무 없음, 출장 없음","growth":"에너지 산업 기술 발전 기회 보통","stability":"공공사업으로 고용 안정성 매우 좋음","income":"사무 작업으로 상위 소득","teamwork":"데이터 관리 협업 요구","solo_deep":"검침 데이터 분석, 정리 작업으로 독립 작업 多","analytical":"사용량 분석, 패턴 파악으로 분석 매우 중요","creative":"보고서 작성 최적화로 창의성 보통","execution":"검침 사무 실행 중심","people_facing":"내부 협업 업무","degree_required":"고졸 정도 학력 요구","license_required":"특별 자격증 불필요"}'
)
ON CONFLICT(job_id) DO UPDATE SET
  job_name = excluded.job_name,
  tagger_version = excluded.tagger_version,
  status = excluded.status,
  wlb = excluded.wlb,
  growth = excluded.growth,
  stability = excluded.stability,
  income = excluded.income,
  teamwork = excluded.teamwork,
  solo_deep = excluded.solo_deep,
  analytical = excluded.analytical,
  creative = excluded.creative,
  execution = excluded.execution,
  people_facing = excluded.people_facing,
  work_hours = excluded.work_hours,
  shift_work = excluded.shift_work,
  travel = excluded.travel,
  remote_possible = excluded.remote_possible,
  degree_required = excluded.degree_required,
  license_required = excluded.license_required,
  experience_required = excluded.experience_required,
  _confidence = excluded._confidence,
  _field_confidence_json = excluded._field_confidence_json,
  evidence_json = excluded.evidence_json,
  updated_at = CURRENT_TIMESTAMP;


INSERT INTO job_attributes (
  job_id, job_name, source_system, tagger_version, status,
  wlb, growth, stability, income,
  teamwork, solo_deep, analytical, creative, execution, people_facing,
  work_hours, shift_work, travel, remote_possible,
  degree_required, license_required, experience_required,
  _confidence, _field_confidence_json, evidence_json
) VALUES (
  '1765285618520254',
  '검침원',
  'WORK24_DJOB',
  'tagger-v1.0.0',
  'tagged',
  65, 40, 80, 70,
  65, 60, 70, 40, 75, 80,
  'regular', 'none', 'none', 'none',
  'none', 'none', 'none',
  0.73,
  '{"wlb":0.75,"growth":0.6,"stability":0.9,"income":0.85,"teamwork":0.75,"solo_deep":0.8,"analytical":0.85,"creative":0.6,"execution":0.85,"people_facing":0.95,"degree_required":0.9,"license_required":0.9}',
  '{"wlb":"현장 방문으로 야근 가능, 교대 근무 없음, 출장 가능","growth":"에너지 산업 기술 발전 기회 낮음","stability":"공공사업으로 고용 안정성 매우 좋음","income":"현장 방문으로 상위 소득","teamwork":"독립 작업 중심","solo_deep":"계량기 확인, 기록 작업으로 독립 작업 多","analytical":"사용량 측정, 이상 감지로 분석 중요","creative":"최적 경로 계획으로 창의성 보통","execution":"검침 실행 중심","people_facing":"고객 응대 매우 多","degree_required":"고졸 정도 학력 요구","license_required":"특별 자격증 불필요"}'
)
ON CONFLICT(job_id) DO UPDATE SET
  job_name = excluded.job_name,
  tagger_version = excluded.tagger_version,
  status = excluded.status,
  wlb = excluded.wlb,
  growth = excluded.growth,
  stability = excluded.stability,
  income = excluded.income,
  teamwork = excluded.teamwork,
  solo_deep = excluded.solo_deep,
  analytical = excluded.analytical,
  creative = excluded.creative,
  execution = excluded.execution,
  people_facing = excluded.people_facing,
  work_hours = excluded.work_hours,
  shift_work = excluded.shift_work,
  travel = excluded.travel,
  remote_possible = excluded.remote_possible,
  degree_required = excluded.degree_required,
  license_required = excluded.license_required,
  experience_required = excluded.experience_required,
  _confidence = excluded._confidence,
  _field_confidence_json = excluded._field_confidence_json,
  evidence_json = excluded.evidence_json,
  updated_at = CURRENT_TIMESTAMP;


INSERT INTO job_attributes (
  job_id, job_name, source_system, tagger_version, status,
  wlb, growth, stability, income,
  teamwork, solo_deep, analytical, creative, execution, people_facing,
  work_hours, shift_work, travel, remote_possible,
  degree_required, license_required, experience_required,
  _confidence, _field_confidence_json, evidence_json
) VALUES (
  '1765285618870198',
  '자동판매기관리원',
  'WORK24_DJOB',
  'tagger-v1.0.0',
  'tagged',
  70, 50, 75, 70,
  65, 65, 75, 55, 80, 75,
  'regular', 'possible', 'none', 'none',
  'none', 'none', 'none',
  0.74,
  '{"wlb":0.8,"growth":0.7,"stability":0.85,"income":0.85,"teamwork":0.75,"solo_deep":0.85,"analytical":0.9,"creative":0.75,"execution":0.9,"people_facing":0.9,"degree_required":0.9,"license_required":0.9}',
  '{"wlb":"현장 방문으로 야근 가능, 교대 근무 가능, 출장 가능","growth":"유통 산업 기술 발전 기회 보통","stability":"제조업으로 고용 안정성 좋음","income":"관리 작업으로 상위 소득","teamwork":"독립 작업 중심","solo_deep":"기기 점검, 재고 관리 작업으로 독립 작업 多","analytical":"판매 데이터 분석, 고장 진단으로 분석 매우 중요","creative":"배치 최적화, 재고 전략으로 창의성 높음","execution":"자동판매기 관리 실행 중심","people_facing":"기기 설치장소 고객 응대 업무","degree_required":"고졸 정도 학력 요구","license_required":"특별 자격증 불필요"}'
)
ON CONFLICT(job_id) DO UPDATE SET
  job_name = excluded.job_name,
  tagger_version = excluded.tagger_version,
  status = excluded.status,
  wlb = excluded.wlb,
  growth = excluded.growth,
  stability = excluded.stability,
  income = excluded.income,
  teamwork = excluded.teamwork,
  solo_deep = excluded.solo_deep,
  analytical = excluded.analytical,
  creative = excluded.creative,
  execution = excluded.execution,
  people_facing = excluded.people_facing,
  work_hours = excluded.work_hours,
  shift_work = excluded.shift_work,
  travel = excluded.travel,
  remote_possible = excluded.remote_possible,
  degree_required = excluded.degree_required,
  license_required = excluded.license_required,
  experience_required = excluded.experience_required,
  _confidence = excluded._confidence,
  _field_confidence_json = excluded._field_confidence_json,
  evidence_json = excluded.evidence_json,
  updated_at = CURRENT_TIMESTAMP;


INSERT INTO job_attributes (
  job_id, job_name, source_system, tagger_version, status,
  wlb, growth, stability, income,
  teamwork, solo_deep, analytical, creative, execution, people_facing,
  work_hours, shift_work, travel, remote_possible,
  degree_required, license_required, experience_required,
  _confidence, _field_confidence_json, evidence_json
) VALUES (
  '1765285619220142',
  '주정차계도원',
  'WORK24_DJOB',
  'tagger-v1.0.0',
  'tagged',
  60, 45, 85, 70,
  75, 55, 70, 45, 80, 90,
  'regular', 'possible', 'none', 'none',
  'none', 'none', 'none',
  0.74,
  '{"wlb":0.7,"growth":0.65,"stability":0.95,"income":0.85,"teamwork":0.85,"solo_deep":0.75,"analytical":0.85,"creative":0.7,"execution":0.9,"people_facing":0.98,"degree_required":0.9,"license_required":0.9}',
  '{"wlb":"야외 근무로 야근 가능, 교대 근무 가능, 출장 없음","growth":"교통 산업 기술 발전 기회 보통","stability":"공공사업으로 고용 안정성 매우 높음","income":"계도 작업으로 상위 소득","teamwork":"계도 작업 협업 중요","solo_deep":"차량 상태 확인, 계도 결정 작업으로 독립 작업 多","analytical":"주정차 위반 판단, 상황 분석으로 분석 중요","creative":"계도 방법 최적화로 창의성 보통","execution":"주정차 계도 실행 중심","people_facing":"운전자 계도 매우 多","degree_required":"고졸 정도 학력 요구","license_required":"특별 자격증 불필요"}'
)
ON CONFLICT(job_id) DO UPDATE SET
  job_name = excluded.job_name,
  tagger_version = excluded.tagger_version,
  status = excluded.status,
  wlb = excluded.wlb,
  growth = excluded.growth,
  stability = excluded.stability,
  income = excluded.income,
  teamwork = excluded.teamwork,
  solo_deep = excluded.solo_deep,
  analytical = excluded.analytical,
  creative = excluded.creative,
  execution = excluded.execution,
  people_facing = excluded.people_facing,
  work_hours = excluded.work_hours,
  shift_work = excluded.shift_work,
  travel = excluded.travel,
  remote_possible = excluded.remote_possible,
  degree_required = excluded.degree_required,
  license_required = excluded.license_required,
  experience_required = excluded.experience_required,
  _confidence = excluded._confidence,
  _field_confidence_json = excluded._field_confidence_json,
  evidence_json = excluded.evidence_json,
  updated_at = CURRENT_TIMESTAMP;


INSERT INTO job_attributes (
  job_id, job_name, source_system, tagger_version, status,
  wlb, growth, stability, income,
  teamwork, solo_deep, analytical, creative, execution, people_facing,
  work_hours, shift_work, travel, remote_possible,
  degree_required, license_required, experience_required,
  _confidence, _field_confidence_json, evidence_json
) VALUES (
  '1765285619570086',
  '주차장관리원',
  'WORK24_DJOB',
  'tagger-v1.0.0',
  'tagged',
  65, 40, 80, 65,
  75, 50, 65, 45, 75, 85,
  'regular', 'possible', 'none', 'none',
  'none', 'none', 'none',
  0.73,
  '{"wlb":0.75,"growth":0.6,"stability":0.9,"income":0.8,"teamwork":0.85,"solo_deep":0.7,"analytical":0.8,"creative":0.7,"execution":0.85,"people_facing":0.95,"degree_required":0.9,"license_required":0.9}',
  '{"wlb":"주차장 근무로 야근 가능, 교대 근무 가능, 출장 없음","growth":"서비스 산업 기술 발전 기회 낮음","stability":"공공사업으로 고용 안정성 매우 좋음","income":"관리 작업으로 상위 소득","teamwork":"관리 작업 협업 중요","solo_deep":"주차 안내, 요금 정산 작업으로 독립 작업 多","analytical":"주차 상황 판단, 요금 계산으로 분석 중요","creative":"주차 안내 최적화로 창의성 보통","execution":"주차장 관리 실행 중심","people_facing":"운전자 안내 매우 多","degree_required":"고졸 정도 학력 요구","license_required":"특별 자격증 불필요"}'
)
ON CONFLICT(job_id) DO UPDATE SET
  job_name = excluded.job_name,
  tagger_version = excluded.tagger_version,
  status = excluded.status,
  wlb = excluded.wlb,
  growth = excluded.growth,
  stability = excluded.stability,
  income = excluded.income,
  teamwork = excluded.teamwork,
  solo_deep = excluded.solo_deep,
  analytical = excluded.analytical,
  creative = excluded.creative,
  execution = excluded.execution,
  people_facing = excluded.people_facing,
  work_hours = excluded.work_hours,
  shift_work = excluded.shift_work,
  travel = excluded.travel,
  remote_possible = excluded.remote_possible,
  degree_required = excluded.degree_required,
  license_required = excluded.license_required,
  experience_required = excluded.experience_required,
  _confidence = excluded._confidence,
  _field_confidence_json = excluded._field_confidence_json,
  evidence_json = excluded.evidence_json,
  updated_at = CURRENT_TIMESTAMP;


INSERT INTO job_attributes (
  job_id, job_name, source_system, tagger_version, status,
  wlb, growth, stability, income,
  teamwork, solo_deep, analytical, creative, execution, people_facing,
  work_hours, shift_work, travel, remote_possible,
  degree_required, license_required, experience_required,
  _confidence, _field_confidence_json, evidence_json
) VALUES (
  '1765285619920030',
  '구두미화원',
  'WORK24_DJOB',
  'tagger-v1.0.0',
  'tagged',
  70, 40, 75, 60,
  75, 45, 55, 50, 70, 85,
  'regular', 'possible', 'none', 'none',
  'none', 'none', 'entry',
  0.72,
  '{"wlb":0.8,"growth":0.6,"stability":0.85,"income":0.75,"teamwork":0.85,"solo_deep":0.65,"analytical":0.75,"creative":0.7,"execution":0.8,"people_facing":0.95,"degree_required":0.9,"license_required":0.9}',
  '{"wlb":"구두 수선으로 야근 가능, 교대 근무 가능, 출장 없음","growth":"서비스 산업 기술 발전 기회 낮음","stability":"자영업 성격으로 고용 안정성 좋음","income":"수선 서비스로 중위 소득","teamwork":"수선 작업 협업 중요","solo_deep":"구두 상태 진단, 수선 작업으로 독립 작업 多","analytical":"구두 손상 분석으로 분석 높음","creative":"수선 방법 창의성 보통","execution":"구두 미화 실행 중심","people_facing":"고객 상담 매우 多","degree_required":"고졸 정도 학력 요구","license_required":"특별 자격증 불필요"}'
)
ON CONFLICT(job_id) DO UPDATE SET
  job_name = excluded.job_name,
  tagger_version = excluded.tagger_version,
  status = excluded.status,
  wlb = excluded.wlb,
  growth = excluded.growth,
  stability = excluded.stability,
  income = excluded.income,
  teamwork = excluded.teamwork,
  solo_deep = excluded.solo_deep,
  analytical = excluded.analytical,
  creative = excluded.creative,
  execution = excluded.execution,
  people_facing = excluded.people_facing,
  work_hours = excluded.work_hours,
  shift_work = excluded.shift_work,
  travel = excluded.travel,
  remote_possible = excluded.remote_possible,
  degree_required = excluded.degree_required,
  license_required = excluded.license_required,
  experience_required = excluded.experience_required,
  _confidence = excluded._confidence,
  _field_confidence_json = excluded._field_confidence_json,
  evidence_json = excluded.evidence_json,
  updated_at = CURRENT_TIMESTAMP;


INSERT INTO job_attributes (
  job_id, job_name, source_system, tagger_version, status,
  wlb, growth, stability, income,
  teamwork, solo_deep, analytical, creative, execution, people_facing,
  work_hours, shift_work, travel, remote_possible,
  degree_required, license_required, experience_required,
  _confidence, _field_confidence_json, evidence_json
) VALUES (
  '1765285620279974',
  '세탁물접수원',
  'WORK24_DJOB',
  'tagger-v1.0.0',
  'tagged',
  70, 40, 75, 60,
  80, 50, 65, 45, 75, 90,
  'regular', 'possible', 'none', 'none',
  'none', 'none', 'none',
  0.73,
  '{"wlb":0.8,"growth":0.6,"stability":0.85,"income":0.75,"teamwork":0.9,"solo_deep":0.7,"analytical":0.8,"creative":0.7,"execution":0.85,"people_facing":0.98,"degree_required":0.9,"license_required":0.9}',
  '{"wlb":"세탁소 근무로 야근 가능, 교대 근무 가능, 출장 없음","growth":"서비스 산업 기술 발전 기회 낮음","stability":"제조업으로 고용 안정성 좋음","income":"접수 작업으로 중위 소득","teamwork":"접수 작업 협업 중요","solo_deep":"세탁물 분류, 접수 기록 작업으로 독립 작업 多","analytical":"세탁물 상태, 서비스 분류로 분석 중요","creative":"서비스 최적화로 창의성 보통","execution":"세탁물 접수 실행 중심","people_facing":"고객 응대 매우 多","degree_required":"고졸 정도 학력 요구","license_required":"특별 자격증 불필요"}'
)
ON CONFLICT(job_id) DO UPDATE SET
  job_name = excluded.job_name,
  tagger_version = excluded.tagger_version,
  status = excluded.status,
  wlb = excluded.wlb,
  growth = excluded.growth,
  stability = excluded.stability,
  income = excluded.income,
  teamwork = excluded.teamwork,
  solo_deep = excluded.solo_deep,
  analytical = excluded.analytical,
  creative = excluded.creative,
  execution = excluded.execution,
  people_facing = excluded.people_facing,
  work_hours = excluded.work_hours,
  shift_work = excluded.shift_work,
  travel = excluded.travel,
  remote_possible = excluded.remote_possible,
  degree_required = excluded.degree_required,
  license_required = excluded.license_required,
  experience_required = excluded.experience_required,
  _confidence = excluded._confidence,
  _field_confidence_json = excluded._field_confidence_json,
  evidence_json = excluded.evidence_json,
  updated_at = CURRENT_TIMESTAMP;


INSERT INTO job_attributes (
  job_id, job_name, source_system, tagger_version, status,
  wlb, growth, stability, income,
  teamwork, solo_deep, analytical, creative, execution, people_facing,
  work_hours, shift_work, travel, remote_possible,
  degree_required, license_required, experience_required,
  _confidence, _field_confidence_json, evidence_json
) VALUES (
  '1765285620629918',
  '세탁보조원',
  'WORK24_DJOB',
  'tagger-v1.0.0',
  'tagged',
  65, 40, 75, 60,
  85, 45, 55, 40, 75, 80,
  'regular', 'possible', 'none', 'none',
  'none', 'none', 'entry',
  0.72,
  '{"wlb":0.75,"growth":0.6,"stability":0.85,"income":0.75,"teamwork":0.95,"solo_deep":0.65,"analytical":0.75,"creative":0.6,"execution":0.85,"people_facing":0.95,"degree_required":0.9,"license_required":0.9}',
  '{"wlb":"세탁 작업으로 야근 가능, 교대 근무 가능, 출장 없음","growth":"서비스 산업 기술 발전 기회 낮음","stability":"제조업으로 고용 안정성 좋음","income":"보조 작업으로 중위 소득","teamwork":"세탁 작업 협업 매우 중요","solo_deep":"세탁물 준비, 정리 작업으로 독립 작업 多","analytical":"세탁물 상태 확인으로 분석 높음","creative":"세탁 방법 최적화로 창의성 보통","execution":"세탁 보조 실행 중심","people_facing":"팀 협업 매우 多","degree_required":"고졸 정도 학력 요구","license_required":"특별 자격증 불필요"}'
)
ON CONFLICT(job_id) DO UPDATE SET
  job_name = excluded.job_name,
  tagger_version = excluded.tagger_version,
  status = excluded.status,
  wlb = excluded.wlb,
  growth = excluded.growth,
  stability = excluded.stability,
  income = excluded.income,
  teamwork = excluded.teamwork,
  solo_deep = excluded.solo_deep,
  analytical = excluded.analytical,
  creative = excluded.creative,
  execution = excluded.execution,
  people_facing = excluded.people_facing,
  work_hours = excluded.work_hours,
  shift_work = excluded.shift_work,
  travel = excluded.travel,
  remote_possible = excluded.remote_possible,
  degree_required = excluded.degree_required,
  license_required = excluded.license_required,
  experience_required = excluded.experience_required,
  _confidence = excluded._confidence,
  _field_confidence_json = excluded._field_confidence_json,
  evidence_json = excluded.evidence_json,
  updated_at = CURRENT_TIMESTAMP;


INSERT INTO job_attributes (
  job_id, job_name, source_system, tagger_version, status,
  wlb, growth, stability, income,
  teamwork, solo_deep, analytical, creative, execution, people_facing,
  work_hours, shift_work, travel, remote_possible,
  degree_required, license_required, experience_required,
  _confidence, _field_confidence_json, evidence_json
) VALUES (
  '1765285620979862',
  '덤프트럭운전원',
  'WORK24_DJOB',
  'tagger-v1.0.0',
  'tagged',
  50, 45, 75, 75,
  75, 60, 70, 45, 85, 70,
  'regular', 'possible', 'none', 'none',
  'none', 'required', 'none',
  0.74,
  '{"wlb":0.6,"growth":0.65,"stability":0.85,"income":0.9,"teamwork":0.85,"solo_deep":0.8,"analytical":0.85,"creative":0.7,"execution":0.95,"people_facing":0.8,"degree_required":0.9,"license_required":0.9}',
  '{"wlb":"화물 운송으로 야근 가능, 교대 근무 가능, 출장 가능","growth":"운송 산업 기술 발전 기회 보통","stability":"제조업으로 고용 안정성 좋음","income":"덤프트럭 운전으로 상위 소득","teamwork":"운송 작업 협업 중요","solo_deep":"경로 계획, 화물 관리 작업으로 독립 작업 多","analytical":"화물 무게, 경로로 분석 중요","creative":"운송 최적화로 창의성 보통","execution":"덤프트럭 운전 실행 중심","people_facing":"화물 관련자 응대 업무","degree_required":"고졸 정도 학력 요구","license_required":"운전면허 필수"}'
)
ON CONFLICT(job_id) DO UPDATE SET
  job_name = excluded.job_name,
  tagger_version = excluded.tagger_version,
  status = excluded.status,
  wlb = excluded.wlb,
  growth = excluded.growth,
  stability = excluded.stability,
  income = excluded.income,
  teamwork = excluded.teamwork,
  solo_deep = excluded.solo_deep,
  analytical = excluded.analytical,
  creative = excluded.creative,
  execution = excluded.execution,
  people_facing = excluded.people_facing,
  work_hours = excluded.work_hours,
  shift_work = excluded.shift_work,
  travel = excluded.travel,
  remote_possible = excluded.remote_possible,
  degree_required = excluded.degree_required,
  license_required = excluded.license_required,
  experience_required = excluded.experience_required,
  _confidence = excluded._confidence,
  _field_confidence_json = excluded._field_confidence_json,
  evidence_json = excluded.evidence_json,
  updated_at = CURRENT_TIMESTAMP;


INSERT INTO job_attributes (
  job_id, job_name, source_system, tagger_version, status,
  wlb, growth, stability, income,
  teamwork, solo_deep, analytical, creative, execution, people_facing,
  work_hours, shift_work, travel, remote_possible,
  degree_required, license_required, experience_required,
  _confidence, _field_confidence_json, evidence_json
) VALUES (
  '1765285621329806',
  '호텔세탁원',
  'WORK24_DJOB',
  'tagger-v1.0.0',
  'tagged',
  65, 40, 80, 65,
  80, 50, 60, 45, 75, 75,
  'regular', 'possible', 'none', 'none',
  'none', 'none', 'none',
  0.73,
  '{"wlb":0.75,"growth":0.6,"stability":0.9,"income":0.8,"teamwork":0.9,"solo_deep":0.7,"analytical":0.8,"creative":0.7,"execution":0.85,"people_facing":0.9,"degree_required":0.9,"license_required":0.9}',
  '{"wlb":"호텔 세탁으로 야근 가능, 교대 근무 가능, 출장 없음","growth":"호텔 산업 기술 발전 기회 낮음","stability":"호텔업으로 고용 안정성 매우 좋음","income":"세탁 작업으로 상위 소득","teamwork":"세탁 작업 협업 중요","solo_deep":"세탁물 분류, 세탁 작업으로 독립 작업 多","analytical":"세탁물 상태, 세탁 방법으로 분석 높음","creative":"세탁 최적화로 창의성 보통","execution":"호텔 세탁 실행 중심","people_facing":"팀 협업 업무","degree_required":"고졸 정도 학력 요구","license_required":"특별 자격증 불필요"}'
)
ON CONFLICT(job_id) DO UPDATE SET
  job_name = excluded.job_name,
  tagger_version = excluded.tagger_version,
  status = excluded.status,
  wlb = excluded.wlb,
  growth = excluded.growth,
  stability = excluded.stability,
  income = excluded.income,
  teamwork = excluded.teamwork,
  solo_deep = excluded.solo_deep,
  analytical = excluded.analytical,
  creative = excluded.creative,
  execution = excluded.execution,
  people_facing = excluded.people_facing,
  work_hours = excluded.work_hours,
  shift_work = excluded.shift_work,
  travel = excluded.travel,
  remote_possible = excluded.remote_possible,
  degree_required = excluded.degree_required,
  license_required = excluded.license_required,
  experience_required = excluded.experience_required,
  _confidence = excluded._confidence,
  _field_confidence_json = excluded._field_confidence_json,
  evidence_json = excluded.evidence_json,
  updated_at = CURRENT_TIMESTAMP;


INSERT INTO job_attributes (
  job_id, job_name, source_system, tagger_version, status,
  wlb, growth, stability, income,
  teamwork, solo_deep, analytical, creative, execution, people_facing,
  work_hours, shift_work, travel, remote_possible,
  degree_required, license_required, experience_required,
  _confidence, _field_confidence_json, evidence_json
) VALUES (
  '1765285621679750',
  '등하교교통안전원',
  'WORK24_DJOB',
  'tagger-v1.0.0',
  'tagged',
  70, 40, 85, 65,
  75, 50, 60, 40, 75, 90,
  'regular', 'none', 'none', 'none',
  'none', 'none', 'none',
  0.73,
  '{"wlb":0.8,"growth":0.6,"stability":0.95,"income":0.8,"teamwork":0.85,"solo_deep":0.7,"analytical":0.8,"creative":0.6,"execution":0.85,"people_facing":0.98,"degree_required":0.9,"license_required":0.9}',
  '{"wlb":"학교 주변으로 야근 적고 교대 근무 없음, 출장 없음","growth":"교육 산업 기술 발전 기회 낮음","stability":"공공사업으로 고용 안정성 매우 높음","income":"안전 지도로 상위 소득","teamwork":"안전 지도 협업 중요","solo_deep":"교통 상황 모니터링, 지도 작업으로 독립 작업 多","analytical":"위험 상황 판단으로 분석 높음","creative":"안전 지도 방법 최적화로 창의성 보통","execution":"등하교 교통 안전 실행 중심","people_facing":"학생/학부모 안내 매우 多","degree_required":"고졸 정도 학력 요구","license_required":"특별 자격증 불필요"}'
)
ON CONFLICT(job_id) DO UPDATE SET
  job_name = excluded.job_name,
  tagger_version = excluded.tagger_version,
  status = excluded.status,
  wlb = excluded.wlb,
  growth = excluded.growth,
  stability = excluded.stability,
  income = excluded.income,
  teamwork = excluded.teamwork,
  solo_deep = excluded.solo_deep,
  analytical = excluded.analytical,
  creative = excluded.creative,
  execution = excluded.execution,
  people_facing = excluded.people_facing,
  work_hours = excluded.work_hours,
  shift_work = excluded.shift_work,
  travel = excluded.travel,
  remote_possible = excluded.remote_possible,
  degree_required = excluded.degree_required,
  license_required = excluded.license_required,
  experience_required = excluded.experience_required,
  _confidence = excluded._confidence,
  _field_confidence_json = excluded._field_confidence_json,
  evidence_json = excluded.evidence_json,
  updated_at = CURRENT_TIMESTAMP;


INSERT INTO job_attributes (
  job_id, job_name, source_system, tagger_version, status,
  wlb, growth, stability, income,
  teamwork, solo_deep, analytical, creative, execution, people_facing,
  work_hours, shift_work, travel, remote_possible,
  degree_required, license_required, experience_required,
  _confidence, _field_confidence_json, evidence_json
) VALUES (
  '1765285622029694',
  '등하굣길동행도우미',
  'WORK24_DJOB',
  'tagger-v1.0.0',
  'tagged',
  70, 45, 80, 65,
  75, 55, 65, 50, 75, 95,
  'regular', 'none', 'none', 'none',
  'none', 'none', 'none',
  0.74,
  '{"wlb":0.8,"growth":0.65,"stability":0.9,"income":0.8,"teamwork":0.85,"solo_deep":0.75,"analytical":0.8,"creative":0.7,"execution":0.85,"people_facing":0.99,"degree_required":0.9,"license_required":0.9}',
  '{"wlb":"등하교 동행으로 야근 적고 교대 근무 없음, 출장 가능","growth":"교육 산업 기술 발전 기회 보통","stability":"공공사업으로 고용 안정성 매우 좋음","income":"동행 도우미로 상위 소득","teamwork":"동행 작업 협업 중요","solo_deep":"안전 동행, 상황 판단 작업으로 독립 작업 多","analytical":"위험 상황, 학생 상태로 분석 중요","creative":"동행 방법 최적화로 창의성 보통","execution":"등하굣길 동행 실행 중심","people_facing":"학생 동행 매우 多","degree_required":"고졸 정도 학력 요구","license_required":"특별 자격증 불필요"}'
)
ON CONFLICT(job_id) DO UPDATE SET
  job_name = excluded.job_name,
  tagger_version = excluded.tagger_version,
  status = excluded.status,
  wlb = excluded.wlb,
  growth = excluded.growth,
  stability = excluded.stability,
  income = excluded.income,
  teamwork = excluded.teamwork,
  solo_deep = excluded.solo_deep,
  analytical = excluded.analytical,
  creative = excluded.creative,
  execution = excluded.execution,
  people_facing = excluded.people_facing,
  work_hours = excluded.work_hours,
  shift_work = excluded.shift_work,
  travel = excluded.travel,
  remote_possible = excluded.remote_possible,
  degree_required = excluded.degree_required,
  license_required = excluded.license_required,
  experience_required = excluded.experience_required,
  _confidence = excluded._confidence,
  _field_confidence_json = excluded._field_confidence_json,
  evidence_json = excluded.evidence_json,
  updated_at = CURRENT_TIMESTAMP;


INSERT INTO job_attributes (
  job_id, job_name, source_system, tagger_version, status,
  wlb, growth, stability, income,
  teamwork, solo_deep, analytical, creative, execution, people_facing,
  work_hours, shift_work, travel, remote_possible,
  degree_required, license_required, experience_required,
  _confidence, _field_confidence_json, evidence_json
) VALUES (
  '1765285622379638',
  '양수장감시원',
  'WORK24_DJOB',
  'tagger-v1.0.0',
  'tagged',
  70, 45, 85, 70,
  70, 65, 75, 45, 75, 70,
  'regular', 'possible', 'none', 'none',
  'none', 'none', 'none',
  0.74,
  '{"wlb":0.8,"growth":0.65,"stability":0.95,"income":0.85,"teamwork":0.8,"solo_deep":0.85,"analytical":0.9,"creative":0.7,"execution":0.85,"people_facing":0.8,"degree_required":0.9,"license_required":0.9}',
  '{"wlb":"양수장 근무로 야근 가능, 교대 근무 가능, 출장 없음","growth":"환경 산업 기술 발전 기회 보통","stability":"공공사업으로 고용 안정성 매우 높음","income":"감시 작업으로 상위 소득","teamwork":"독립 작업 중심","solo_deep":"수위 모니터링, 장비 점검 작업으로 독립 작업 多","analytical":"수위 데이터 분석, 장비 상태로 분석 매우 중요","creative":"감시 시스템 최적화로 창의성 보통","execution":"양수장 감시 실행 중심","people_facing":"내부 보고 업무","degree_required":"고졸 정도 학력 요구","license_required":"특별 자격증 불필요"}'
)
ON CONFLICT(job_id) DO UPDATE SET
  job_name = excluded.job_name,
  tagger_version = excluded.tagger_version,
  status = excluded.status,
  wlb = excluded.wlb,
  growth = excluded.growth,
  stability = excluded.stability,
  income = excluded.income,
  teamwork = excluded.teamwork,
  solo_deep = excluded.solo_deep,
  analytical = excluded.analytical,
  creative = excluded.creative,
  execution = excluded.execution,
  people_facing = excluded.people_facing,
  work_hours = excluded.work_hours,
  shift_work = excluded.shift_work,
  travel = excluded.travel,
  remote_possible = excluded.remote_possible,
  degree_required = excluded.degree_required,
  license_required = excluded.license_required,
  experience_required = excluded.experience_required,
  _confidence = excluded._confidence,
  _field_confidence_json = excluded._field_confidence_json,
  evidence_json = excluded.evidence_json,
  updated_at = CURRENT_TIMESTAMP;


INSERT INTO job_attributes (
  job_id, job_name, source_system, tagger_version, status,
  wlb, growth, stability, income,
  teamwork, solo_deep, analytical, creative, execution, people_facing,
  work_hours, shift_work, travel, remote_possible,
  degree_required, license_required, experience_required,
  _confidence, _field_confidence_json, evidence_json
) VALUES (
  '1765285622729582',
  '지하철도우미',
  'WORK24_DJOB',
  'tagger-v1.0.0',
  'tagged',
  70, 45, 85, 70,
  80, 55, 65, 50, 80, 95,
  'regular', 'possible', 'none', 'none',
  'none', 'none', 'none',
  0.75,
  '{"wlb":0.8,"growth":0.65,"stability":0.95,"income":0.85,"teamwork":0.9,"solo_deep":0.75,"analytical":0.8,"creative":0.7,"execution":0.9,"people_facing":0.99,"degree_required":0.9,"license_required":0.9}',
  '{"wlb":"지하철역 근무로 야근 가능, 교대 근무 가능, 출장 없음","growth":"교통 산업 기술 발전 기회 보통","stability":"공공사업으로 고용 안정성 매우 높음","income":"도우미 작업으로 상위 소득","teamwork":"도우미 작업 협업 중요","solo_deep":"승객 안내, 상황 판단 작업으로 독립 작업 多","analytical":"승객 상황, 안전으로 분석 중요","creative":"안내 방법 최적화로 창의성 보통","execution":"지하철 도우미 실행 중심","people_facing":"승객 도움 매우 多","degree_required":"고졸 정도 학력 요구","license_required":"특별 자격증 불필요"}'
)
ON CONFLICT(job_id) DO UPDATE SET
  job_name = excluded.job_name,
  tagger_version = excluded.tagger_version,
  status = excluded.status,
  wlb = excluded.wlb,
  growth = excluded.growth,
  stability = excluded.stability,
  income = excluded.income,
  teamwork = excluded.teamwork,
  solo_deep = excluded.solo_deep,
  analytical = excluded.analytical,
  creative = excluded.creative,
  execution = excluded.execution,
  people_facing = excluded.people_facing,
  work_hours = excluded.work_hours,
  shift_work = excluded.shift_work,
  travel = excluded.travel,
  remote_possible = excluded.remote_possible,
  degree_required = excluded.degree_required,
  license_required = excluded.license_required,
  experience_required = excluded.experience_required,
  _confidence = excluded._confidence,
  _field_confidence_json = excluded._field_confidence_json,
  evidence_json = excluded.evidence_json,
  updated_at = CURRENT_TIMESTAMP;


INSERT INTO job_attributes (
  job_id, job_name, source_system, tagger_version, status,
  wlb, growth, stability, income,
  teamwork, solo_deep, analytical, creative, execution, people_facing,
  work_hours, shift_work, travel, remote_possible,
  degree_required, license_required, experience_required,
  _confidence, _field_confidence_json, evidence_json
) VALUES (
  '1765285623079526',
  '환경감시원',
  'WORK24_DJOB',
  'tagger-v1.0.0',
  'tagged',
  65, 50, 85, 70,
  75, 65, 80, 50, 75, 75,
  'regular', 'possible', 'none', 'none',
  'none', 'none', 'none',
  0.75,
  '{"wlb":0.75,"growth":0.7,"stability":0.95,"income":0.85,"teamwork":0.85,"solo_deep":0.85,"analytical":0.95,"creative":0.7,"execution":0.85,"people_facing":0.9,"degree_required":0.9,"license_required":0.9}',
  '{"wlb":"환경 감시로 야근 가능, 교대 근무 가능, 출장 가능","growth":"환경 산업 기술 발전 기회 보통","stability":"공공사업으로 고용 안정성 매우 높음","income":"감시 작업으로 상위 소득","teamwork":"감시 작업 협업 중요","solo_deep":"환경 데이터 수집, 분석 작업으로 독립 작업 多","analytical":"환경 데이터 분석, 이상 감지로 분석 매우 중요","creative":"감시 방법 최적화로 창의성 보통","execution":"환경 감시 실행 중심","people_facing":"현장 보고 업무","degree_required":"고졸 정도 학력 요구","license_required":"특별 자격증 불필요"}'
)
ON CONFLICT(job_id) DO UPDATE SET
  job_name = excluded.job_name,
  tagger_version = excluded.tagger_version,
  status = excluded.status,
  wlb = excluded.wlb,
  growth = excluded.growth,
  stability = excluded.stability,
  income = excluded.income,
  teamwork = excluded.teamwork,
  solo_deep = excluded.solo_deep,
  analytical = excluded.analytical,
  creative = excluded.creative,
  execution = excluded.execution,
  people_facing = excluded.people_facing,
  work_hours = excluded.work_hours,
  shift_work = excluded.shift_work,
  travel = excluded.travel,
  remote_possible = excluded.remote_possible,
  degree_required = excluded.degree_required,
  license_required = excluded.license_required,
  experience_required = excluded.experience_required,
  _confidence = excluded._confidence,
  _field_confidence_json = excluded._field_confidence_json,
  evidence_json = excluded.evidence_json,
  updated_at = CURRENT_TIMESTAMP;


INSERT INTO job_attributes (
  job_id, job_name, source_system, tagger_version, status,
  wlb, growth, stability, income,
  teamwork, solo_deep, analytical, creative, execution, people_facing,
  work_hours, shift_work, travel, remote_possible,
  degree_required, license_required, experience_required,
  _confidence, _field_confidence_json, evidence_json
) VALUES (
  '1765285623429470',
  '분뇨처리기술자',
  'WORK24_DJOB',
  'tagger-v1.0.0',
  'tagged',
  55, 50, 80, 75,
  75, 65, 80, 50, 80, 70,
  'regular', 'possible', 'none', 'none',
  'college', 'preferred', 'none',
  0.75,
  '{"wlb":0.65,"growth":0.7,"stability":0.9,"income":0.9,"teamwork":0.85,"solo_deep":0.85,"analytical":0.95,"creative":0.7,"execution":0.9,"degree_required":0.8,"license_required":0.8}',
  '{"wlb":"처리장 작업으로 야근 가능, 교대 근무 가능, 출장 없음","growth":"환경 산업 기술 발전 기회 보통","stability":"공공사업으로 고용 안정성 매우 좋음","income":"기술자 역할로 상위 소득","teamwork":"처리 작업 협업 중요","solo_deep":"처리 공정 모니터링, 조정 작업으로 독립 작업 多","analytical":"처리 데이터 분석, 효율 최적화로 분석 매우 중요","creative":"처리 방법 개선으로 창의성 보통","execution":"분뇨 처리 실행 중심","people_facing":"내부 협업 업무","degree_required":"전문대 정도 학력 요구","license_required":"환경 관련 자격증 선호"}'
)
ON CONFLICT(job_id) DO UPDATE SET
  job_name = excluded.job_name,
  tagger_version = excluded.tagger_version,
  status = excluded.status,
  wlb = excluded.wlb,
  growth = excluded.growth,
  stability = excluded.stability,
  income = excluded.income,
  teamwork = excluded.teamwork,
  solo_deep = excluded.solo_deep,
  analytical = excluded.analytical,
  creative = excluded.creative,
  execution = excluded.execution,
  people_facing = excluded.people_facing,
  work_hours = excluded.work_hours,
  shift_work = excluded.shift_work,
  travel = excluded.travel,
  remote_possible = excluded.remote_possible,
  degree_required = excluded.degree_required,
  license_required = excluded.license_required,
  experience_required = excluded.experience_required,
  _confidence = excluded._confidence,
  _field_confidence_json = excluded._field_confidence_json,
  evidence_json = excluded.evidence_json,
  updated_at = CURRENT_TIMESTAMP;


INSERT INTO job_attributes (
  job_id, job_name, source_system, tagger_version, status,
  wlb, growth, stability, income,
  teamwork, solo_deep, analytical, creative, execution, people_facing,
  work_hours, shift_work, travel, remote_possible,
  degree_required, license_required, experience_required,
  _confidence, _field_confidence_json, evidence_json
) VALUES (
  '1765285623779414',
  '종이원료공급원',
  'WORK24_DJOB',
  'tagger-v1.0.0',
  'tagged',
  60, 45, 75, 65,
  80, 50, 65, 45, 75, 75,
  'regular', 'possible', 'none', 'none',
  'none', 'none', 'none',
  0.73,
  '{"wlb":0.7,"growth":0.65,"stability":0.85,"income":0.8,"teamwork":0.9,"solo_deep":0.7,"analytical":0.8,"creative":0.7,"execution":0.85,"people_facing":0.9,"degree_required":0.9,"license_required":0.9}',
  '{"wlb":"공장 작업으로 야근 가능, 교대 근무 가능, 출장 없음","growth":"제조 산업 기술 발전 기회 보통","stability":"제조업으로 고용 안정성 좋음","income":"공급 작업으로 상위 소득","teamwork":"공급 작업 협업 중요","solo_deep":"원료 분류, 공급 계획 작업으로 독립 작업 多","analytical":"원료 품질, 수량으로 분석 중요","creative":"공급 최적화로 창의성 보통","execution":"종이 원료 공급 실행 중심","people_facing":"팀 협업 업무","degree_required":"고졸 정도 학력 요구","license_required":"특별 자격증 불필요"}'
)
ON CONFLICT(job_id) DO UPDATE SET
  job_name = excluded.job_name,
  tagger_version = excluded.tagger_version,
  status = excluded.status,
  wlb = excluded.wlb,
  growth = excluded.growth,
  stability = excluded.stability,
  income = excluded.income,
  teamwork = excluded.teamwork,
  solo_deep = excluded.solo_deep,
  analytical = excluded.analytical,
  creative = excluded.creative,
  execution = excluded.execution,
  people_facing = excluded.people_facing,
  work_hours = excluded.work_hours,
  shift_work = excluded.shift_work,
  travel = excluded.travel,
  remote_possible = excluded.remote_possible,
  degree_required = excluded.degree_required,
  license_required = excluded.license_required,
  experience_required = excluded.experience_required,
  _confidence = excluded._confidence,
  _field_confidence_json = excluded._field_confidence_json,
  evidence_json = excluded.evidence_json,
  updated_at = CURRENT_TIMESTAMP;


INSERT INTO job_attributes (
  job_id, job_name, source_system, tagger_version, status,
  wlb, growth, stability, income,
  teamwork, solo_deep, analytical, creative, execution, people_facing,
  work_hours, shift_work, travel, remote_possible,
  degree_required, license_required, experience_required,
  _confidence, _field_confidence_json, evidence_json
) VALUES (
  '1765285624129358',
  '지사벽지제조기조작원',
  'WORK24_DJOB',
  'tagger-v1.0.0',
  'tagged',
  60, 50, 75, 70,
  80, 60, 75, 50, 80, 75,
  'regular', 'possible', 'none', 'none',
  'none', 'none', 'none',
  0.74,
  '{"wlb":0.7,"growth":0.7,"stability":0.85,"income":0.85,"teamwork":0.9,"solo_deep":0.8,"analytical":0.9,"creative":0.7,"execution":0.9,"people_facing":0.9,"degree_required":0.9,"license_required":0.9}',
  '{"wlb":"공장 작업으로 야근 가능, 교대 근무 가능, 출장 없음","growth":"제조 산업 기술 발전 기회 보통","stability":"제조업으로 고용 안정성 좋음","income":"조작 작업으로 상위 소득","teamwork":"조작 작업 협업 중요","solo_deep":"기계 모니터링, 조정 작업으로 독립 작업 多","analytical":"생산 데이터 분석, 품질로 분석 매우 중요","creative":"조작 최적화로 창의성 보통","execution":"지사 벽지 제조기 조작 실행 중심","people_facing":"팀 협업 업무","degree_required":"고졸 정도 학력 요구","license_required":"특별 자격증 불필요"}'
)
ON CONFLICT(job_id) DO UPDATE SET
  job_name = excluded.job_name,
  tagger_version = excluded.tagger_version,
  status = excluded.status,
  wlb = excluded.wlb,
  growth = excluded.growth,
  stability = excluded.stability,
  income = excluded.income,
  teamwork = excluded.teamwork,
  solo_deep = excluded.solo_deep,
  analytical = excluded.analytical,
  creative = excluded.creative,
  execution = excluded.execution,
  people_facing = excluded.people_facing,
  work_hours = excluded.work_hours,
  shift_work = excluded.shift_work,
  travel = excluded.travel,
  remote_possible = excluded.remote_possible,
  degree_required = excluded.degree_required,
  license_required = excluded.license_required,
  experience_required = excluded.experience_required,
  _confidence = excluded._confidence,
  _field_confidence_json = excluded._field_confidence_json,
  evidence_json = excluded.evidence_json,
  updated_at = CURRENT_TIMESTAMP;


INSERT INTO job_attributes (
  job_id, job_name, source_system, tagger_version, status,
  wlb, growth, stability, income,
  teamwork, solo_deep, analytical, creative, execution, people_facing,
  work_hours, shift_work, travel, remote_possible,
  degree_required, license_required, experience_required,
  _confidence, _field_confidence_json, evidence_json
) VALUES (
  '1765285624479302',
  '전사기조작원',
  'WORK24_DJOB',
  'tagger-v1.0.0',
  'tagged',
  65, 50, 75, 70,
  75, 60, 75, 55, 80, 70,
  'regular', 'possible', 'none', 'none',
  'none', 'none', 'none',
  0.74,
  '{"wlb":0.75,"growth":0.7,"stability":0.85,"income":0.85,"teamwork":0.85,"solo_deep":0.8,"analytical":0.9,"creative":0.75,"execution":0.9,"people_facing":0.8,"degree_required":0.9,"license_required":0.9}',
  '{"wlb":"공장 작업으로 야근 가능, 교대 근무 가능, 출장 없음","growth":"인쇄 산업 기술 발전 기회 보통","stability":"제조업으로 고용 안정성 좋음","income":"조작 작업으로 상위 소득","teamwork":"조작 작업 협업 중요","solo_deep":"전사기 모니터링, 조정 작업으로 독립 작업 多","analytical":"인쇄 품질 분석, 색상으로 분석 매우 중요","creative":"인쇄 최적화로 창의성 높음","execution":"전사기 조작 실행 중심","people_facing":"작업 협업 업무","degree_required":"고졸 정도 학력 요구","license_required":"특별 자격증 불필요"}'
)
ON CONFLICT(job_id) DO UPDATE SET
  job_name = excluded.job_name,
  tagger_version = excluded.tagger_version,
  status = excluded.status,
  wlb = excluded.wlb,
  growth = excluded.growth,
  stability = excluded.stability,
  income = excluded.income,
  teamwork = excluded.teamwork,
  solo_deep = excluded.solo_deep,
  analytical = excluded.analytical,
  creative = excluded.creative,
  execution = excluded.execution,
  people_facing = excluded.people_facing,
  work_hours = excluded.work_hours,
  shift_work = excluded.shift_work,
  travel = excluded.travel,
  remote_possible = excluded.remote_possible,
  degree_required = excluded.degree_required,
  license_required = excluded.license_required,
  experience_required = excluded.experience_required,
  _confidence = excluded._confidence,
  _field_confidence_json = excluded._field_confidence_json,
  evidence_json = excluded.evidence_json,
  updated_at = CURRENT_TIMESTAMP;


INSERT INTO job_attributes (
  job_id, job_name, source_system, tagger_version, status,
  wlb, growth, stability, income,
  teamwork, solo_deep, analytical, creative, execution, people_facing,
  work_hours, shift_work, travel, remote_possible,
  degree_required, license_required, experience_required,
  _confidence, _field_confidence_json, evidence_json
) VALUES (
  '1765285624829246',
  '계면활성제포장원',
  'WORK24_DJOB',
  'tagger-v1.0.0',
  'tagged',
  65, 45, 75, 65,
  80, 50, 65, 50, 75, 75,
  'regular', 'possible', 'none', 'none',
  'none', 'none', 'none',
  0.73,
  '{"wlb":0.75,"growth":0.65,"stability":0.85,"income":0.8,"teamwork":0.9,"solo_deep":0.7,"analytical":0.8,"creative":0.7,"execution":0.85,"people_facing":0.9,"degree_required":0.9,"license_required":0.9}',
  '{"wlb":"공장 작업으로 야근 가능, 교대 근무 가능, 출장 없음","growth":"화학 산업 기술 발전 기회 보통","stability":"제조업으로 고용 안정성 좋음","income":"포장 작업으로 상위 소득","teamwork":"포장 작업 협업 중요","solo_deep":"계면활성제 취급, 포장 작업으로 독립 작업 多","analytical":"제품 품질, 안전으로 분석 중요","creative":"포장 최적화로 창의성 보통","execution":"계면활성제 포장 실행 중심","people_facing":"팀 협업 업무","degree_required":"고졸 정도 학력 요구","license_required":"특별 자격증 불필요"}'
)
ON CONFLICT(job_id) DO UPDATE SET
  job_name = excluded.job_name,
  tagger_version = excluded.tagger_version,
  status = excluded.status,
  wlb = excluded.wlb,
  growth = excluded.growth,
  stability = excluded.stability,
  income = excluded.income,
  teamwork = excluded.teamwork,
  solo_deep = excluded.solo_deep,
  analytical = excluded.analytical,
  creative = excluded.creative,
  execution = excluded.execution,
  people_facing = excluded.people_facing,
  work_hours = excluded.work_hours,
  shift_work = excluded.shift_work,
  travel = excluded.travel,
  remote_possible = excluded.remote_possible,
  degree_required = excluded.degree_required,
  license_required = excluded.license_required,
  experience_required = excluded.experience_required,
  _confidence = excluded._confidence,
  _field_confidence_json = excluded._field_confidence_json,
  evidence_json = excluded.evidence_json,
  updated_at = CURRENT_TIMESTAMP;


INSERT INTO job_attributes (
  job_id, job_name, source_system, tagger_version, status,
  wlb, growth, stability, income,
  teamwork, solo_deep, analytical, creative, execution, people_facing,
  work_hours, shift_work, travel, remote_possible,
  degree_required, license_required, experience_required,
  _confidence, _field_confidence_json, evidence_json
) VALUES (
  '1765285625179190',
  '기내용품탑재원',
  'WORK24_DJOB',
  'tagger-v1.0.0',
  'tagged',
  65, 50, 80, 75,
  85, 60, 75, 50, 80, 80,
  'regular', 'possible', 'none', 'none',
  'none', 'none', 'none',
  0.75,
  '{"wlb":0.75,"growth":0.7,"stability":0.9,"income":0.9,"teamwork":0.95,"solo_deep":0.8,"analytical":0.9,"creative":0.7,"execution":0.9,"people_facing":0.95,"degree_required":0.9,"license_required":0.9}',
  '{"wlb":"공항 작업으로 야근 가능, 교대 근무 가능, 출장 없음","growth":"항공 산업 기술 발전 기회 보통","stability":"항공업으로 고용 안정성 매우 좋음","income":"전문 탑재로 상위 소득","teamwork":"팀 탑재 작업 필수","solo_deep":"용품 분류, 탑재 계획 작업으로 독립 작업 多","analytical":"용품 무게, 안전 기준으로 분석 매우 중요","creative":"탑재 최적화로 창의성 보통","execution":"기내 용품 탑재 실행 중심","people_facing":"팀 협업 매우 多","degree_required":"고졸 정도 학력 요구","license_required":"특별 자격증 불필요"}'
)
ON CONFLICT(job_id) DO UPDATE SET
  job_name = excluded.job_name,
  tagger_version = excluded.tagger_version,
  status = excluded.status,
  wlb = excluded.wlb,
  growth = excluded.growth,
  stability = excluded.stability,
  income = excluded.income,
  teamwork = excluded.teamwork,
  solo_deep = excluded.solo_deep,
  analytical = excluded.analytical,
  creative = excluded.creative,
  execution = excluded.execution,
  people_facing = excluded.people_facing,
  work_hours = excluded.work_hours,
  shift_work = excluded.shift_work,
  travel = excluded.travel,
  remote_possible = excluded.remote_possible,
  degree_required = excluded.degree_required,
  license_required = excluded.license_required,
  experience_required = excluded.experience_required,
  _confidence = excluded._confidence,
  _field_confidence_json = excluded._field_confidence_json,
  evidence_json = excluded.evidence_json,
  updated_at = CURRENT_TIMESTAMP;

COMMIT;